### ISSUE TITLE
Installer instructions unclear and not true for my device

### ISSUE THREAD

**Issue by mouboo** [ubports/ubports-installer#760] opened 2019-04-22 11:16 UTC
The installer says to press power + volume down to get to bootloader, but for the bq e4.5 I needed to press power + volume up to get to the bootloader.
It only worked while unplugged to my computer too, which was confusing.

*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: krillin
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/CNfmP5Dh4d/

**Comment by mouboo** [comment] 2019-04-24 18:28
What can I do to confirm it? If you search for "bq e4.5 bootloader" all guides will say "Power + Volume Up" to get to the bootloader. I could maybe film pressing the buttons. 
Pressing down these buttons restarted my phone, but didn't open the bootloader screen unless it was unplugged from my computer (ubuntu 18.04). If you tell me what I can do to provide more evidence, I'll do my best to document it. Thank you.

**Comment by MK1973** [comment] 2019-05-02 15:24
I confirm this mistake: today reinstalling my Bq 4.5 due edge kill update.To get into boot-loader it is needed to hold: **"power + volume up"** . 

To succeed the device must be completely off. 

Note: (with the today edge channel update it was not possible even to power off the device, the only way was to also **"power + volume up"** and once the device was off, quickly release the buttons otherwise was starting again into normal boot that did not worked due update edge bug.)

**Comment by NeoTheThird** [comment] 2019-08-28 06:39
Duplicate of #302. Thanks for reporting.

**Closed by NeoTheThird** 2019-08-28 06:39 UTC
Labels: needs confirmation
