### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by Wangtaotaoo** [ubports/ubports-installer#1190] opened 2020-04-29 11:58 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: deb
Operating System: Linux Mint 19.3 tricia x64 
NodeJS version: v12.0.0 
Error log: https://paste.ubuntu.com//p/7y4p34vkgc/ 

it saying   "The installer failed to connect to the UBports servers" 
i am in China and i tried to use the shadowsocks...

**Comment by NeoTheThird** [comment] 2020-09-23 11:09
duplicate of #1322

**Closed by NeoTheThird** 2020-09-23 11:09 UTC
