### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by chrizgeo** [ubports/ubports-installer#1493] opened 2020-11-04 15:26 UTC
**UBports Installer `0.5.6-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-52-generic x64` with Node.js `v12.16.3`
Device: flo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa2c8219702a600079dac99
Log: https://paste.ubuntu.com//

**Error:**
```
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space
```

**Comment by NeoTheThird** [comment] 2020-11-04 15:47
Duplicate of #1087

**Closed by NeoTheThird** 2020-11-04 15:47 UTC
