### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.323s]booting...FAILED (remote: dtb not found)finished. total time: 0.345s

### ISSUE THREAD

**Issue by Aladio** [ubports/ubports-installer#544] opened 2018-11-19 22:32 UTC
*Automatically generated error report* 
UB

**Comment by Aladio** [comment] 2018-11-19 22:32
Phone bricked

**Comment by NeoTheThird** [comment] 2019-03-13 16:32
Sorry about that (and the late answer). Were you able to restore your device? What device was this, what OS and version was it running?
Duplicate of #699.

**Closed** 2019-03-25 09:59 UTC
Labels: question
