### ISSUE TITLE
Adb failed to reboot!, reboot failed: -1 : 

### ISSUE THREAD

**Issue by geminiano65** [ubports/ubports-installer#114] opened 2018-03-02 16:37 UTC
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: ia32 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/FRb4g9QrtR/

**Comment by geminiano65** [comment] 2018-03-02 16:47
I installed ubuntu xenial 16.04 in nexus 5 and when I went to vivid it gave me this error in ubuntu installer

**Comment by NeoTheThird** [comment] 2018-03-02 17:17
Possible duplicate of #43.

**Closed** 2018-03-19 09:41 UTC
Labels: needs confirmation
