### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by MJIMMYA** [ubports/ubports-installer#897] opened 2019-09-29 12:20 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.7-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [�汾 10.0.18362.356] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/V6JdHDzVNZ/

**Comment by MJIMMYA** [comment] 2019-09-29 12:24
The softwave cannot detect my phone when I reboot to bootloader, and I try to change the usb port, but there is nothing change, it is still unusable, how can I let my phone to be detected by my pc.

**Comment by NeoTheThird** [comment] 2019-10-03 22:50
Duplicate of #786. Sorry about that.

**Closed by NeoTheThird** 2019-10-03 22:50 UTC
