### ISSUE TITLE
Got stuck on Google boot logo

### ISSUE THREAD

**Issue by xander2m** [ubports/ubports-installer#1665] opened 2020-12-21 19:42 UTC
**UBports Installer `0.8.2-beta` (snap)**
Environment: `Ubuntu Core 20 linux 4.19.0-13-amd64 x64 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fe0fa7942e3b000074c0fac
Log: *N/A*

Debian 10 and Snap installer

**Comment by NeoTheThird** [comment] 2021-01-08 08:40
Sorry about that. Duplicate of #1052.

**Closed by NeoTheThird** 2021-01-08 08:40 UTC
