### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.360s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.361s

### ISSUE THREAD

**Issue by dirkvs** [ubports/ubports-installer#642] opened 2019-01-31 11:07 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Fairphone 2
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/hxzz3TFkwk/

**Comment by dirkvs** [comment] 2019-01-31 11:08
This is a brand new Fairphone 2, with no SIM card or SDA card.

Also, phone was not detected when connecting to USB.

**Comment by GermoVeltmaat** [comment] 2019-02-10 14:19
I experience the same problem on OSX and on Ubuntu (Deb or Snap)
(also New Fp2, no SIM)

**Comment by Ingo-FP-Angel** [comment] 2019-02-11 20:50
duplicate of #184

**Closed** 2019-03-10 08:51 UTC
