### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.477s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.478s

### ISSUE THREAD

**Issue by spyphi** [ubports/ubports-installer#268] opened 2018-05-19 16:05 UTC
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/vCzPjBT3xX/

**Comment by jonnius** [comment] 2018-05-21 16:54
May be a duplicate of #184

**Closed** 2018-06-06 09:04 UTC
Labels: duplicate
