### ISSUE TITLE
When finishing the install, frozen screen with Google logo & open lock.

### ISSUE THREAD

**Issue by Freredaran** [ubports/ubports-installer#1815] opened 2021-02-27 16:46 UTC
**UBports Installer `0.8.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-44-generic x64 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/603a773416ef7600077b1d52
Log: *N/A*

Solution: reboot phone in Recovery mode. Please provide this solution in the install instructions.

**Comment by NeoTheThird** [comment] 2021-03-06 17:38
sorry about that, duplicate of #1052

**Closed by NeoTheThird** 2021-03-06 17:38 UTC
