### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for martin: downloading 'boot.img'...OKAY [  0.368s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.370s

### ISSUE THREAD

**Issue by Elsur** [ubports/ubports-installer#657] opened 2019-02-14 21:49 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/DHF6b2PHVG/

**Comment by NeoTheThird** [comment] 2019-03-10 08:51
Duplicate of #184. Try again with UBports Installer 0.1.12-beta.

**Closed by NeoTheThird** 2019-03-10 08:51 UTC
