### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":fa [...]                          FAILED (File is too large to download)\r\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by silveroffspring** [ubports/ubports-installer#1499] opened 2020-11-06 09:34 UTC
**UBports Installer `0.5.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19041 win32 10.0.19041 x64 19041 0.0` with Node.js `v12.16.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa518ae9702a600079db0ec
Log: https://paste.ubuntu.com//p/NhVxqJTF74/

**Error:**
```
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\VOLKER~1\\AppData\\Local\\Temp\\1igEaIs1613hun5Q5NjwwC0zksr\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\fastboot.exe flash boot \"C:\\Users\\Volker-PC\\AppData\\Roaming\\ubports\\santoni\\firmware\\halium-boot_santoni.img\""},"stdout":"","stderr":"< waiting for any device >\r\nSending 'boot' (0 KB)                              FAILED (File is too large to download)\r\nfastboot: error: Command failed"}
```

**Comment by NeoTheThird** [comment] 2020-11-06 09:55
Duplicate of #1497

**Closed by NeoTheThird** 2020-11-06 09:55 UTC
