### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by freddyvegamarcelino** [ubports/ubports-installer#1134] opened 2020-03-07 15:37 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":false}
Package: snap
Operating System: Ubuntu Linux    18.04    bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/VSD7FwcYFH/

**Comment by NeoTheThird** [comment] 2020-03-09 17:29
Duplicate of #1132

**Closed by NeoTheThird** 2020-03-09 17:29 UTC
