### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: stdout: adb: error: failed to copy 'C:\Users\leon_domajnko\AppData\Roaming\ubports\pool\ubports-aa9dad30db962019f4dfcc58162fbb86660bc3680767af7fc20506bbefc6675f.tar.xz' to '/cache/recovery/': remote Is a directoryC:\Users\leon_domajnko\AppData\Roaming\ubports\pool\ubports-aa9dad30db962019f4dfcc58162fbb86660bc3680767af7fc20506bbefc6675f.tar.xz: 0 files pushed, 0 skipped. 300.1 MB/s (458696 bytes in 0.001s)

### ISSUE THREAD

**Issue by Soorsi** [ubports/ubports-installer#1251] opened 2020-06-07 15:34 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:true,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18363.836] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/ZxnJsT74vC/

**Comment by NeoTheThird** [comment] 2020-09-23 11:56
duplicate of #1089

**Closed by NeoTheThird** 2020-09-23 11:56 UTC
