### ISSUE TITLE
Nexus5 keep to show the logo of nexus5

### ISSUE THREAD

**Issue by m5stacking** [ubports/ubports-installer#1821] opened 2021-03-03 20:31 UTC
**UBports Installer `0.8.5-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.18363 win32 10.03 x64 18363 0.0 NodeJS v12.18.3.1836`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/603ff20b6bfdd00007c88227
Log: *N/A*

Installer says :
Error: systemimage:install: Error: {"error":{"code":1},"stdout":"adb: error: failed to copy 'C:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\pool\\ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz' to '/cache/recovery/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz': remote No space left on device\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\pool\\ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz: 1 file pushed, 0 skipped. 8.7 MB/s (392330372 bytes in 42.817s)\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\pool\\ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz.asc: 1 file pushed, 0 skipped. 0.2 MB/s (473 bytes in 0.003s)\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\pool\\device-acd68776bf09c82adc321743a0b12171ea09a9ced25c26c854eaa8bdd520860e.tar.xz: 1 file pushed, 0 skipped. 8.7 MB/s (59671712 bytes in 6.514s)\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\pool\\device-acd68776bf09c82adc321743a0b12171ea09a9ced25c26c854eaa8bdd520860e.tar.xz.asc: 1 file pushed, 0 skipped. 0.2 MB/s (473 bytes in 0.002s)\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\pool\\keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz: 1 file pushed, 0 skipped. 3.3 MB/s (1504 bytes in 0.000s)\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\pool\\keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc: 1 file pushed, 0 skipped. 0.0 MB/s (473 bytes in 0.013s)\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\pool\\version-13.tar.xz: 1 file pushed, 0 skipped. 1.2 MB/s (464 bytes in 0.000s)\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\pool\\version-13.tar.xz.asc: 1 file pushed, 0 skipped. 0.3 MB/s (473 bytes in 0.002s)\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-signing.tar.xz: 1 file pushed, 0 skipped. 0.5 MB/s (900 bytes in 0.002s)\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 0.3 MB/s (473 bytes in 0.002s)\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-master.tar.xz: 1 file pushed, 0 skipped. 0.5 MB/s (864 bytes in 0.002s)\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-master.tar.xz.asc: 1 file pushed, 0 skipped. 0.2 MB/s (473 bytes in 0.003s)\r\nC:\\Users\\aki_f\\AppData\\Roaming\\ubports\\system-image\\ubuntu_command: 1 file pushed, 0 skipped. 0.4 MB/s (728 bytes in 0.002s)\r\n13 files pushed, 0 skipped. 8.6 MB/s (452009382 bytes in 50.078s)"}

I have ignored the above message and
I have waited for 10+min, but Nexus5 just keep showing the logo of nexus5

**Comment by NeoTheThird** [comment] 2021-03-06 17:21
Sorry about that, duplicate of #1052.

**Closed by NeoTheThird** 2021-03-06 17:21 UTC
