### ISSUE TITLE
Invalid paths in sideload does not escalate error

### ISSUE THREAD

**Issue by Vince1171** [ubports/ubports-installer#1524] opened 2020-11-11 13:27 UTC
**UBports Installer `0.7.0-beta` (deb)**
Environment: `LinuxMint 20 Ulyana linux 5.4.0-52-generic x64 NodeJS v12.16.3`
Device: oneplus2
Target OS: LineageOS 16
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fabe69b9702a600079dbf69
Log: https://paste.ubuntu.com/p/kCd5CJ7bKF/

for Lineage, we need to sideload OpenGApps after Lineage. the first sideload works perfectly well but the second one is just stuck

**Comment by NeoTheThird** [comment] 2020-11-12 10:12
Difficult to reproduce due to the missing output of #1522, but what's interesting is that it doesn't even spawn the second sideload.

**Comment by Vince1171** [comment] 2020-11-13 11:25
Same issue, but with 0.7.1 for better logging (I hope)

**UBports Installer `0.7.1-beta` (deb)**
Environment: `LinuxMint 20 Ulyana linux 5.4.0-52-generic x64 NodeJS v12.16.3`
Device: oneplus2
Target OS: LineageOS
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: https://paste.ubuntu.com/p/KzGSPN4Q5y/

NOTE: I have no idea why OPEN-cuts is N/A....

**Comment by Vince1171** [comment] 2020-11-13 12:20
according to some advanced debug tools (a bunch of utils.log xD) it stuck [here](https://github.com/ubports/promise-android-tools/blob/438133d56d10964a60a463aa55ba496dc216eaad/src/adb.js#L247)
![Screenshot from 2020-11-13 13-19-10](https://user-images.githubusercontent.com/15124037/99071718-f6cd7b00-25b2-11eb-9fec-64f7071b7d43.png)

**Comment by NeoTheThird** [comment] 2020-11-13 12:37
> NOTE: I have no idea why OPEN-cuts is N/A.... (maybe because there is no 0.7.1 section in OPEN-CUTS)

Yes, because you were super quick :D OPEN-CUTS polls for new releases once per hour ;)

**Comment by Vince1171** [comment] 2020-11-13 12:49
Ok I'm a f*cking idiot
There is a type in the name of the file I try to sideload

**Comment by NeoTheThird** [comment] 2020-11-13 12:52
Whoops! That should throw an error! Needs to be handled.

**Comment by NeoTheThird** [comment] 2020-12-04 07:14
Fixed in [0.8.1-beta](https://github.com/ubports/ubports-installer/releases/tag/0.8.1-beta), afaics.

**Closed** 2020-12-04 07:15 UTC
Labels: bug
