### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/home/pierre/.cache/ubports/suzu/firmware/halium-unlocked-recovery_suzu.img\""},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'."}

### ISSUE THREAD

**Issue by Ractor20** [ubports/ubports-installer#1398] opened 2020-09-29 14:29 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/stable","wipe":true,"bootstrap":true}
Package: deb
Operating System: Linux Mint 20 ulyana x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/Mc9dTSH6QD/

**Comment by Ractor20** [comment] 2020-09-29 14:31
I installed Ubuntu Touch on Xperia X.

**Comment by NeoTheThird** [comment] 2020-09-29 15:43
Duplicate of #1377

**Closed by NeoTheThird** 2020-09-29 15:43 UTC
