### ISSUE TITLE
Fastboot: Unknown error

### ISSUE THREAD

**Issue by cmmei** [ubports/ubports-installer#839] opened 2019-07-06 03:01 UTC
Fastboot: Unknown error:  < waiting for any device >target didn't report max-download-sizesending 'recovery' (10044 KB)...FAILED (command write failed (Success))finished. total time: 0.000s

*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: flo
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/hpbPQgHN2h/

**Comment by NeoTheThird** [comment] 2019-08-27 09:31
Are you still experiencing this issue?

**Comment by NeoTheThird** [comment] 2019-08-28 06:43
Duplicate of #615.

**Closed by NeoTheThird** 2019-08-28 06:43 UTC
Labels: needs confirmation
