### ISSUE TITLE
Error: systemimage: Push failed: Failed to mount: error: {"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"}stderr: mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: Invalid argument

### ISSUE THREAD

**Issue by PauloJSPinhal** [ubports/ubports-installer#1046] opened 2019-12-01 22:09 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.11-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":false,"bootstrap":true}
Package: deb
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/fQStsF7w4w/

**Comment by NeoTheThird** [comment] 2019-12-03 13:04
@vince1171 any ideas? Looks similar to #997.

**Comment by S3sm9** [comment] 2020-01-04 02:34
Ya eh resuelto el problema, aqui la solucion:

#1089 (comment)

Es la respuesta al mismo problema que tienes.

**Comment by Vince1171** [comment] 2020-01-06 12:51
@NeoTheThird there are some big issues if the device have been updated to Android 9, due to the fstab have been changed...
So the device need to be downgraded to android 8 before installing UT :/

**Comment by bblaha** [comment] 2020-01-23 08:25
> @NeoTheThird there are some big issues if the device have been updated to Android 9, due to the fstab have been changed...
> So the device need to be downgraded to android 8 before installing UT :/

Sorry if this is a dumb question, but after formatting all partitions as per the manual how does it matter if there is android 8 or android 9 on it?

**Comment by michael71** [comment] 2020-01-23 10:29
I downgraded my OnePlus 3T to Android 8 - and, after running the UBports-installer 2(!) times, I finally had success and ubports installed fine!
thanks for the hint, @NeoTheThird !

**Comment by Vince1171** [comment] 2020-01-23 11:18
> Sorry if this is a dumb question, but after formatting all partitions as per the manual how does it matter if there is android 8 or android 9 on it?

Because Android 9 adds a vendor partition...
And it breaks the current port

**Comment by bblaha** [comment] 2020-01-23 13:13
> > Sorry if this is a dumb question, but after formatting all partitions as per the manual how does it matter if there is android 8 or android 9 on it?
> 
> Because Android 9 adds a vendor partition...
> And it breaks the current port

So I have tried downgrading to Android 8 (I took the standard Oxygen OS Oreo image) and still get the same error:
Here is my process:
Flash TWRP
Flash Oxygen OS based on AndroidOreo
(I booted into the OS and set it up just to be sure. I doublechecked the Android version which was 8.0.0)
Go back to TWRP and wipe all partitions
Start Ubinstaller and let it do its thing
After a while I get the same error. 

I tried the procedure 5 times now (since  @michael71 mentioned having to run it twice), always the same thing.
I may have missed something, though.

**Comment by Vince1171** [comment] 2020-01-23 13:34
how have you perform the downgrade?
have you use [this](https://forum.xda-developers.com/oneplus-3/how-to/op3-collection-unbrick-tools-t3896722) ?

**Comment by michael71** [comment] 2020-01-23 14:14
my downgrade procedure: I had LineageOS-16.0 running on the OnePlus3T - and used the LineageOS installation procedure ( https://wiki.lineageos.org/devices/oneplus3/install ) to install lineageos-15.1 (with TWRP wipe). After the unsuccessful first installation attempt (the UBports "O-ring" appeared only for about a second, then the device switched into the "ubuntu actions/android actions" error and the ubports-installer displayed "connection to device lost"), I put the device into fastboot mode again and restarted the ubports-installer - which then succeeded.

btw: the phone (making/receiving calls) works fine with UBports, also Wifi, browser and sending SMS work  - but the camera app crashes when I hit the "make photo" button.

**Comment by bblaha** [comment] 2020-01-23 15:38
> how have you perform the downgrade?
> have you use [this](https://forum.xda-developers.com/oneplus-3/how-to/op3-collection-unbrick-tools-t3896722) ?

I wiped the phone completely using TWRP and then flashed the Oxygen OS version with Android Oreo. I can't really follow your manual as I am on Ubuntu (on Desktop, that is). Tried to look for a Linux alternative, but could not find one.
I will now try @michael71 s approach (although I could not find any lineageos-15.1 version that is compatible with OP3), but I do not really have much hope since it is very similar to what I did.
Will report back with the results.

**Comment by Zocker1999NET** [comment] 2020-06-26 12:45
I ran into the same issue today after getting a OP3
@michael71 If you still have the Lineage OS 15.1 image, can you upload it somewhere or send a link to where you found the image? The official Lineage Download server does not list a 15.1 version anymore and I haven't found one on the web either so far.

**Comment by Zocker1999NET** [comment] 2020-06-26 22:42
For reference, I've found an [Oxygen OS image](https://archive.org/details/oos-9.0.2-op3-3t) and a [Lineage OS 15.1 image](https://archive.org/details/lineage-15.1-20190208-nightly-oneplus3-signed), both based on Android 8.0 Oreo, at archive.org, maybe these help someone to flash their device.

With the Oxygen OS image sideloaded and booted before, I came to the error "connection to device lost" while the phone was in the recovery installed by ubports installer, but running the installer multiple times does not solve this issue.
I'm currently on to test it with the Lineage OS 15.1 image, I hope this does work. (I will report back by editing this comment)

**Comment by Zocker1999NET** [comment] 2020-06-27 22:06
For my case, I found the reason of the "lost connection" error of the installer, the error always happens on a native USB 3.0 port, but not on a USB 2.0 port. I could install ubports without any problem using the installer (after I sideloaded an Android Oreo image). @bblaha maybe you had a similar problem back then?

**Comment by NeoTheThird** [comment] 2020-09-23 08:44
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:44 UTC
Labels: bug
