### ISSUE TITLE
Won't boot into Ubuntu

### ISSUE THREAD

**Issue by iainrosen** [ubports/ubports-installer#1761] opened 2021-01-28 06:48 UTC
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60125e2cafa951000786c243
Log: https://paste.ubuntu.com/p/g5npGjqyzZ/

Only boots into UBPorts recovery, shows error "This phone needs restoring from a PC or service center"

**Comment by NeoTheThird** [comment] 2021-03-06 17:31
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:31 UTC
