### ISSUE TITLE
boot loop to Google screen

### ISSUE THREAD

**Issue by tomtdl** [ubports/ubports-installer#2070] opened 2021-08-07 03:13 UTC
**UBports Installer `0.8.8-beta` (deb)**
Environment: `LinuxMint 20.1 Ulyssa linux 5.4.0-80-generic x64 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Tried in USB3 port,  will now try again in USB2 port...

**Comment by NeoTheThird** [comment] 2022-03-19 19:13
this is seems to be a a duplicate of #1537. Please try [these steps](https://github.com/ubports/ubports-installer/issues/1537#issuecomment-792346472) to get it to work. sorry for the inconvenience :)

**Closed by NeoTheThird** 2022-03-19 19:13 UTC
