### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.368s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.369s

### ISSUE THREAD

**Issue by aleins** [ubports/ubports-installer#512] opened 2018-10-21 08:12 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/GTZCKKD88P/ 
I tryed to flash my FP2 und failed. I don't know how to proceed now

**Comment by jonnius** [comment] 2018-10-27 07:32
duplicate of #184

**Closed** 2019-03-10 09:00 UTC
Labels: duplicate
