### ISSUE TITLE
Installer fails sending files to arale

### ISSUE THREAD

**Issue by DiogoConstantino** [ubports/ubports-installer#1602] opened 2020-12-04 15:31 UTC
The installer fails to send files to arale, it starts sending, or at least it say so, but never completes it, and also never decides it has failed to do so.
I'm also not sure how much of sending was actually made, and knowing what's the transfer rate (average and current) would also be good. Also ideally would be good to have that type of feedback both on the installer and on the device, and would be good to also have a way to know which end is dropping a connection, and if there're any logs to display them or store them somewhere where they can be used by the user, and eventually removed.

**Comment by NeoTheThird** [comment] 2020-12-04 16:11
Duplicate of #1593

**Closed by NeoTheThird** 2020-12-04 16:11 UTC
