### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":fa [...]                 FAILED (remote: 'not supported in locked device')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by niweiwang** [ubports/ubports-installer#1483] opened 2020-10-30 12:41 UTC
**UBports Installer `0.5.6-beta` (dmg)**
Environment: `Mac OS X 10.13.6 macOS High Sierra darwin 17.7.0 x64 17G14033` with Node.js `v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f9c09da9702a600079da037
Log: https://paste.ubuntu.com//p/W5cgyrSHtd/

**Error:**
```
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"/Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/node_modules/android-tools-bin/dist/darwin/x86/fastboot\" flash boot '/Users/yiwei/Library/Caches/ubports/hammerhead/firmware/boot-hammerhead.img'"},"stdout":"","stderr":"Sending 'boot' (12302 KB)                          OKAY [  0.578s]\nWriting 'boot'                                     FAILED (remote: 'not supported in locked device')\nfastboot: error: Command failed"}
```

**Comment by NeoTheThird** [comment] 2020-10-30 22:09
Duplicate of #1468. Should be fixed in [this pre-release version](https://github.com/ubports/ubports-installer/releases/tag/0.6.0-beta).

**Closed by NeoTheThird** 2020-10-30 22:09 UTC
