### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >target didn't report max-download-sizesending 'recovery' (12592 KB)...OKAY [  0.408s]writing 'recovery'...FAILED (remote: image is not a boot image)finished. total time: 0.411s

### ISSUE THREAD

**Issue by maximbaturov** [ubports/ubports-installer#561] opened 2018-11-29 19:54 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 7 2013 (LTE)
Package: unknown
Operating System: Ubuntu Linux 18.10 cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/dcN76sqcjj/ 

Also screenshot: https://www.dropbox.com/s/i7z2kiu47fgpll9/Screenshot%20from%202018-11-29%2021-55-05.png?dl=0

**Comment by prasadjacky** [comment] 2018-12-24 07:50
Were you able to work around this error?

**Comment by NeoTheThird** [comment] 2019-03-10 16:32
Duplicate of #639.

**Closed by NeoTheThird** 2019-03-10 16:32 UTC
