### ISSUE TITLE
Error: systemimage: Error: Can't find latest version: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by userj** [ubports/ubports-installer#1338] opened 2020-09-07 04:01 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: kagura
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/stable","wipe":false,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/wZSvQfGVK7/

**Comment by userj** [comment] 2020-09-07 04:15
Maybe not a bug. I guess there's no stable image yet.

**Comment by NeoTheThird** [comment] 2020-09-23 08:35
Duplicate of #1340

**Closed by NeoTheThird** 2020-09-23 08:35 UTC
