### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by octaviusdaivnci** [ubports/ubports-installer#164] opened 2018-03-24 15:51 UTC
Hi,

 can someone hlep me to sort out this while installing UBUNTU TOUCH from windows 10 this error is appearing 

![opo ubuntu error](https://user-images.githubusercontent.com/8819939/37865918-1fdf9850-2fa9-11e8-837f-6dd2ca0de6e0.PNG)

Adb push error: cannot stat ''C:\Users\<user>\AppData\Roaming\ubports\pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz'': No such file or directory

**Comment by gsilvapt** [comment] 2018-03-26 21:55
Have you tried again? The error seems to be that it could not find the file for some reason.

**Comment by octaviusdaivnci** [comment] 2018-03-27 00:57
I tried again then the installation process freezes and the process got
stuck there itself not progressing.

**Comment by gsilvapt** [comment] 2018-03-27 08:51
Can you confirm all paths in the logs have double-quotes instead of single quotes? Reference to issue #152 Also, there seems to be a similar experience in #110 after _pool_.

**Comment by NeoTheThird** [comment] 2018-04-30 20:28
Thanks for reporting! Duplicate of #110.

**Closed by NeoTheThird** 2018-04-30 20:28 UTC
