### ISSUE TITLE
adb errors

### ISSUE THREAD

**Issue by jaydenorjaiden** [ubports/ubports-installer#1842] opened 2021-03-10 16:29 UTC
**UBports Installer `0.8.7-beta` (deb)**
Environment: `Ubuntu 20.04.2 LTS Focal Fossa linux 5.8.0-44-generic x64 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6048f3db52bd840007f9205e
Log: *N/A*

just installing using the deb package on Ubuntu 20.04 and it gave me an adb error and its stuck on the bootlogo now

**Comment by NeoTheThird** [comment] 2021-03-10 20:37
duplicate of #1052

**Closed by NeoTheThird** 2021-03-10 20:37 UTC
