### ISSUE TITLE
install on Nexus 7 2013: can t boot

### ISSUE THREAD

**Issue by CharlesGueunet** [ubports/ubports-installer#782] opened 2019-05-12 12:20 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: flo
Channel: ubports-touch/16.04/devel
Package: dir
Operating System: Arch Linux undefined undefined x64 
NodeJS version: v10.11.0 

Tested with: 
* 15.04 stable
* 16.04 stable
* 16.04 dev

## Install: UBports 0.2.2-beta

no error reported during install process. fail during boot:
```
This phone needs restoring from PC or repair service.
```

## Install manially

* The recovery (cwm) warn about `e2fsck` fail with return 8
* After having pushed everything into `/cache/recovery/`, a reboot to recovery does nothing and this folder is still empty.

Error log: http://paste.ubuntu.com/p/xkbM2Mqfpg/

**Comment by billmarrs** [comment] 2019-07-10 16:41
I think I may be experiencing this same issue.  I made a forum topic about it here: 
https://forums.ubports.com/topic/2909/trouble-with-install-on-nexus-7-2013-wifi-flo
I posted some images of the e2fsck and mount errors in recovery mode.

**Comment by LibertatisPrius** [comment] 2019-07-10 17:49
I ran into this last night. It appears the problem (for me at least) was the data partition had been corrupted and was no longer mountable. I worked around it by flashing TWRP to recovery and reformatting data (it would only let me reformat the partition by going into Wipe and under Advanced (iirc) selecting just the data partition.

I did after that flash an unofficial Lineage build but never rebooted before trying to install Ubuntu Touch again at which point everything just worked. (I was using the 0.2.3-beta installer at that point for the record).

**Comment by billmarrs** [comment] 2019-07-10 22:44
The main error I'm getting from the ubuntu recovery mode looks like this:

E:e2fsck for device [/dev/block/platform/msm_sdcc.1/by-name/cache] failed with 8

I don't really understand this, but guessing... it's the device for the cache partition, fsck fails and it can't mount it either.  So, Ubuntu Touch install fails and the OS isn't updated (I can reboot and the old OS still works).  

I tried using TWRP to "repair" cache (also did it for all other partitions) using the Wipe->Advanced page.  That seems to also run e2fsck and doesn't show any errors.  But, after UT install still fails in the same way for me and I still see the e2fsck failed with 8 messages on the recovery screen.  So, I tried using "adb shell" to run e2fsck -fv by hand on cache and other partitions.  It seemed to run without errors (nothing to fix), as if they were all fine.   So, I'm not sure what's up with my Nexus 7.  I can restore it to stock Android and it seems fine.  I've also loaded LineageOS and it seemed to work well too.  So, I don't know what's different about Ubuntu Touch.  

I think my partitions are all ext4.  TWRP seems to have a way to change them to another fstype, if that might help.  I've seen some stuff about superblocks, not sure if that matters.  There may be a fsck log (/var/log/fsck/checkfs ?) with more info (was going to look for that next time I try this)...

**Comment by billmarrs** [comment] 2019-07-11 13:19
After looking at this more (I'm using 'adb shell' to look around while in UT recovery), I think the issue is that the devices for /cache /userdata and /system are not being created.

/tmp/recovery.log has errors like this:
/sbin/e2fsck: No such file or directory while trying to open /dev/block/platform/msm_sdcc.1/by-name/cache
Possibly non-existent device?
E:e2fsck check for device [/dev/block/platform/msm_sdcc.1/by-name/cache] failed with 8

/dev/block/platform/msm_sdcc.1/by-name/cache does not exist.  There is no /dev/block/platform at all actually.  

In comparison, twrp's recovery has these devices and works fine.   I don't know enough about the system to figure out why Ubuntu Touch's recovery does not create these devices.  But, without them, it can't e2fsck them or mount them and thus nothing gets installed.

Otherwise, it's not hard to restore the Nexus back to stock Android (Nexus Root Toolkit works well or see https://developers.google.com/android/images to do it by hand).

**Comment by billmarrs** [comment] 2019-07-11 13:47
Also, worth noting that in twrp's recovery /dev/block/platform/msm_sdcc.1/by-name/cache is a symlink: /dev/block/platform/msm_sdcc.1/by-name/cache -> /dev/block/mmcblk0p23 
/dev/block/mmcblk0p23 doesn't exist in UT's recovery either

**Comment by NeoTheThird** [comment] 2019-08-27 10:12
Could you confirm this is still an issue with the latest version?

**Comment by CharlesGueunet** [comment] 2019-08-27 11:22
I have change my internal partition on my Nexus 7 since I posted this issue, so I think a test would not be relevant anymore with my device.
@billmarrs can you try to reproduce the issue ?
Otherwise, I might reset the partition of my tablet but I won't have time for this this week.

**Comment by NeoTheThird** [comment] 2019-08-27 12:11
Okay, thanks

**Comment by NeoTheThird** [comment] 2019-08-27 13:35
Duplicate of #615.

**Closed by NeoTheThird** 2019-08-27 13:35 UTC
Labels: bug

**Comment by CharlesGueunet** [comment] 2019-11-22 19:00
The issue is now fixed

**Comment by NeoTheThird** [comment] 2019-11-22 20:30
Good to hear :)
