### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by SaanilTaneja** [ubports/ubports-installer#1262] opened 2020-06-22 01:18 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":true}
Package: dmg
Operating System: macOS 10.15.519F101 x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/JKjzdh4gZf/

**Comment by NeoTheThird** [comment] 2020-09-23 09:57
Duplicate of #1087

**Closed by NeoTheThird** 2020-09-23 09:57 UTC
