### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell echo ."},"stdout":"","stderr":"error: device unauthorized.\nThis adb server's $ADB_VENDOR_KEYS is not set\nTry 'adb kill-server' if that seems wrong.\nOtherwise check for a confirmation dialog on your device."}

### ISSUE THREAD

**Issue by dvatstation** [ubports/ubports-installer#1278] opened 2020-07-03 11:09 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/N9t33NfJYK/

**Comment by NeoTheThird** [comment] 2020-09-23 09:12
Duplicate of #983

**Closed by NeoTheThird** 2020-09-23 09:12 UTC
