### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by JanArneFagertun** [ubports/ubports-installer#1158] opened 2020-04-01 17:37 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":false}
Package: deb
Operating System: Debian  10  buster x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/K43tdXSBCb/

**Comment by JanArneFagertun** [comment] 2020-04-01 17:42
I have been upgrading from the devel channel, and a couple of weeks ago the Nexus 5 started to hang during boot.
I have tried to reinstall, but no go. It seems like ubports-installer finds the phone after I have selected it manually.
I have tried to do a manual install.
Is there an option to force install?

**Comment by NeoTheThird** [comment] 2020-04-01 18:57
Duplicate of #983. There will be a popup for on the device, where you have to confirm adb access. If you do that, the installer will work.

**Comment by JanArneFagertun** [comment] 2020-04-04 09:51
Hmm - I have seen somebody commented at this popup before, but I have never seen it. Neither at the device (Nexus 5), nor at the PC screen.
ubports-installer does not recognize my Nexus 5, so I choose it manually. After that I get a popup warning about that this works only on Hammerhead, which it is.
After a while the install process stops with an error message ("yikes....").

I started ubports-installer from the command line, and this is the ouput:

~ (11:33:00) $ ubports-installer 
info: Welcome to the UBports Installer version 0.4.17-beta!
info: Downloaded file 1 of 2
info: Downloaded file 2 of 2
error: Error: adb:format: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell echo ."},"stdout":"","stderr":"error: device unauthorized.\nThis adb server's $ADB_VENDOR_KEYS is not set\nTry 'adb kill-server' if that seems wrong.\nOtherwise check for a confirmation dialog on your device."}
stack trace: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell echo ."},"stdout":"","stderr":"error: device unauthorized.\nThis adb server's $ADB_VENDOR_KEYS is not set\nTry 'adb kill-server' if that seems wrong.\nOtherwise check for a confirmation dialog on your device."}
    at /opt/ubports-installer/resources/app.asar/node_modules/promise-android-tools/src/adb.js:66:13
    at /opt/ubports-installer/resources/app.asar/src/utils.js:282:7
    at ChildProcess.exithandler (child_process.js:319:5)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Socket.<anonymous> (internal/child_process.js:403:11)
    at Socket.emit (events.js:194:13)
    at Pipe.<anonymous> (net.js:593:12)
info: Good bye!

I have tried to kill the adb server::
root@laptop:/home/janaf/Nedlastinger# adb kill-server
cannot connect to daemon at tcp:5037: Connection refused

Afterwards I started the adb server (adb -start-server) and tried ubports-installer again, but with the same result.

**Comment by JanArneFagertun** [comment] 2020-04-07 21:58
Here is the "list of devices" when I start the Nexus 5 in recovery mode:

root@laptop:/home/janaf/Nedlastinger# adb devices
List of devices attached
0390fc8c25228dfe	unauthorized

So - it looks like the device is found, somehow. Is this useful information?

**Comment by jafPowelNo** [comment] 2020-04-29 05:13
I see that (two or more) files are getting uploaded to the Nexus, so it is obvious that the device is found.
Is there no possibility to force install/update?

**Comment by NeoTheThird** [comment] 2020-09-23 09:12
Duplicate of #983

**Closed by NeoTheThird** 2020-09-23 09:12 UTC
Labels: question
