### ISSUE TITLE
Please reboot to bootloader

### ISSUE THREAD

**Issue by igoratomubootski** [ubports/ubports-installer#251] opened 2018-05-13 08:06 UTC
Notebook XMG P505
-Win10 x64, newest
-USB 3
Oneplus One
-LineageOS 14.1
-TWRP Recovery

The installer stops and says the phone must be in bootloader mode to continue but the phone is in bootloader mode and the computer notices it. The phone is reachable via ADB Command but the installer still does nothing.
Hope someone can help, THX for answers!

**Comment by NeoTheThird** [comment] 2018-05-13 08:45
If the phone is in bootloader mode, it can not be reachable w/ the adb command. The utility to communicate w/ the bootloader is fastboot.

There seem to be problems with TWRP (#52). Could you try installing with the stock rom and recovery?

**Comment by fw190d13** [comment] 2018-05-13 09:32
I can confirm this but on Solus Linux. I get a please reboot to bootloader although the phone is already there.

**Comment by igoratomubootski** [comment] 2018-05-13 15:51
So, phone reset to stock rom, OxygenOS with stoch recovery but the problem still exists. Computer shows phone and the phone responds when connected. But the installer does not show the device and so still no install.

**Comment by NeoTheThird** [comment] 2018-05-13 16:29
Strange. By the way, to avoid hitting #110 later, you'll have to use [version 0.1.9-beta](https://github.com/ubports/ubports-installer/releases/download/0.1.9-beta/ubports-installer.0.1.9-beta.exe). That won't solve this problem, though.

So, to recap, you've got the stock rom on there, adb (aka usb-debugging) and oem-unlocking is enabled in the android developer mode settings, windows adb drivers are installed and adb and fastboot recognize the device. If you open the installer with the device plugged in, it is not recognized, and if you select the oneplus one from the dropdown list and complete the initial installation settings, the installation does not proceed. Correct?

Before you try again, please delete the file `%APPDATA%\ubports\ubports-installer.log`. Then, please try again to the point where the installation gets stuck and upload the file here. Verify that your device is actually in bootloader mode (eg look at the screen of the device) and check if your PC detects it (eg run the `fastboot.exe devices` utility). If that's not successful, try plugging in the device to a new usb outlet on your computer, or try with a different usb cable.

**Comment by fw190d13** [comment] 2018-05-13 16:53
Fastboot and adb detect my phone OK. I have a spare Mint laptop which I have to use when I'm trying to install.

**Comment by NeoTheThird** [comment] 2018-05-13 17:00
@fw190d13 Your issue is most likely not related to this one, as Windows handles Android devices very differently from Linux.

**Comment by shooreekspb** [comment] 2018-05-14 11:58
hello
I have nexus 4 with restored factory image by Nexus Root Toolkit (it means drivers are correct). But when I start to use UBports installer, nothing happens after asking to reboot into bootloader mode.
Ia there an option to save a log and to share with you to find an issue?
![default](https://user-images.githubusercontent.com/39265811/39996111-2606ec78-5787-11e8-9296-549e69f2194b.PNG)

**Comment by NeoTheThird** [comment] 2018-05-14 12:18
@shooreekspb Yes please, the log can be found at `%APPDATA%\ubports\ubports-installer.log`.

**Comment by shooreekspb** [comment] 2018-05-14 12:47
Please see attached.
Thanks.
[ubports-installer.log](https://github.com/ubports/ubports-installer/files/2000713/ubports-installer.log)

**Comment by shooreekspb** [comment] 2018-05-18 05:53
Dear NeoTheThird,
Do you have any ideas?
Is there another way to install UT without UBports?

**Comment by Flohack74** [comment] 2018-07-04 08:30
@shooreekspb Can you try this test build plz, it might still have issues detecting the phone, but once it is in fastboot/bootloader mode, everything went fine for me: https://ci.appveyor.com/api/buildjobs/6y6may7umpkpscfj/artifacts/dist%2Fubports-installer%200.1.17-beta.exe

**Comment by NeoTheThird** [comment] 2018-07-04 22:01
Please try again with [the latest release](https://github.com/ubports/ubports-installer/releases/latest).

**Comment by timikesmarky** [comment] 2019-02-11 01:11
I have the same issue. How to fix it?
Can't I install this manually like android factory image?

**Comment by NeoTheThird** [comment] 2019-03-18 21:19
Sorry about the delay, everyone...

@foolishchow Thanks for the hint. Solved in #710.

@timikesmarky We'll soon have a new release that includes the fix for this. In the mean time, you can follow the manual install intructions on [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io).

Thanks for your patience and your help in solving this issue! Since some of you already started to familiarize themselves with the source code, we could use your help [on some other issues](https://github.com/ubports/ubports-installer/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) as well, if you're interested.

**Closed** 2019-03-18 21:19 UTC
Labels: question
