### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by southsidetoker** [ubports/ubports-installer#761] opened 2019-04-22 12:52 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.2-be I'm trying to flash my fairphone with ubuntu touch and it is not recognising the usb connection and it's not booting to the android logo after I choose manual installation and booting to bootloader, the fairphone ta 
Device: FP2 just displays a black screen and the fairphone logo ands sticks doing nothing I have already installed the universal ADB driver. but nothing is working
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.17134.706] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/ByKXDch9k8/

**Comment by NeoTheThird** [comment] 2019-04-24 13:57
duplicate of #762

**Closed by NeoTheThird** 2019-04-24 13:57 UTC
