### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.366s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.368s

### ISSUE THREAD

**Issue by eliasrudberg** [ubports/ubports-installer#493] opened 2018-10-13 15:32 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Fairphone 2
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/kMzhqThjY9/

**Comment by jonnius** [comment] 2018-10-27 07:31
duplicate of #184

**Closed** 2019-03-10 09:00 UTC
Labels: duplicate
