### ISSUE TITLE
Error: Unknown: error: {"killed":false,"code":127,"signal":null,"cmd":"/home/alfred/snap/ubports-installer/211/.cache/ubports/platform-tools/adb -P 5037 kill-server"}stderr: /bin/sh: 1: /home/alfred/snap/ubports-installer/211/.cache/ubports/platform-tools/adb: not found

### ISSUE THREAD

**Issue by fredldotme** [ubports/ubports-installer#914] opened 2019-10-05 22:06 UTC
*Automatically generated error report* 
UBports Installer Version: 0.3.2-beta 
Device: Not detected
Channel: Not yet set
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/FCJKfcKyqQ/

**Comment by NeoTheThird** [comment] 2019-10-05 22:27
Duplicate of #913. Thanks for the log, though.

**Closed by NeoTheThird** 2019-10-05 22:27 UTC
