### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >downloading 'boot.img'...OKAY [  0.332s]booting...FAILED (remote: unknown command)finished. total time: 0.334s

### ISSUE THREAD

**Issue by ricsipontaz** [ubports/ubports-installer#397] opened 2018-08-02 19:19 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ Aquaris E4.5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/yzqg9MT2C2/

**Comment by dayrover** [comment] 2018-08-03 15:01
This is the same error as:
Ubuntu Installation on Fairphone 2 does not continue. #387

**Comment by NeoTheThird** [comment] 2019-03-13 14:58
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.

**Closed by NeoTheThird** 2019-03-13 14:58 UTC
