### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by luckyamber** [ubports/ubports-installer#424] opened 2018-08-27 14:23 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: exe
Operating Syst
my phone already have been reboot bootloader,but didn't get to  next step.

**Comment by NeoTheThird** [comment] 2019-03-10 09:34
Duplicate of #658

**Closed by NeoTheThird** 2019-03-10 09:34 UTC
