### ISSUE TITLE
Loop at Google Logo (tried on 2 nexus 5)

### ISSUE THREAD

**Issue by neshby** [ubports/ubports-installer#374] opened 2018-07-17 00:19 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Nexus 5
Package: exe
Operating Syst

**Comment by NeoTheThird** [comment] 2019-03-10 10:03
Duplicate of #116.

**Closed by NeoTheThird** 2019-03-10 10:03 UTC
