### ISSUE TITLE
can't flash had developer mode activated

### ISSUE THREAD

**Issue by McMarius11** [ubports/ubports-installer#1565] opened 2020-11-21 13:33 UTC
**UBports Installer `0.7.4-beta` (AppImage)**
Environment: `ManjaroLinux 20.2 Nibia linux 5.9.8-2-MANJARO x64 rolling NodeJS v12.16.3`
Device: yggdrasil
Target OS: VollaOS
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fb917349702a600079dda08
Log: https://paste.ubuntu.com/p/CwXHp8xBQ5/

enable developert mode

this is the error i get 

Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'download for partition 'recovery' is not allowed')fastboot: error: Command failed"}

**Comment by NeoTheThird** [comment] 2020-11-21 13:52
Sorry about that. Please reboot the device to fastboot mode and run `fastboot flashing unlock` in the terminal. Duplicate of #1479.

**Closed by NeoTheThird** 2020-11-21 13:52 UTC
