### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by basketwill** [ubports/ubports-installer#623] opened 2019-01-22 15:07 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 4
Package: exe
Operating System windows 10 X64，don‘t find device bootloader

**Comment by NeoTheThird** [comment] 2019-03-10 09:54
duplicate of #685

**Closed by NeoTheThird** 2019-03-10 09:54 UTC
