### ISSUE TITLE
unable to reboot to bootloader on deb

### ISSUE THREAD

**Issue by doniks** [ubports/ubports-installer#1445] opened 2020-10-11 11:20 UTC
**UBports Installer `0.5.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-47-generic x64` with Node.js `v12.16.3`
Device: deb
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f82e9b304d6b6000750b2ee
Log: https://paste.ubuntu.com//p/tT8CP5B3bz/

* OPENCUTS=true ubports-installer
* device gets detected
* select RC, leave everything else as defaults
-> installer just sits on the screen with "Rebooting to bootloader" and device just keeps running regular UT without rebooting

* when I `cd /snap/ubports-installer/current/app/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86` I can `./adb shell` log in to the device ok 
* when I then run `sudo reboot -f bootloader` on the device it does reboot and the installer continues
* installer finishes with PASS https://ubports.open-cuts.org/run/5f82ebb504d6b6000750b2f2 
* update on the device finishes ok, device reboots and works ok with new os version

**Comment by NeoTheThird** [comment] 2020-10-11 13:37
This is really weird, because the step doesn't actually seem to be executed. The log just announces that the step is being run, but adb is not called. Maybe a race codition? Maybe the download step before is doing something weird to it? Needs investigation.

**Comment by NeoTheThird** [comment] 2020-10-28 11:10
duplicate of #1367

**Closed by NeoTheThird** 2020-10-28 11:10 UTC
Labels: needs confirmation
