### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/usr/share/ubports-installer/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: Invalid argument"}

### ISSUE THREAD

**Issue by DickThomas** [ubports/ubports-installer#1287] opened 2020-07-07 17:07 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":false,"bootstrap":true}
Package: dir
Operating System: Arch Linux rolling undefined x64 
NodeJS version: v12.4.0 

Error log: https://paste.ubuntu.com//p/ZJzVs2HYyf/ 
 

I followed the instructions on the installer and  I got an error.. 
Not sure what else I can say, sorry

**Comment by wizzymt** [comment] 2020-08-14 18:08
same issue, my device keep restarting :(

**Comment by NeoTheThird** [comment] 2020-09-23 08:42
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:42 UTC
