### ISSUE TITLE
OnePlus One is not detected in either Auto mode nor Manual

### ISSUE THREAD

**Issue by DrMagicWolf** [ubports/ubports-installer#390] opened 2018-07-26 17:45 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: OnePlus One
Package: exe
Operating

**Comment by DrMagicWolf** [comment] 2018-07-26 17:46
- I still can't install UT on my OnePlus One as it doesn't get autodetected even though Debug mode is on and "adb devices" returns the device ID, even when choosing manual mode it gets stuck at the reboot to fastboot stage, even though "fastboot devices" returns the device ID fine.

**Comment by fabrei** [comment] 2018-09-03 08:36
i had a similar problem. maybe [this](https://github.com/ubports/ubports-installer/issues/416#issuecomment-417250720) helps :)

**Comment by NeoTheThird** [comment] 2019-03-10 10:04
Duplicate of #116.

**Closed by NeoTheThird** 2019-03-10 10:04 UTC
