### ISSUE TITLE
Had to start installation again and use instructions in video tutorial

### ISSUE THREAD

**Issue by CppBaddy** [ubports/ubports-installer#1787] opened 2021-02-08 03:47 UTC
**UBports Installer `0.8.4-beta` (deb)**
Environment: `Ubuntu 16.04.4 LTS Xenial Xerus linux 4.15.0-133-generic x64 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6020b38dafa951000786e48e
Log: *N/A*

Follow installer steps and select device auto detection. Setup stall in copying files step.

**Comment by NeoTheThird** [comment] 2021-03-06 17:36
sorry about that, duplicate of #1052

**Closed by NeoTheThird** 2021-03-06 17:36 UTC
