### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.786s]booting...FAILED (remote: unknown command)finished. total time: 0.800s

### ISSUE THREAD

**Issue by Makc-DT** [ubports/ubports-installer#671] opened 2019-02-22 11:06 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu MX4
Package: snap
Operating System: elementary OS   undefined   undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/wQpp62q4Zp/

**Comment by NeoTheThird** [comment] 2019-03-13 14:53
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.

**Closed by NeoTheThird** 2019-03-13 14:53 UTC
