### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 268435456 bytessending 'recovery' (10046 KB)...OKAY [  0.316s]writing 'recovery'...FAILED (remote: Partition flashing is not allowed)finished. total time: 0.320s

### ISSUE THREAD

**Issue by AlphaDVX** [ubports/ubports-installer#577] opened 2018-12-08 16:46 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: BQ Aquaris E5
Package: snap
Operating System: Ubuntu Linux   18.04   bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/HcxqwDW7nx/ 

I have also tried via Android Studio to push via ADB a Lineage *.apk but I have always the same answer : directory or device locked.
Always the same path is blocking : /dev/block/

**Comment by NeoTheThird** [comment] 2019-03-13 14:48
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.

**Closed by NeoTheThird** 2019-03-13 14:48 UTC
