### ISSUE TITLE
The installer locks up in recovery mode during preparing system img.

### ISSUE THREAD

**Issue by tarrreltonp** [ubports/ubports-installer#1452] opened 2020-10-20 21:02 UTC
**UBports Installer `0.5.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.3.0-64-generic x64` with Node.js `v12.16.3`
Device: bacon
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f8f4fa7fd51f200075a48c6
Log: https://paste.ubuntu.com//p/b6tFMMx6YY/

happens when installation is not recovery mode during preparing img.

**Comment by NeoTheThird** [comment] 2020-10-21 14:27
Duplicate of #983

**Closed by NeoTheThird** 2020-10-21 14:27 UTC
