### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for joe: downloading 'boot.img'...OKAY [  0.709s]booting...FAILED (remote failure)finished. total time: 0.709s

### ISSUE THREAD

**Issue by kigula23** [ubports/ubports-installer#550] opened 2018-11-25 15:22 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/XNtPk6sbjj/

**Comment by NeoTheThird** [comment] 2019-03-13 15:50
What OS is the device running?

**Comment by NeoTheThird** [comment] 2019-03-17 16:48
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.

**Closed by NeoTheThird** 2019-03-17 16:48 UTC
Labels: question

**Comment by kigula23** [comment] 2019-03-30 08:11
Ut

**Comment by NeoTheThird** [comment] 2019-03-30 09:34
Ok, you can just try again with our latest prerelease and it should be ok: https://github.com/ubports/ubports-installer/releases/tag/0.2.2-beta
