### ISSUE TITLE
Nexus 6P stuck in Ubport recovery bootloop after installation

### ISSUE THREAD

**Issue by BJL-DevNurse** [ubports/ubports-installer#1661] opened 2020-12-20 10:44 UTC
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 10 Home Insider Preview 10.0.20231 win32 10.0.20231 x64 20231 0.0 NodeJS v12.16.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fdf2aec42e3b000074c0b33
Log: *N/A*

After reportedly succesful installation, device will only reboot into Ubport recovery mode. Won't boot Ubuntu Touch.

**Comment by billypeanut** [comment] 2021-01-09 18:00
Same issue here...

**Comment by joxdiaz** [comment] 2021-01-26 04:18
I had the same problem and after hours of testing I did the following which end up working like a charm:

1. Flash the latest stock rom for Android 7.1.2 (n2g48c)
2. Perform the first boot just to allow USB debugging
3. Flash the latest TWRP for the Nexus 6P (https://dl.twrp.me/angler/twrp-3.5.0_9-0-angler.img.html)
4. Using TWRP, wipe data partition 
5. Use UBports installer as required.
6. Enjoy Ubuntu Touch :)

**Comment by NeoTheThird** [comment] 2021-03-06 17:29
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:29 UTC
