### ISSUE TITLE
Try again not working properly after download error, finally crashes with "Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space"

### ISSUE THREAD

**Issue by alex-galey** [ubports/ubports-installer#1119] opened 2020-02-09 01:11 UTC
**Context**
Got this error while trying to install for the first time, which followed a "Download Error" (I didn't record). Then I clicked on "Try again" which was actually not working (progress bar stuck at previous 100%). I restarted and the installation went smoothly the second time :)

*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: deb
Operating System: Debian  9.11  stretch x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/RRRDNcJM2j/

Thank you for this very encouraging project !

**Comment by NeoTheThird** [comment] 2020-03-09 17:48
that's peculiar. needs investigation, no idea why it happened.

**Comment by vdagguma** [comment] 2020-07-21 15:18
I think my issue is pretty much similar. what I did was, increased the system space by third party tool so as to install custom ROM which is unable to install Gapps(getting error 70). still the issue is not fixed

**Comment by vdagguma** [comment] 2020-07-21 15:19
my handset is hammerhead

**Comment by NeoTheThird** [comment] 2020-09-23 09:53
Duplicate of #1087

**Closed by NeoTheThird** 2020-09-23 09:53 UTC
Labels: needs confirmation
