### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/home/elmx/.cache/ubports/kagura/firmware/halium-unlocked-recovery_kagura.img\""},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'."}

### ISSUE THREAD

**Issue by xelmasx** [ubports/ubports-installer#1379] opened 2020-09-26 13:16 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: kagura
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Debian unstable sid x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/tHBBSvC6nk/

**Comment by NeoTheThird** [comment] 2020-09-26 16:45
duplicate of #1380

**Closed by NeoTheThird** 2020-09-26 16:45 UTC
