### ISSUE TITLE
The burning of Ubuntu touch is normal. The system can't enter into Ubuntu touch. It can only enter into Ubuntu rec, please check boot.img Is it suitable for nexus 6p to be a stable version

### ISSUE THREAD

**Issue by 244099121** [ubports/ubports-installer#1711] opened 2021-01-09 04:04 UTC
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 professional workstations 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5ff92aa0203a7f0007645a28
Log: https://paste.ubuntu.com/p/WtCBGqMhKq/

UBports installer

**Comment by NeoTheThird** [comment] 2021-03-06 17:30
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:30 UTC
