### ISSUE TITLE
[angler] Nexus 6p bootloops when trying to flash using UBPorts-Installer

### ISSUE THREAD

**Issue by kz6fittycent** [ubports/ubports-installer#1590] opened 2020-12-01 22:21 UTC
UBPorts Installer- `0.7.4-beta` (snap)
Env: `Pop!_OS 20.04`
Device: angler
Target OS: Not yet set
Settings: `undefined`

When attempting to flash `stable` (or any other image) to my angler, the installer hangs at "Preparing system-image"

![Screenshot from 2020-12-01 16-17-37](https://user-images.githubusercontent.com/14829816/100803462-d003a700-33f0-11eb-85f6-e743508517bb.png)

Running `snap run ubports-installer` doesn't provide anything useful:

```
snap run ubports-installer
Gtk-Message: 16:11:26.925: Failed to load module "appmenu-gtk-module"
Gtk-Message: 16:11:26.955: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:11:26.956: Failed to load module "canberra-gtk-module"

(ubports-installer:105006): GLib-GIO-CRITICAL **: 16:11:26.966: g_settings_schema_source_lookup: assertion 'source != NULL' failed
info: Welcome to the UBports Installer version 0.7.4-beta!

(ubports-installer:105006): GLib-GIO-CRITICAL **: 16:11:27.061: g_settings_schema_source_lookup: assertion 'source != NULL' failed
info: device detected: angler
info: preparing
info: checking previously downloaded firmware files
```

I let it bootloop for about 30 min and nothing ever happened - as one would expect. 

Is there a bug with the snap? 

My "theory" is that a new recovery is being flashed over my version of TWRP: `twrp-3.2.1-0-angler-4core.img`

My angler experiences BLOD w/o this version of TWRP.

**Comment by NeoTheThird** [comment] 2020-12-01 23:04
Duplicate of #1537

**Closed by NeoTheThird** 2020-12-01 23:04 UTC
