### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: stdout: adb: error: failed to copy '/home/daveacc/snap/ubports-installer/262/.cache/ubports/pool/ubports-8c640da78cb1e63c70d8946a4ec9e1e0383573399dcd4c2d5b2cd771977112ba.tar.xz' to '/cache/recovery/ubports-8c640da78cb1e63c70d8946a4ec9e1e0383573399dcd4c2d5b2cd771977112ba.tar.xz': remote write failed: Read-only file system/home/daveacc/snap/ubports-installer/262/.cache/ubports/pool/ubports-8c640da78cb1e63c70d8946a4ec9e1e0383573399dcd4c2d5b2cd771977112ba.tar.xz: 0 files pushed. 13.6 MB/s (46262768 bytes in 3.236s)

### ISSUE THREAD

**Issue by Dave1152000** [ubports/ubports-installer#1081] opened 2019-12-24 20:02 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/fredldotme/devel","wipe":true,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/XgpGYvDsJ2/

**Comment by davebosley** [comment] 2020-01-01 21:29
I am having the same issue.

**Comment by Dave1152000** [comment] 2020-01-01 22:13
If you have a microsd card in the phone you should take it out and try again. This is how I eventually got it to work. You also need to take the microsd card out whenever you do an update or you just get a black screen.

**Comment by davebosley** [comment] 2020-01-02 23:46
I tried this and still get the same error without the SD Card installed.

Thanks

------ Original Message ------

**Comment by S3sm9** [comment] 2020-01-04 02:33
Ya eh resuelto el problema, aqui la solucion:

#1089 (comment)

Es la respuesta al mismo problema que tienes.

**Comment by davebosley** [comment] 2020-01-04 10:48
Gracias. Intentaré esto cuando el tiempo lo permita.


Thanks,

Dave

**Comment by NeoTheThird** [comment] 2020-01-22 15:43
Duplicate of #1072

**Closed by NeoTheThird** 2020-01-22 15:43 UTC
