### ISSUE TITLE
On Nexus 5, after the bios flash and Ubport download, the connection with the phone was lost. Then I got a message to retry and an endless wait. Then I quitted UBports installer and restarted and it worked fine.

### ISSUE THREAD

**Issue by suipotryot** [ubports/ubports-installer#1699] opened 2021-01-05 11:38 UTC
**UBports Installer `0.8.2-beta` (dmg)**
Environment: `Mac OS X 10.12.6 macOS Sierra darwin 16.7.0 x64 16G2136 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

I don't know how to reproduce... Maybe with a bad usb cable (mine was a non official old one)

**Comment by NeoTheThird** [comment] 2021-01-08 08:33
Duplicate of #1593

**Closed by NeoTheThird** 2021-01-08 08:33 UTC
