### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/platform-tools/mac/fastboot flash boot '/Users/zsolt/Library/Caches/ubports/bacon/firmware/boot-bacon.img'"},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'."}

### ISSUE THREAD

**Issue by zsoltbarat** [ubports/ubports-installer#1390] opened 2020-09-28 20:48 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/edge","wipe":true,"bootstrap":true}
Package: dmg
Operating System: macOS 10.14.618G6020 x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/T4d53f3Rcv/

**Comment by NeoTheThird** [comment] 2020-09-28 21:20
duplicate of #1032

**Closed by NeoTheThird** 2020-09-28 21:20 UTC
