### ISSUE TITLE
Error: adb:format: Error: failed to mount: mount: mounting /dev/block/mmcblk0p5 on /cache failed: Device or resource busy

### ISSUE THREAD

**Issue by Chaosdelphin** [ubports/ubports-installer#1270] opened 2020-06-29 08:10 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: krillin
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/rc","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/rm9rCm7qQT/

**Comment by Chaosdelphin** [comment] 2020-06-29 08:12
2 times clicking on "ignore" works...

**Comment by Chaosdelphin** [comment] 2020-06-29 08:28
the installer GUI is still in phase "formatting cache" but the phone finished the update successfully.

**Comment by NeoTheThird** [comment] 2020-09-23 08:45
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:45 UTC
