### ISSUE TITLE
Adb push error: Error: Command failed: adb -P 5038 push "/home/lapinus/.cache/ubports/pool/ubports-8832267993eb0215232c953d6c5fa7f22ab2fe348b4e68946b098b6bdc19830c.tar.xz" /cache/recovery/, stdout: [...]2c953d6c5fa7f22ab2fe348b4e68946b098b6bdc19830c.tar.xz': remote No space left on device/home/lapinus/.cache/ubports/pool/ubports-8832267993eb0215232c953d6c5fa7f22ab2fe348b4e68946b098b6bdc19830c.tar.xz: 0 files pushed. 7.7 MB/s (266272768 bytes in 32.895s), stderr: 

### ISSUE THREAD

**Issue by lapinus** [ubports/ubports-installer#873] opened 2019-09-06 16:59 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.6-beta 
Device: flo
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux  19.04  disco x64 
NodeJS version: v8.2.1 

Error log: /p/ngmdyznDs2/

**Comment by NeoTheThird** [comment] 2019-09-07 21:40
duplicate of #615

**Closed by NeoTheThird** 2019-09-07 21:40 UTC
