### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: stdout: adb: error: failed to copy '/home/wolf/.cache/ubports/pool/ubports-b657df118efe3e3d244dc012bea05d1be93b6a70c4d776ad53f8ce08919de035.tar.xz' to '/cache/recovery/ubports-b657df118efe3e3d244dc012bea05d1be93b6a70c4d776ad53f8ce08919de035.tar.xz': remote write failed: Read-only file system/home/wolf/.cache/ubports/pool/ubports-b657df118efe3e3d244dc012bea05d1be93b6a70c4d776ad53f8ce08919de035.tar.xz: 0 files pushed, 0 skipped. 17.2 MB/s (273382816 bytes in 15.175s)

### ISSUE THREAD

**Issue by wolf-m-72** [ubports/ubports-installer#1339] opened 2020-09-08 09:23 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/fredldotme/devel","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/ZG7HMJcw8W/

**Comment by NeoTheThird** [comment] 2020-09-23 09:38
Duplicate of #1072

**Closed by NeoTheThird** 2020-09-23 09:38 UTC
