### ISSUE TITLE
Adb push error, the installer does not wait for the device to come online.

### ISSUE THREAD

**Issue by BigET** [ubports/ubports-installer#594] opened 2018-12-28 10:40 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/4GtSsXfFHS/ 

I have the device in recovery mode with the standard `recovery-turbo.img`

I start `ubports-installer`, it will detect my device, issue the reset, but will not wait for the device to be online.

The images are already downloaded and in ~/.cache/ubports.

**Comment by BigET** [comment] 2018-12-28 10:50
the installer should wait for the device with a command like this:

```adb wait-for-any-recovery```

before trying to push the files to the device.

**Comment by NeoTheThird** [comment] 2019-03-19 11:27
Duplicate of #207.

**Closed by NeoTheThird** 2019-03-19 11:27 UTC
Labels: needs confirmation
