### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: stdout: adb: error: failed to copy '/home/daveacc/snap/ubports-installer/275/.cache/ubports/pool/ubports-ff1bb2498a7ef3bc13fb5307629b3709eead3106d889bd258f186335df7888d3.tar.xz' to '/cache/recovery/ubports-ff1bb2498a7ef3bc13fb5307629b3709eead3106d889bd258f186335df7888d3.tar.xz': remote write failed: Read-only file system/home/daveacc/snap/ubports-installer/275/.cache/ubports/pool/ubports-ff1bb2498a7ef3bc13fb5307629b3709eead3106d889bd258f186335df7888d3.tar.xz: 0 files pushed, 0 skipped. 15.1 MB/s (230461976 bytes in 14.531s)

### ISSUE THREAD

**Issue by Dave1152000** [ubports/ubports-installer#1301] opened 2020-07-25 13:43 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":true,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/nzX89yxJJV/

**Comment by NeoTheThird** [comment] 2020-09-23 09:38
Duplicate of #1072

**Closed by NeoTheThird** 2020-09-23 09:38 UTC
