### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: stdout: adb: error: failed to copy '/home/chris/.cache/ubports/pool/ubports-eb4a9073387beab29012bd9c7eb82e21b1b54f4e38c3e08621c64593c40733e9.tar.xz' to '/cache/recovery/ubports-eb4a9073387beab29012bd9c7eb82e21b1b54f4e38c3e08621c64593c40733e9.tar.xz': remote write failed: Read-only file system/home/chris/.cache/ubports/pool/ubports-eb4a9073387beab29012bd9c7eb82e21b1b54f4e38c3e08621c64593c40733e9.tar.xz: 0 files pushed, 0 skipped. 18.1 MB/s (282098040 bytes in 14.877s)

### ISSUE THREAD

**Issue by chris7chris** [ubports/ubports-installer#1328] opened 2020-09-01 20:22 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/fredldotme/devel","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/F68PkxPddH/ 
Now it is in Bootloop.

**Comment by NeoTheThird** [comment] 2020-09-23 09:38
Duplicate of #1072

**Closed by NeoTheThird** 2020-09-23 09:38 UTC
