### ISSUE TITLE
Adb push error: Error: Command failed: /var/folders/8g/jfw9qw9x2t946f7hn_9_q50w0000gn/T/.com.ubports.installer.pUGjo9 -P 5038 push /Users/jeanmarie/Library/Caches/ubports/pool/ubports-420bfa80c833e7736e0197d969b5cd981f18eee1215ad3bfae6d82aab9105f03.tar.xz /cache/recovery/, stdout: [...]d981f18eee1215ad3bfae6d82aab9105f03.tar.xz': remote No space left on device/Users/jeanmarie/Library/Caches/ubports/pool/ubports-420bfa80c833e7736e0197d969b5cd981f18eee1215ad3bfae6d82aab9105f03.tar.xz: 0 files pushed. 8.0 MB/s (202940216 bytes in 24.077s), stderr: 

### ISSUE THREAD

**Issue by jmvdc** [ubports/ubports-installer#842] opened 2019-07-14 09:49 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.3-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: dmg
Operating System: macOS 10.14.518F132 x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/N9YDgPctcF/

**Comment by NeoTheThird** [comment] 2019-08-27 09:28
You selected the device manually. Are you sure you have a **Nexus 5**?

**Comment by NeoTheThird** [comment] 2019-08-28 06:58
Duplicate of #841. Sorry about that.

**Closed by NeoTheThird** 2019-08-28 06:58 UTC
Labels: needs confirmation
