### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by eoslinux** [ubports/ubports-installer#1222] opened 2020-05-17 03:21 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:false,bootstrap:true,format:false}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.836] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/zq2TZXc4Yb/

**Comment by NeoTheThird** [comment] 2020-09-23 09:59
Duplicate of #1052

**Closed by NeoTheThird** 2020-09-23 09:59 UTC
