### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by danielitto91** [ubports/ubports-installer#165] opened 2018-03-25 17:06 UTC
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Debian 9.4
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/bQzcPFDHf4/

**Comment by gsilvapt** [comment] 2018-03-26 21:50
I'm not particularly familiar with these logs but seems there was a failure with the executable. The command pretty much failed executing:

`debug 2018-03-25T17:05:47.597Z Command failed: adb -P 5038 push '/home/daniel/.cache/ubports/pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz' /cache/recovery/
`
The problem is that it says what if fails but does not say why :sweat_smile: Since these cables are super sensible, have you tried again the same procedure to see if that happens again?

**Comment by NeoTheThird** [comment] 2018-03-27 09:04
Yes, this is likely an issue with the cable. If it's wonky in any way, try to find a different one. You could also try to use a different usb socket on your PC

**Comment by NeoTheThird** [comment] 2018-04-30 20:28
Duplicate of #207.

**Closed by NeoTheThird** 2018-04-30 20:28 UTC
