### ISSUE TITLE
Not able to boot up

### ISSUE THREAD

**Issue by idea-log** [ubports/ubports-installer#1844] opened 2021-03-10 20:25 UTC
**UBports Installer `0.8.7-beta` (deb)**
Environment: `Ubuntu 20.04.2 LTS Focal Fossa linux 5.8.0-44-generic x64 NodeJS v12.18.3`
Device: s3ve3g
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60492b4d9442980007574e0b
Log: *N/A*

Try installing it on a Samsung S3 Neo instead of Neo+.

**Error:**
```
Error: systemimage:install: TypeError: Cannot read property 'status' of undefined
```

**Comment by NeoTheThird** [comment] 2021-03-10 20:46
Duplicate of #1840

**Closed by NeoTheThird** 2021-03-10 20:46 UTC
