### ISSUE TITLE
Adb push error: error: device not found

### ISSUE THREAD

**Issue by Albin-John** [ubports/ubports-installer#503] opened 2018-10-15 12:34 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Nexus 5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/ZzMymvCqT4/

**Comment by NeoTheThird** [comment] 2019-03-13 15:19
Looks like the device got disconnected during the installation. You could just try again or use a different usb cable, if this one sits a little loose.

**Comment by NeoTheThird** [comment] 2019-03-19 11:27
Duplicate of #207

**Closed by NeoTheThird** 2019-03-19 11:27 UTC
Labels: question
