### ISSUE TITLE
manual intervention needed to copy loire image files and start fastboot mode

### ISSUE THREAD

**Issue by Danfro** [ubports/ubports-installer#1560] opened 2020-11-20 11:08 UTC
**UBports Installer `0.7.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-54-generic x64 NodeJS v12.16.3`
Device: suzu
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fb7a2249702a600079dd725
Log: *N/A*

install suzu, download loire image -> always failed to copy to snap temp folder
I tried to download to several folders. It never succeeded. Error messages where:
```
Error: manual_download: Error: EISDIR: illegal operation on a directory, copyfile '/home/ubuntu/' -> '/home/ubuntu/snap/ubports-installer/320/.cache/ubports/suzu/firmware/SW_binaries_for_Xperia_AOSP_N_MR1_5.7_r1_v08_loire.img'

Error: manual_download: Error: EACCES: permission denied, copyfile '/media/Daten/Downloads/Lineage/' -> '/home/ubuntu/snap/ubports-installer/320/.cache/ubports/suzu/firmware/SW_binaries_for_Xperia_AOSP_N_MR1_5.7_r1_v08_loire.img'

Error: manual_download: Error: EISDIR: illegal operation on a directory, copyfile '/home/ubuntu/Downloads/' -> '/home/ubuntu/snap/ubports-installer/320/.cache/ubports/suzu/firmware/SW_binaries_for_Xperia_AOSP_N_MR1_5.7_r1_v08_loire.img'
```
"Daten" in my case is a separate disk mounted under, well, under media. Snap permissions for accessing removable drives are set.
I then copied the loire image to the folder specified in the error message and pressed ignore. That took me further through the install process.

When ever I tried the installer (three times so far), my suzu never automatically went into bootloader mode/fastboot. I always had to do that manually for the install process to proceed.

But in the end I got my Xperia up and running. Thanks Jan for providing the installer!

**Comment by Danfro** [comment] 2020-11-28 06:03
Thanks to another user, I could pinpoint the reason why the file copy did give me those errors.

The installers dialog does ask the user to imput the **path** to the image file.
 
![grafik](https://user-images.githubusercontent.com/37637312/100494813-a96e1380-3145-11eb-9c60-b19088ee543e.png)


BUT the installer requires the **path + filename** to proceed.

**_Subissue:_**

Using a path on a removable media did not work. I do have a part of my HDD mounted as a separate disk in _/media_. That did not work. But permissions where granted to use removable media.
This brings up the permissions error:

> Error: manual_download: Error: EACCES: permission denied, copyfile '/media/Daten/Downloads/Lineage/SW_binaries_for_Xperia_AOSP_N_MR1_5.7_r1_v08_loire.img' -> '/home/ubuntu/snap/ubports-installer/326/.cache/ubports/suzu/firmware/SW_binaries_for_Xperia_AOSP_N_MR1_5.7_r1_v08_loire.img'

![grafik](https://user-images.githubusercontent.com/37637312/100495030-a542f580-3147-11eb-8332-283d057b4b2f.png)


**P.S.**
Did you change the 0.8.0 beta installer today/yesterday? When testing now (28.11.2020 morning) for the first time ever I can see instructions on how to enter the bootloader. That was not there yesterday and all the other times before.

**Comment by NeoTheThird** [comment] 2020-11-30 13:47
>  Did you change the 0.8.0 beta installer today/yesterday? When testing now (28.11.2020 morning) for the first time ever I can see instructions on how to enter the bootloader. That was not there yesterday and all the other times before.

i did not. you'll only see instructions as a fallback, though, so you won't see them always.

**Comment by Danfro** [comment] 2020-11-30 19:49
I guess, because I always needed to manually boot into bootloader, it would have helped me having always seen those instructions. :-)

**Comment by NeoTheThird** [comment] 2020-12-01 10:16
Duplicate of #1467, since XDG portal will also handle permissions,

**Closed by NeoTheThird** 2020-12-01 10:16 UTC
Labels: needs confirmation
