### ISSUE TITLE
Fastboot: Unknown error:  [sudo] senha para duwe: downloading 'boot.img'...OKAY [  0.593s]booting...FAILED (remote failure)finished. total time: 0.593s

### ISSUE THREAD

**Issue by robertoduwe** [ubports/ubports-installer#468] opened 2018-09-24 03:47 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/2QwWg7BgJJ/

**Comment by NeoTheThird** [comment] 2019-03-17 16:46
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.

**Closed by NeoTheThird** 2019-03-17 16:46 UTC
Labels: duplicate
