### ISSUE TITLE
UBPorts Recovery after install

### ISSUE THREAD

**Issue by meijad** [ubports/ubports-installer#2394] opened 2022-01-12 23:14 UTC
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 11 Home 10.0.22000 win32 10.0.22000 x64 22000 0.0 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

unsure

**Comment by NeoTheThird** [comment] 2022-03-19 19:13
this is seems to be a a duplicate of #1537. Please try [these steps](https://github.com/ubports/ubports-installer/issues/1537#issuecomment-792346472) to get it to work. sorry for the inconvenience :)

**Closed by NeoTheThird** 2022-03-19 19:13 UTC
