### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by lonlyd** [ubports/ubports-installer#1302] opened 2020-07-26 09:52 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":true}
Package: dir
Operating System: Manjaro Linux 20.0.3 lysia x64 
NodeJS version: v12.4.0 

Error log: https://paste.ubuntu.com//p/TBPw8wfD8N/

**Comment by SakuraOxygen** [comment] 2020-08-20 18:07
I managed to fix this issue on Pop!_OS.

Is your nexus 5 repartitioned? You'll need to revert it back to stock partitioning if so, otherwise the install fails like that.

**Comment by NeoTheThird** [comment] 2020-09-23 09:57
Duplicate of #1087

**Closed by NeoTheThird** 2020-09-23 09:57 UTC
