### ISSUE TITLE
ubports detect my device, ask if I want to install, but impossible to click any button to accept.

### ISSUE THREAD

**Issue by jphuart** [ubports/ubports-installer#791] opened 2019-05-20 16:33 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: krillin
Channel: Not yet set
Package: deb
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/sZtQQD7DP9/

**Comment by jphuart** [comment] 2019-05-20 16:37
The device is a BQ aquaris E4.5 Ubuntu edition with ubuntu 15.04(OTA-15) installed. I would like to upgrade with ubports.

**Comment by amtx** [comment] 2019-05-22 12:17
I had the same problem on same device - succeded with manual install from debian 9. fastboot oem unlock gave me timeout, but the rest worked. 
The reboot to recovery is easier with: fastboot reboot-recovery

**Comment by NeoTheThird** [comment] 2019-08-27 10:44
Duplicate of #806 
sorry about that

**Closed by NeoTheThird** 2019-08-27 10:44 UTC
