### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.360s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.361s

### ISSUE THREAD

**Issue by ivoxavier** [ubports/ubports-installer#380] opened 2018-07-18 09:30 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Fairphone 2
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/7PDMnqB9sn/

**Comment by montage114** [comment] 2018-07-19 13:33
I have the same issue in Windows 10. I got a feeling it has something to do with the version of the recovery installed. I had to revert from TWRP to Fairphones stock recovery to get it to flash the ubuntu-touch recovery, but after that it's stuck. Maybe the installer needs an older recovery version?

**Comment by NeoTheThird** [comment] 2018-07-21 08:48
duplicate of #323

**Closed by NeoTheThird** 2018-07-21 08:48 UTC
