### ISSUE TITLE
Installer claims password is incorrect, even though it's not

### ISSUE THREAD

**Issue by leobap** [ubports/ubports-installer#113] opened 2018-03-02 12:55 UTC
I tried to flash my phone with th Ubport software and receive an error message related to my password.
I tried several times, change my password and the error continues. I think this could be a bug.

Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/xBTWMRymFN/ 
Command failed: echo '' | sudo -S echo correct[sudo] senha para leobap: Sinto muito, tente novamente.[sudo] senha para leobap: sudo: 1 tentativa de senha incorreta

**Comment by NeoTheThird** [comment] 2018-03-02 13:39
So you are 100% certain you typed your password correctly?

**Comment by NeoTheThird** [comment] 2018-03-02 13:42
I'm assuming you used the deb version? As a quick workaround (just to allow you to install) you could try the snap (which doesn't need admin access, instructions in the readme) or run the installer with sudo.

**Comment by leobap** [comment] 2018-03-03 12:29
I'm using the .Deb package. I will try the snap and report the result.

**Comment by leobap** [comment] 2018-03-03 13:17
The snap works fine and ubuntu touch is running in my cel phone. Problem solved.

Thanks for your help.

**Comment by NeoTheThird** [comment] 2018-03-03 17:31
Glad to hear it worked, but the problem is not solved ;) We need to fix this issue, not just work around it...

**Comment by NeoTheThird** [comment] 2018-03-20 19:29
Closing, since we had not had this reported again and I can not reproduce it.

**Closed by NeoTheThird** 2018-03-20 19:29 UTC
Labels: needs confirmation
