### ISSUE TITLE
Error: adb:format: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/cache on /cache failed: Device or resource busy

### ISSUE THREAD

**Issue by doniks** [ubports/ubports-installer#1174] opened 2020-04-12 11:39 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: deb
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/rc","wipe":false,"bootstrap":true,"format":false}
Package: snap
Operating System: Ubuntu Linux 19.04 disco x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/XsGrXcRDyh/ 

- deb with twrp installed and booted 
- start installer 
- deb is recognized 
- choose installation: rc, wipe:no, bootstrap:yes, format system: no 
- boots to fastboot 
- installs recovery 
- boots recovery 
-> error message about mounting cache 
- click open bug report (this one ;) ) 
- click retry 
-> spinning yumi forever .... 
- connect with `adb shell` from terminal: 
```
$ adb shell
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
~ # mount
rootfs on / type rootfs (rw)
tmpfs on /dev type tmpfs (rw,nosuid,relatime,mode=755)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
tmpfs on /tmp type tmpfs (rw,relatime)
tmpfs on /storage type tmpfs (rw,relatime,mode=050,gid=1028)
tmpfs on /mnt/secure type tmpfs (rw,relatime,mode=700)
tmpfs on /mnt/fuse type tmpfs (rw,relatime,mode=775,gid=1000)
/dev/block/platform/msm_sdcc.1/by-name/system on /system type ext4 (rw,relatime,data=ordered)
/dev/block/platform/msm_sdcc.1/by-name/cache on /cache type ext4 (rw,relatime,data=ordered)
/dev/block/platform/msm_sdcc.1/by-name/userdata on /data type ext4 (rw,relatime,data=ordered)
~ # cd /cache/
/cache # touch stuff
/cache # ls -l
__bionic_open_tzdata: couldn't find any tzdata when looking for localtime!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
drwx------    2 root     root          4096 Jan  1  1970 lost+found
drwxrwxrwx    2 root     root          4096 Jan  4 18:49 recovery
-rw-rw-rw-    1 root     root             0 Jan  4 18:53 stuff
/cache # rm stuff
/cache # ls -l
__bionic_open_tzdata: couldn't find any tzdata when looking for localtime!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
drwx------    2 root     root          4096 Jan  1  1970 lost+found
drwxrwxrwx    2 root     root          4096 Jan  4 18:49 recovery
```
- so, cache seems to be mounted ok ... 
- close and restart installer 
- try again but without bootstrap 
-> reboots recovery 
-> same error again 
- click ignore
-> now it seems to install ok

**Comment by NeoTheThird** [comment] 2020-09-23 08:45
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:45 UTC
