### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for ed: target didn't report max-download-sizesending 'recovery' (12592 KB)...OKAY [  0.406s]writing 'recovery'...FAILED (remote: image is not a boot image)finished. total time: 0.410s

### ISSUE THREAD

**Issue by liquidlemur** [ubports/ubports-installer#681] opened 2019-03-02 02:55 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 7 2013 (LTE)
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/wHcHGzx2Yc/

**Comment by NeoTheThird** [comment] 2019-03-10 16:31
Duplicate of #639.

**Closed by NeoTheThird** 2019-03-10 16:31 UTC
