### ISSUE TITLE
Adb push error: Error: Command failed: adb -P 5038 push C:\Users\tigra\AppData\Roaming\ubports\pool\device-add1def5b822ab3d83c427d6bfabb0330aef9f8f12beda00cd7ba0cd227359e4.tar.xz /cache/recovery/, stdout: adb: error: failed to get feature set: more than one device/emulator, stderr: 

### ISSUE THREAD

**Issue by donkikos** [ubports/ubports-installer#857] opened 2019-08-25 06:05 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.3-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.295] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/8RGXB6mWr8/ 

**UPDATE** 
I used manual install. When I was pushing the files to the devices sometimes it was showing the same error. I had to redo the command one or more times to successfully push.

**Comment by NeoTheThird** [comment] 2019-08-27 08:35
Sorry about that. Duplicate of #653.

**Comment by NeoTheThird** [comment] 2019-08-29 12:19
Well, adb for sure detects more than one. There must be another adb client connected. What's the output of `adb devices`?

**Comment by donkikos** [comment] 2019-09-02 00:50
Hi @NeoTheThird , as I already installed it, I can't check it now. However I think you are right that for some reason adb was seeing more than one devices. So I needed to try the same copy command few times. Maybe the code could do the same? Let's say try each command up to 5 times and then fail.

**Comment by NeoTheThird** [comment] 2019-09-02 20:39
The installer is looking for devices until it finds one, but if more than one is connected, that is a problem, because adb won't know who we want to recieve the files. Anyways, good to hear that you succeeded with manual install. We'll track the rest over at #653.

**Closed by NeoTheThird** 2019-09-02 20:39 UTC
Labels: question

**Comment by donkikos** [comment] 2019-09-02 20:47
@NeoTheThird, I don't have additional devices connected. For some reason adb was detecting more than one device during some copy commands and then after few seconds there was only one. I was suggesting to have a check in the code that if there are more then one devices, check few time until there is only one. Might help others.

**Comment by NeoTheThird** [comment] 2019-09-02 20:57
Yep, that's what we need to do in #653. If more than one device is detected, the user is prompted to double-check and can then resume the installation (without having to start over) :)
