### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by nivu619** [ubports/ubports-installer#1125] opened 2020-02-23 09:42 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18363.657] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/hKsbspX6Bh/

**Comment by nivu619** [comment] 2020-02-23 09:42
there is lots of space

**Comment by chhager** [comment] 2020-02-24 00:35
possibel solution: repartition to stock partition configuration
explanation: switched from ubtouch to Lineage 17.1, for that I had to repartition; didn't like Android 10, so wanted to go back to ubtouch;

here's a link to a repartition-to-stock-script, that's part of a twrp image ( twrp-3.3.1-HH-hammerhead.img ) :
https://forum.xda-developers.com/showpost.php?p=79928889&postcount=190

just follow the instructions for reverting the partitioning and reflash ubuntu touch.

**Comment by NeoTheThird** [comment] 2020-09-23 09:56
Duplicate of #1089

**Closed by NeoTheThird** 2020-09-23 09:56 UTC
Labels: needs confirmation
