### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >downloading 'boot.img'...FAILED (command write failed (Protocol error))finished. total time: 0.004s

### ISSUE THREAD

**Issue by diabolo81** [ubports/ubports-installer#442] opened 2018-09-02 11:23 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu MX4
Package: unknown
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/gSXj5r6hKq/

**Comment by NeoTheThird** [comment] 2019-03-13 14:57
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.

**Closed by NeoTheThird** 2019-03-13 14:57 UTC
