### ISSUE TITLE
MacOS-device not recognised in bootloader mode

### ISSUE THREAD

**Issue by NGStaph** [ubports/ubports-installer#281] opened 2018-05-28 08:43 UTC
ubports installer cannot connect with phone in bootloader mode.

**Comment by NGStaph** [comment] 2018-05-28 08:44
Nexus 5

**Comment by harshkalra** [comment] 2018-05-30 18:30
same issue. cannot connect to nexus 5 in bootloader mode

**Comment by NGStaph** [comment] 2018-05-30 22:06
Build via cli, that works.

**Comment by NeoTheThird** [comment] 2018-07-04 22:41
Duplicate of #182

**Closed by NeoTheThird** 2018-07-04 22:41 UTC
