### ISSUE TITLE
install completes. Nexus6p. But only boots up to "ubports recovery"

### ISSUE THREAD

**Issue by Lymp2** [ubports/ubports-installer#1790] opened 2021-02-08 13:47 UTC
**UBports Installer `0.8.4-beta` (AppImage)**
Environment: `Ubuntu 20.10 Groovy Gorilla linux 5.8.0-41-generic x64 NodeJS v12.18.3`
Device: angler n2g47w
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/602140caafa951000786e5d2
Log: *N/A*

I don't know. I completely wiped my phone. used fastboot.  I successfully installed android 7.1.2 beforehand which booted up. I've tried

**Comment by NeoTheThird** [comment] 2021-03-06 17:31
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:31 UTC
