### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/tmp/.mount_ubportYH0QfQ/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: No such process"}

### ISSUE THREAD

**Issue by vasyugan** [ubports/ubports-installer#1186] opened 2020-04-25 10:33 UTC
This is about a OnePlus 3T. I have wiped data, system, cache and dalvik cache. 
Dispite that, installation fails reproduciblly

*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":true,"bootstrap":true}
Package: AppImage
Operating System: Debian 10 buster x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/DFW9yFC4jD/

**Comment by vasyugan** [comment] 2020-04-25 10:58
Same result with the native deb packages and after wiping internal storage

**Comment by ThatGeekZen** [comment] 2020-04-30 18:46
Happening for me on the deb version with KDE Neon 18.04 and on Solus with the snap version. Also using the OnePlus 3T.

**Comment by NeoTheThird** [comment] 2020-09-23 08:45
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:45 UTC
