### ISSUE TITLE
installing ubuntu toch for Android 6.0 One plus one

### ISSUE THREAD

**Issue by Andrey16android** [ubports/ubports-installer#829] opened 2019-06-20 14:08 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: Not detected
Channel: Not yet set
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/B6TxtwnNF8/

**Comment by Andrey16android** [comment] 2019-06-20 14:10
Ждемс установки Ubuntu Toch на смартфон One plus one

**Comment by NeoTheThird** [comment] 2019-08-27 09:38
Sorry about that. Duplicate of #700.

**Closed by NeoTheThird** 2019-08-27 09:38 UTC
