### ISSUE TITLE
Fastboot: Unknown error:  target didn't report max-download-sizesending 'recovery' (12592 KB)...OKAY [  0.400s]writing 'recovery'...FAILED (remote: image is not a boot image)finished. total time: 0.404s

### ISSUE THREAD

**Issue by DE2885V** [ubports/ubports-installer#437] opened 2018-09-01 10:49 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 7 2013 (LTE)
Package: unknown
Operating System: Ubuntu Linux undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/DGxdRBJhbg/

**Comment by NeoTheThird** [comment] 2019-03-10 16:33
Duplicate of #639.

**Closed by NeoTheThird** 2019-03-10 16:33 UTC
