### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.766s]booting...FAILED (remote: unknown command)finished. total time: 0.780s

### ISSUE THREAD

**Issue by zikaras** [ubports/ubports-installer#327] opened 2018-06-25 19:59 UTC
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/h5SV4rMy4Q/

**Comment by NeoTheThird** [comment] 2018-07-01 10:49
Duplicate of #328. Please don't report the same bug multiple times!

**Closed by NeoTheThird** 2018-07-01 10:49 UTC
