### ISSUE TITLE
smartphone freezzes at startup (showing google caption)

### ISSUE THREAD

**Issue by Qverty** [ubports/ubports-installer#1718] opened 2021-01-11 22:34 UTC
**UBports Installer `0.8.4-beta` (dmg)**
Environment: `Mac OS X 10.15.6 macOS Catalina darwin 19.6.0 x64 19G73 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5ffcd257203a7f0007646312
Log: *N/A*

nexus 5 with android 6

**Comment by NeoTheThird** [comment] 2021-03-06 17:44
sorry about that, duplicate of #1052

**Closed by NeoTheThird** 2021-03-06 17:44 UTC
