### ISSUE TITLE
Stopped at bootloader

### ISSUE THREAD

**Issue by vasudevnn** [ubports/ubports-installer#1793] opened 2021-02-11 07:06 UTC
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6024d596afa951000786edc5
Log: https://paste.ubuntu.com/p/FBZ7rvy9m3/

no

**Comment by NeoTheThird** [comment] 2021-03-06 17:32
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:32 UTC
