### ISSUE TITLE
errror

### ISSUE THREAD

**Issue by shawn7226791** [ubports/ubports-installer#2308] opened 2021-11-25 11:27 UTC
**UBports Installer `0.8.9-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

stay on unport recovery

**Comment by NeoTheThird** [comment] 2022-03-19 19:14
this is seems to be a a duplicate of #1537. Please try [these steps](https://github.com/ubports/ubports-installer/issues/1537#issuecomment-792346472) to get it to work. sorry for the inconvenience :)

**Closed by NeoTheThird** 2022-03-19 19:14 UTC
