### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by freddyvegamarcelino** [ubports/ubports-installer#1135] opened 2020-03-07 16:02 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/dcNpxfvQX6/

**Comment by NeoTheThird** [comment] 2020-03-09 17:29
Duplicate of #1132

**Closed by NeoTheThird** 2020-03-09 17:29 UTC
