### ISSUE TITLE
UBports is stuck when asking if i'm ready - Meizu pro 5

### ISSUE THREAD

**Issue by leolsdb** [ubports/ubports-installer#757] opened 2019-04-19 20:46 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: turbo
Package: snap
Operating System: Ubuntu Linux  18.10  cosmic x64 
NodeJS version: v8.2.1 

UBports installer detect my devices, then asking if i'm ready. But seems to be stuck there.

![uspport](https://user-images.githubusercontent.com/49796384/56443286-445d0580-62f4-11e9-83ee-cf068c77fba5.jpg)

**Comment by NeoTheThird** [comment] 2019-04-24 14:02
What OS is the phone running?

**Comment by leolsdb** [comment] 2019-04-24 14:07
Ubuntu Touch15.04 OTA 15

**Comment by matty-codes** [comment] 2019-05-06 16:19
I'm getting the same issue. Running the same OS (15.04).

**Comment by NeoTheThird** [comment] 2019-08-27 12:45
Duplicate of #806

**Closed by NeoTheThird** 2019-08-27 12:45 UTC
Labels: needs confirmation
