### ISSUE TITLE
Fastboot: Unknown error:  Password:Sending 'boot.img' (11442 KB)                      OKAY [  0.361s]Booting                                            FAILED (remote: 'bootimage: incomplete or not signed')fastboot: error: Command failed

### ISSUE THREAD

**Issue by beatrupp** [ubports/ubports-installer#712] opened 2019-03-16 07:03 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.0-beta 
Device: FP2
Channel: ubports-touch/16.04/stable
Package: dmg
Operating System: macOS 10.14.318D109 x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/H4nMkzhpvd/

**Comment by NeoTheThird** [comment] 2019-03-16 07:42
Thanks for testing! Duplicate of #184.

**Closed by NeoTheThird** 2019-03-16 07:42 UTC
