### ISSUE TITLE
not able to install: stuck in "Please reboot to bootloader"

### ISSUE THREAD

**Issue by voducngh** [ubports/ubports-installer#446] opened 2018-09-05 11:20 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: exe
Operating Syst

**Comment by NeoTheThird** [comment] 2019-03-10 10:05
Duplicate of #116.

**Closed by NeoTheThird** 2019-03-10 10:05 UTC
