### ISSUE TITLE
High CPU Usage while downloading

### ISSUE THREAD

**Issue by paulusasol** [ubports/ubports-installer#807] opened 2019-05-30 18:21 UTC
**Expected behaviour:**
Downloading files puts high load on networking, but little CPU usage

**Observed behaviour:**
Approximately 50% CPU usage (combined from all Installer Processes, ~10% of the grandparent process, ~40% on the grandchild process), only approximately 1/10th of available network bandwidth gets used while downloading

Device is Ubuntu M10 FHD
Channel is 16.04/stable
The ubports-installer was installed using snap
Excerpt from `snap list`: `ubports-installer        0.2.2-beta  189   stable    mariogrip       -`
Operating system: `Debian testing`, `uname -v`: `#1 SMP Debian 5.0.2-1~exp1 (2019-03-18)`

**Comment by NeoTheThird** [comment] 2019-08-27 09:36
Sorry about that. Duplicate of #726.

**Closed by NeoTheThird** 2019-08-27 09:36 UTC
