### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by Hernest-Glitch** [ubports/ubports-installer#1290] opened 2020-07-09 10:24 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:true,bootstrap:true,format:true}
Package: exe
Operating System: Microsoft Windows [version 10.0.19041.329] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/XPbmVDtgXC/

**Comment by NeoTheThird** [comment] 2020-09-23 09:59
Duplicate of #1052

**Closed by NeoTheThird** 2020-09-23 09:59 UTC
