### ISSUE TITLE
/cache/recovery missing required key

### ISSUE THREAD

**Issue by benwhite1987** [ubports/ubports-installer#2481] opened 2022-03-02 19:56 UTC
**UBports Installer `0.8.9-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.15.15-76051515-generic x64 NodeJS v12.18.3`
Device: enchilada
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

I followed bielsnohr's 19 Feb 2022 forum post on how to install on OP6T, failed right at the end of the installation, device won't reboot into recovery at the moment.

**Comment by NeoTheThird** [comment] 2022-03-18 10:07
duplicate of #2155

**Closed by NeoTheThird** 2022-03-18 10:07 UTC
