### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: stdout: adb: error: failed to copy '/home/hoeschen/.cache/ubports/pool/ubports-afa028768237baedd75b02758f191a7aa15fbbe88fc35ad9c2dc578272b4a747.tar.xz' to '/cache/recovery/ubports-afa028768237baedd75b02758f191a7aa15fbbe88fc35ad9c2dc578272b4a747.tar.xz': remote write failed: Read-only file system/home/hoeschen/.cache/ubports/pool/ubports-afa028768237baedd75b02758f191a7aa15fbbe88fc35ad9c2dc578272b4a747.tar.xz: 0 files pushed, 0 skipped. 17.4 MB/s (298742152 bytes in 16.347s)

### ISSUE THREAD

**Issue by RubbelDeCatc** [ubports/ubports-installer#1169] opened 2020-04-10 13:48 UTC
After flashing the bootloader the ubports-installer restart the device into recovery ans start to transfer the image. The the device reboots after 20 xxx seconds so the transfer can not be finished.

*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/fredldotme/devel","wipe":true,"bootstrap":true}
Package: AppImage
Operating System: Debian testing bullseye x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/nVw5f3Pp7F/ 

Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: stdout: adb: error: failed to copy '/home/hoeschen/.cache/ubports/pool/ubports-afa028768237baedd75b02758f191a7aa15fbbe88fc35ad9c2dc578272b4a747.tar.xz' to '/cache/recovery/ubports-afa028768237baedd75b02758f191a7aa15fbbe88fc35ad9c2dc578272b4a747.tar.xz': remote write failed: Read-only file system/home/hoeschen/.cache/ubports/pool/ubports-afa028768237baedd75b02758f191a7aa15fbbe88fc35ad9c2dc578272b4a747.tar.xz: 0 files pushed, 0 skipped. 17.4 MB/s (298742152 bytes in 16.347s)

**Comment by NeoTheThird** [comment] 2020-09-23 09:37
Duplicate of #1072

**Closed by NeoTheThird** 2020-09-23 09:37 UTC
