### ISSUE TITLE
oem unlock: FAILED (remote: 'Incorrect format for unlock data. Should be on the form \"0x')

### ISSUE THREAD

**Issue by kamilss4937** [ubports/ubports-installer#1071] opened 2019-12-14 15:56 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/fredldotme/devel","wipe":false,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/fg3cdjMqvp/

**Comment by NeoTheThird** [comment] 2019-12-19 09:15
Hmm, i haven't seen this before. Response for oem-unlock is `FAILED (remote: 'Incorrect format for unlock data. Should be on the form \"0x')`. Thoughts @fredldotme?

**Comment by NeoTheThird** [comment] 2020-09-24 08:13
Looks like you have to get [some sort of code](https://forum.xda-developers.com/showthread.php?t=2558539)!? What fresh hell is this???

**Comment by NeoTheThird** [comment] 2020-09-24 18:25
Duplicate of #1305

**Closed by NeoTheThird** 2020-09-24 18:25 UTC
Labels: bug
