### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >downloading 'boot.img'...OKAY [  1.103s]booting...FAILED (remote failure)finished. total time: 1.105s

### ISSUE THREAD

**Issue by petrus-hanks** [ubports/ubports-installer#542] opened 2018-11-19 05:52 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/djJV27tGDx/

**Comment by NeoTheThird** [comment] 2019-03-13 15:54
What OS is the device running now? possible duplicate of #221.

**Comment by NeoTheThird** [comment] 2019-03-17 16:48
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.

**Closed by NeoTheThird** 2019-03-17 16:48 UTC
Labels: question
