### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.360s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.361s

### ISSUE THREAD

**Issue by bastian-bou** [ubports/ubports-installer#537] opened 2018-11-12 13:55 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux 18.10 cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/wftXs3kYpx/

**Comment by MaritimeMartin** [comment] 2018-11-15 21:16
Same issue here with Ubuntu 16.04

**Comment by tbdal** [comment] 2018-11-22 18:04
same here with ubuntu 18.10

**Comment by Ingo-FP-Angel** [comment] 2018-11-23 15:30
Can you try this version of the installer?
https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fubports-installer/detail/PR-517/6/artifacts

**Comment by tbdal** [comment] 2018-11-25 13:38
i used the .deb version so far but i'll try out the AppImage, too.
https://paste.ubuntu.com/p/42Cw5zwy9t/

**Comment by tbdal** [comment] 2018-11-25 15:46
one step further, next issue: adb push failed
https://paste.ubuntu.com/p/ftf3fdpjhD/

is there any reason why twrp is not used?

**Comment by Ingo-FP-Angel** [comment] 2018-11-25 16:18
Same question just got asked in the forum:https://forums.ubports.com/topic/2037/is-it-possible-to-flash-from-twrp-with-zip-file

**Comment by tbdal** [comment] 2018-11-25 17:38
i'm stuck here now, fp2 is in ubports recovery. any ideas?
![image](https://user-images.githubusercontent.com/6881189/48982318-30b0c880-f0e1-11e8-94d7-67d4d86ea15a.png)

**Comment by Ingo-FP-Angel** [comment] 2018-11-25 17:50
I don't know if it is a Fairphone thing (I don't have other devices) but it seems to be some kind of randomness involved.

If this version also doesn't work, you can try the older ones: 0.1.12 and 0.1.9. These are the versions where several people succeeded (while others didn't) in the past.

**Comment by Ingo-FP-Angel** [comment] 2018-11-25 17:52
> one step further, next issue: adb push failed
> https://paste.ubuntu.com/p/ftf3fdpjhD/

Too bad that the log doesn't contain what went wrong with the "adb push" command.

Here is a new version that hopefully fixes the log entries in that situation: https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fubports-installer/detail/PR-517/8/artifacts

**Comment by tbdal** [comment] 2018-11-26 11:09
cool. i tried again with your new version:
here's the error https://paste.ubuntu.com/p/npgN9yv7d8/

another thing, is this intended?
  after connecting via usb & starting: fp2 boots into fastboot, but installer requires recovery (screenshot)
  --> disconnect usb, unplug battery, manual entry into recovery via buttons, reconnect usb

**Comment by Ingo-FP-Angel** [comment] 2018-11-26 13:19
Dammit, "stdout: overflow" means the output is too long 😟 

The thing is, I neither wrote the installer nor the fix for the "remote: bootimage: incomplete or not signed" issue. The author of the fix didn't create a pull request, just a patch, so that nobody could test it unless they ran it from source (which it seems nobody did).

So either this fix has unintended side effects or this is some general problem with the windows version. I don't know.

**Comment by tbdal** [comment] 2018-11-26 14:55
how can we push this in the right "direction"? im unfortunately not too aware of the code :(

the comments i made last were regarding the AppImage-Version that you posted

**Comment by Ingo-FP-Angel** [comment] 2018-11-28 19:14
I'm somewhat out of ideas at the moment :frowning_face:

**Comment by jonnius** [comment] 2018-12-13 17:43
duplicate of #184

**Closed** 2019-03-10 08:58 UTC
