### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/262/app/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: Invalid argument"}

### ISSUE THREAD

**Issue by FelixBaumgartner91** [ubports/ubports-installer#1151] opened 2020-03-29 15:40 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":false,"bootstrap":true}
Package: snap
Operating System: Manjaro Linux 19.0.2 kyria x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/CrFrsTD9pk/

**Comment by NeoTheThird** [comment] 2020-09-23 08:45
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:45 UTC
