### ISSUE TITLE
add option to cleanup

### ISSUE THREAD

**Issue by wdehoog** [ubports/ubports-installer#942] opened 2019-10-23 20:01 UTC
Hi,

A feature request. Please add an option to clean up after installing. Currently when done there are two directories left in C:\Users\<user>\AppData\Roaming\ one (ubports-installer) of 5MB and one (ubports) of 450MB.

(Testing 0.4.0 on Windows 10 Pro)

**Comment by NeoTheThird** [comment] 2019-10-23 22:32
Duplicate of #865

**Closed by NeoTheThird** 2019-10-23 22:32 UTC
