### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.361s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.364s

### ISSUE THREAD

**Issue by nar001** [ubports/ubports-installer#677] opened 2019-02-27 23:40 UTC
*Automatically generated

**Comment by NeoTheThird** [comment] 2019-03-10 08:50
Duplicate of #184. Try again with UBports Installer 0.1.12-beta.

**Closed by NeoTheThird** 2019-03-10 08:50 UTC
