### ISSUE TITLE
After installation boots to ubports recovery on Nexus6P

### ISSUE THREAD

**Issue by adamdunstan** [ubports/ubports-installer#1731] opened 2021-01-16 01:01 UTC
**UBports Installer `0.8.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-38-generic x64 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60023ad0203a7f0007646f7f
Log: *N/A*

Followed instructions exactly, went back to android 7.12 and clear all partitions with TWRP

Reviewed content on lists, as installation appeared to be sensitive to order of installation and actions, did it quite a few times including attempting to use the halium installer script.  The script appeared to run correctly and transfer the images, however the result was the same.  Phone boots to Ubports recovery

**Comment by NeoTheThird** [comment] 2021-03-06 17:30
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:30 UTC
