### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: stdout: adb: error: failed to copy 'C:\Users\francesco.maisano\AppData\Roaming\ubports\pool\ubports-aa9dad30db962019f4dfcc58162fbb86660bc3680767af7fc20506bbefc6675f.tar.xz' to '/cache/recovery/ubports-aa9dad30db962019f4dfcc58162fbb86660bc3680767af7fc20506bbefc6675f.tar.xz': remote Read-only file systemC:\Users\francesco.maisano\AppData\Roaming\ubports\pool\ubports-aa9dad30db962019f4dfcc58162fbb86660bc3680767af7fc20506bbefc6675f.tar.xz: 0 files pushed, 0 skipped. 8.9 MB/s (65528 bytes in 0.007s)

### ISSUE THREAD

**Issue by maframan** [ubports/ubports-installer#1246] opened 2020-06-06 00:08 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: deb
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:true,bootstrap:true,format:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18363.836] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/bv9TNjhXXh/

**Comment by NeoTheThird** [comment] 2020-09-23 09:37
Duplicate of #1072

**Closed by NeoTheThird** 2020-09-23 09:37 UTC
