### ISSUE TITLE
Uncaught TypeError: devices.sort is not a function (MainRenderer:423)

### ISSUE THREAD

**Issue by Darrellh013** [ubports/ubports-installer#128] opened 2018-03-12 14:25 UTC
Automatically generated error report %0AVersion: 0.1.11-beta %0AHost OS: darwin %0AHost Dist: undefined undefined%0AHost Arch: x64 %0ANode: v8.2.1 %0A%0AError log: http://paste.ubuntu.com/p/9FdtnMFmTt/ %0A

**Comment by NeoTheThird** [comment] 2018-03-14 10:06
Thanks for reporting, duplicate of #87

**Closed by NeoTheThird** 2018-03-14 10:06 UTC
