### ISSUE TITLE
Adb push error: cannot stat ''C:\Users\scardracs\AppData\Roaming\ubports/pool/ubports-f3c4def4862503538951af64e32443ab5d7d2cb3bd2c94bd6c8e908b6c6bb71f.tar.xz'': No such file or directory

### ISSUE THREAD

**Issue by ScardracS** [ubports/ubports-installer#270] opened 2018-05-20 16:13 UTC
Automat

**Comment by ScardracS** [comment] 2018-05-21 19:27
IDK why... I've tried with 0.1.13-beta (the last one) and my N4

**Comment by NeoTheThird** [comment] 2018-05-25 11:03
Duplicate of #110. Please try again with [version 0.1.9-beta](https://github.com/ubports/ubports-installer/releases/download/0.1.9-beta/ubports-installer.0.1.9-beta.exe)

**Closed by NeoTheThird** 2018-05-25 11:03 UTC
