### ISSUE TITLE
please describe the problem in a few words

### ISSUE THREAD

**Issue by ressanoid** [ubports/ubports-installer#1457] opened 2020-10-24 09:27 UTC
**UBports Installer `0.5.5-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19041 win32 10.0.19041 x64 19041 0.0` with Node.js `v12.16.3`
Device: kagura
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f93f36c9702a600079d91f4
Log: https://paste.ubuntu.com//p/sFTm87TGQV/

connect Xperia XZ and it gets decetected with a message then flashing the Ubuntu touch OS gets stuck

**Comment by NeoTheThird** [comment] 2020-10-24 10:36
Duplicate of #1367

**Closed by NeoTheThird** 2020-10-24 10:36 UTC
