### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.388s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.389s

### ISSUE THREAD

**Issue by epierre3** [ubports/ubports-installer#305] opened 2018-06-21 12:44 UTC
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Package: Snap 
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/9yWj94Sy2q/

**Comment by jonnius** [comment] 2018-06-24 15:33
duplicate of #184

**Closed** 2018-07-01 10:47 UTC
Labels: duplicate
