### ISSUE TITLE
Failed Push: out of space

### ISSUE THREAD

**Issue by byronbgs** [ubports/ubports-installer#1051] opened 2019-12-04 03:09 UTC
Error: System Image ....  Failed to push file: out of space. 
![Push failed out of space2](https://user-images.githubusercontent.com/58497545/70109303-1e7d3a80-1611-11ea-839b-a357c27848bc.jpg)
![Push failed out of space](https://user-images.githubusercontent.com/58497545/70109304-1e7d3a80-1611-11ea-97ba-571da0a151d3.jpg)

I will try to delete the user data and try again

**Comment by NeoTheThird** [comment] 2019-12-04 09:36
Duplicate of #1052

**Closed by NeoTheThird** 2019-12-04 09:36 UTC
