### ISSUE TITLE
stuck on google screen

### ISSUE THREAD

**Issue by Bitevic** [ubports/ubports-installer#1752] opened 2021-01-24 20:28 UTC
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/600dd853203a7f0007648b9e
Log: *N/A*

After installing update Nexus 6p stuck on google screen

**Comment by joxdiaz** [comment] 2021-01-26 04:17
I had the same problem and after hours of testing I did the following which end up working like a charm:

1. Flash the latest stock rom for Android 7.1.2 (n2g48c)
2. Perform the first boot just to allow USB debugging
3. Flash the latest TWRP for the Nexus 6P (https://dl.twrp.me/angler/twrp-3.5.0_9-0-angler.img.html)
4. Using TWRP, wipe data partition 
5. Use UBports installer.
6. Enjoy Ubuntu Touch :)

**Comment by NeoTheThird** [comment] 2021-03-06 17:31
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:31 UTC
