### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.762s]booting...FAILED (remote: unknown command)finished. total time: 0.776s

### ISSUE THREAD

**Issue by zikaras** [ubports/ubports-installer#356] opened 2018-07-06 15:33 UTC
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/tpWYSgWJ9D/

**Comment by NeoTheThird** [comment] 2018-07-08 09:59
What OS is your MX4 running right now?

**Comment by fabrei** [comment] 2018-09-03 08:39
i had the same log messages. maybe [this](https://github.com/ubports/ubports-installer/issues/416#issuecomment-417250720) helps :)

**Comment by NeoTheThird** [comment] 2019-03-13 14:58
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.

**Closed by NeoTheThird** 2019-03-13 14:58 UTC
Labels: question
