### ISSUE TITLE
It didn't install on Huawei Nexus 6p.

### ISSUE THREAD

**Issue by aibaron** [ubports/ubports-installer#1791] opened 2021-02-08 14:00 UTC
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/602143feafa951000786e5d6
Log: *N/A*

I went through the install process, unlocked bootloader, device said "Ubuntu Update" or similar, now it doesn't boot.

**Comment by NeoTheThird** [comment] 2021-03-06 17:32
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:32 UTC
