### ISSUE TITLE
Adb push error: Error: Command failed: adb -P 5038 push C:\Users\phill\AppData\Roaming\ubports\pool\ubports-420bfa80c833e7736e0197d969b5cd981f18eee1215ad3bfae6d82aab9105f03.tar.xz /cache/recovery/failed to copy 'C:\Users\phill\AppData\Roaming\ubports\pool\ubports-420bfa80c833e7736e0197d969b5cd981f18eee1215ad3bfae6d82aab9105f03.tar.xz' to '/cache/recovery//ubports-420bfa80c833e7736e0197d969b5cd981f18eee1215ad3bfae6d82aab9105f03.tar.xz': No space left on device, stdout: , stderr: [...]y 'C:\Users\phill\AppData\Roaming\ubports\pool\ubports-420bfa80c833e7736e0197d969b5cd981f18eee1215ad3bfae6d82aab9105f03.tar.xz' to '/cache/recovery//ubports-420bfa80c833e7736e0197d969b5cd981f18eee1215ad3bfae6d82aab9105f03.tar.xz': No space left on device

### ISSUE THREAD

**Issue by PJ112208** [ubports/ubports-installer#848] opened 2019-07-31 17:39 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.17763.615] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/tbT38c7Qh6/

**Comment by NeoTheThird** [comment] 2019-08-27 08:49
You selected the device manually. Are you sure you have a **Nexus 5**?

**Comment by NeoTheThird** [comment] 2019-08-28 06:58
Duplicate of #841. Sorry about that.

**Closed by NeoTheThird** 2019-08-28 06:58 UTC
Labels: needs confirmation
