### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by JonathanReeve** [ubports/ubports-installer#2520] opened 2022-03-21 18:38 UTC
**UBports Installer `0.9.2-beta` (exe)**
Environment: `Microsoft Windows 11 Home 10.0.22000 Windows 10.0.22000 x64 22000 0.0 NodeJS v16.13.0`
Device: [jingpad_a1]
(https://devices.ubuntu-touch.io/device/jingpad_a1)
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6238c61a5f2433000898a0c8

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment] 2022-03-21 19:28
Duplicate of #1840. Fixed in the next release.

**Closed by NeoTheThird** 2022-03-21 19:28 UTC
