### ISSUE TITLE
UBports Installer 0.6.0 Fail, Nexus 6P

### ISSUE THREAD

**Issue by 7evin** [ubports/ubports-installer#1505] opened 2020-11-07 03:57 UTC
**UBports Installer `0.6.0-beta` (exe)**
Environment: `Microsoft Windows 10 Home N 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.16.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa61aa99702a600079db343
Log: *N/A*

flashed TWRP, wiped partitions, started installer. currently have UBPorts Recovery installed just fine but in the next steps, the installer throws an error:
```
Error: systemimage: Error: Error:{"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\Users\\7evin\\AppData\\Local\\Temp\\1jZdYrkqnbzAZoGRTA5fqH0JXK9\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe\" -P 5037 shell 'mount -a || true'"},"stdout":"","stderr":"/sbin/sh: no closing quote\r\n'true'' is not recognized as an internal or external command,\r\noperable program or batch file."}
```
I'd truly love to hear that i'm doing it wrong :)

**Comment by NeoTheThird** [comment] 2020-11-08 10:46
Sorry about that. Duplicate of #1474. Should be resolved in the next release.

**Closed by NeoTheThird** 2020-11-08 10:46 UTC
