### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.362s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.363s

### ISSUE THREAD

**Issue by ubuntushop** [ubports/ubports-installer#572] opened 2018-12-06 12:28 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Fairphone 2
Package: snap
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/GHK7SymhYX/

**Comment by jonnius** [comment] 2018-12-13 17:44
duplicate of #184

**Closed** 2019-03-10 08:56 UTC
