### ISSUE TITLE
Fastboot: Unknown error:  [sudo] Passwort für julius: downloading 'boot.img'...OKAY [  0.361s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.364s

### ISSUE THREAD

**Issue by raverrebel** [ubports/ubports-installer#536] opened 2018-11-11 10:53 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/kNvg3J2BK7/

**Comment by jonnius** [comment] 2018-12-13 17:43
duplicate of #184

**Closed** 2019-03-10 08:58 UTC
Labels: duplicate
