### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.704s]booting...FAILED (remote failure)finished. total time: 0.705s

### ISSUE THREAD

**Issue by apoo7rv** [ubports/ubports-installer#465] opened 2018-09-23 17:56 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Meizu PRO 5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/bQkzZFkY7B/

**Comment by kenvandine** [comment] 2018-09-27 17:50
I'm experiencing the same issue

**Comment by NeoTheThird** [comment] 2019-03-17 16:46
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.

**Closed by NeoTheThird** 2019-03-17 16:46 UTC
Labels: duplicate
