### ISSUE TITLE
Using parameters on windows doesn't work

### ISSUE THREAD

**Issue by kisekinopureya** [ubports/ubports-installer#1466] opened 2020-10-25 12:13 UTC
**UBports Installer `0.5.6-beta` (exe)**
Environment: `Microsoft Windows 10 Home Single Language 10.0.19041 win32 10.0.19041 x64 19041 0.0` with Node.js `v12.16.3`
Device: santoni
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f956ac59702a600079d947c
Log: https://paste.ubuntu.com//p/5fgpD5kxDD/

Tried to use installer with "-f santoni.json (also tested with full path)", installer doesn't recognize json. Also tested appimage version on arch linux, it was fine

**Comment by NeoTheThird** [comment] 2020-10-25 12:57
Duplicate of #1411. If you're interested in helping to investigate, could you check if something like `ubports-installer.exe -- -f <path>` works? maybe we need to add a wrapper.

**Closed by NeoTheThird** 2020-10-25 12:57 UTC
