### ISSUE TITLE
After successfull installation, footer still display " Rebooting to recovery"

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubports-installer#1577] opened 2020-11-25 14:28 UTC
**UBports Installer `0.8.0-beta` (snap)**
Environment: `Ubuntu Core 20 linux 4.15.0-123-generic x64 NodeJS v12.16.3`
Device: hammerhead
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fbe6a1c9702a600079de446
Log: *N/A*

Install on N5 devel

**Comment by NeoTheThird** [comment] 2020-12-01 09:35
Duplicate of #1426

**Closed by NeoTheThird** 2020-12-01 09:35 UTC
Labels: needs confirmation
