### ISSUE TITLE
Report bug for Oneplus 3 UBPorts

### ISSUE THREAD

**Issue by rodolfoAlejandro** [ubports/ubports-installer#1237] opened 2020-05-29 13:39 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: OnePlus 3
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.836] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/9BTF4MhThX/ 

When UB Ports is mounting with this command "adb -P 5037 shell mount -a". The result is invalid argument. I think that the -a is the invalid argument due to when I execute this command in the terminal it runs fine with no errors.

**Comment by NeoTheThird** [comment] 2020-09-23 08:44
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:44 UTC
