### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.574s]booting...FAILED (remote failure)finished. total time: 0.574s

### ISSUE THREAD

**Issue by thrrgilag** [ubports/ubports-installer#309] opened 2018-06-22 21:17 UTC
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Package: Snap 
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/Zg7tSBNnmj/ 

Some additional notes:  After the installer detected the device and the process started, the reboot did not take the device into fastboot mode.  I held the power and volume down to force it to fastboot mode, the installer detected it and begun but then failed trying to flash boot.img

**Comment by NeoTheThird** [comment] 2018-07-01 11:00
Hey there, thanks for reporting. What OS is your Pro 5 running right now?

**Comment by thrrgilag** [comment] 2018-07-04 13:46
It has Ubuntu 15.04 (r3) currently installed.

**Comment by NeoTheThird** [comment] 2018-07-04 22:35
Could you try again with [the latest version](https://github.com/ubports/ubports-installer/releases/latest)?

**Comment by thrrgilag** [comment] 2018-07-05 04:14
It fails in the same way.  Is there anything more specific I can try or detail I can gather?

**Comment by NeoTheThird** [comment] 2019-03-17 16:45
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.

**Closed by NeoTheThird** 2019-03-17 16:45 UTC
Labels: question
