### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.678s]booting...FAILED (remote: unknown command)finished. total time: 0.692s

### ISSUE THREAD

**Issue by p0kR** [ubports/ubports-installer#505] opened 2018-10-15 19:59 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu MX4
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/h4Rzg6KN4v/

**Comment by NeoTheThird** [comment] 2019-03-13 14:56
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.

**Closed by NeoTheThird** 2019-03-13 14:56 UTC
