### ISSUE TITLE
Lost connection. Recovery flashed OK, but no luck pushing the distro files.

### ISSUE THREAD

**Issue by enragegit** [ubports/ubports-installer#1908] opened 2021-04-11 18:57 UTC
**UBports Installer `0.8.7-beta` (deb)**
Environment: `LinuxMint 19.2 Tina linux 4.15.0-129-generic x64 NodeJS v12.18.3`
Device: oneplus3
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60734660ed021f0007109da3
Log: https://paste.ubuntu.com/p/NyTcGrjZwZ/

Tried on a USB 2.0 port. The installer "loses connection". The cable has worked perfectly flashing a good number of custom ROMs on this device and a bunch of others. Is there a way to install manually? Where is the op3t image file located? I insist, it is ridiculously unlikely that either the cable (tried three of them, which had already worked flawlessly flashing TWRP and images for many devices), or my USB ports are faulty. Even assuming my cables don't meet the standards, it does not make sense to require such uber high quality cables. Most if not all UB touch compatible devices are somewhat old, so one is not likely getting new OEM-supplied cables. Please, reconsider devoting some attention to the unstable communication between the UB recovery and the device, or conversely, leave the image files somewhere to download and proceed with the install manually (using adb to push and then using the UB recovery, which seems to be working OK?)

**Comment by Keneda-ut** [comment] 2021-04-13 20:27
It's useless to post the same issue twice... https://github.com/ubports/ubports-installer/issues/1907

**Comment by enragegit** [comment] 2021-04-18 15:32
OK, it was that in this case I tried everything again using a USB 2.0 port (as opposed to a USB3.0 port) and found the same result, so USB 2 vs USB 3 is not the issue, neither is a hypothetically faulty USB port. I hoped to prevent some extra back and forth, but admittedly I am rather new to reporting issues through github.

**Comment by Keneda-ut** [comment] 2021-04-18 21:37
You can update any issue you posted, with additional post or by editing original post.
It's important to not duplicate the same issue so that dev can easily understand each one of them and don't have to "merge" the clones instead. :)

**Comment by UniversalSuperBox** [comment] 2021-04-20 20:37
Duplicate of #1907

**Closed by UniversalSuperBox** 2021-04-20 20:37 UTC

**Comment by enragegit** [comment] 2021-04-21 22:52
> You can update any issue you posted, with additional post or by editing original post.
> It's important to not duplicate the same issue so that dev can easily understand each one of them and don't have to clean the clones instead. :) (see for example)
> 
> After editing one of the clone, you can close yourself the other one.

Thanks!
