### ISSUE TITLE
Error: Failed to start adb server: Error: {"error":{"killed":false,"code":2,"signal":null,"cmd":"/Users/clarkw/Desktop/Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/platform-tools/mac/adb -P 5037 kill-server"},"stdout":"","stderr":"/bin/sh: -c: line 0: syntax error near unexpected token `勿删'\n/bin/sh: -c: line 0: `/Users/clarkw/Desktop/Applications (勿删)/ubports-installer.app/Contents/Resources/app.asar.unpacked/platform-tools/mac/adb -P 5037 kill-server'"}

### ISSUE THREAD

**Issue by clarkwang** [ubports/ubports-installer#1347] opened 2020-09-13 07:01 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: dmg
Operating System: macOS 10.15.619G2021 x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/M2G3PspkqB/

**Comment by NeoTheThird** [comment] 2020-09-23 09:34
Duplicate of #1207

**Closed by NeoTheThird** 2020-09-23 09:34 UTC
