### ISSUE TITLE
Error flashing

### ISSUE THREAD

**Issue by isularifin** [ubports/ubports-installer#1525] opened 2020-11-11 14:25 UTC
**UBports Installer `0.6.0-beta` (AppImage)**
Environment: `Debian GNU/Linux 10 buster linux 4.19.0-12-amd64 x64 NodeJS v12.16.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fabf38f9702a600079dbf91
Log: https://paste.ubuntu.com/p/5n5khjSjkB/

I have got Error:
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"/tmp/.mount_ubportCkmJTz/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fastboot\" flash boot \"/home/isul/.cache/ubports/santoni/firmware/halium-boot_santoni.img\""},"stdout":"","stderr":"Sending 'boot' (16084 KB)                          OKAY [  0.534s]\nWriting 'boot'                                     FAILED (remote: 'Partition flashing is not allowed')\nfastboot: error: Command failed"}

**Comment by NeoTheThird** [comment] 2020-11-12 10:18
Duplicate of #1498

**Closed by NeoTheThird** 2020-11-12 10:18 UTC
Labels: needs confirmation
