### ISSUE TITLE
Device cannot boot into Ubuntu Touch, stuck in recovery mode

### ISSUE THREAD

**Issue by mjwwit** [ubports/ubports-installer#1656] opened 2020-12-18 10:10 UTC
**UBports Installer `0.8.2-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.80-2-MANJARO x64 NodeJS v12.16.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fdc7fff42e3b000074c0523
Log: *N/A*

Flash Android 7.1.2, flash TWRP, format data partition, follow UBports installer 0.8.2-beta

**Comment by NeoTheThird** [comment] 2021-03-06 17:29
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:29 UTC
