### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/275/app/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/home/localadmin/snap/ubports-installer/275/.cache/ubports/flo/firmware/boot.img\""},"stdout":"","stderr":"< waiting for any device >\nSending 'boot' (11320 KB)                          OKAY [  1.375s]\nWriting 'boot'                                     FAILED (remote: '(InvalidSize)')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by marrdoc** [ubports/ubports-installer#1282] opened 2020-07-06 15:51 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":true}
Package: snap
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/pTrtvBp9cg/

**Comment by NeoTheThird** [comment] 2020-09-23 09:07
Duplicate of #1078

**Closed by NeoTheThird** 2020-09-23 09:07 UTC
