### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >target reported max download size of 134217728 bytessending 'recovery' (11436 KB)...OKAY [  0.381s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.384s

### ISSUE THREAD

**Issue by ernmander** [ubports/ubports-installer#557] opened 2018-11-26 08:04 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ M10 HD
Package: unknown
Operating System: Ubuntu Linux 18.10 cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/vFrRkmGJs8/

**Comment by NeoTheThird** [comment] 2019-03-13 14:47
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.

**Closed by NeoTheThird** 2019-03-13 14:47 UTC
