### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.443s]booting...FAILED (remote: dtb not found)finished. total time: 0.466s

### ISSUE THREAD

**Issue by craigynotknow** [ubports/ubports-installer#441] opened 2018-09-02 05:06 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/XqxjNx7MSk/

**Comment by craigynotknow** [comment] 2018-09-02 05:07
Got latest ubports and failed again...

**Comment by fabrei** [comment] 2018-09-03 08:34
i had the same log messages. maybe [this](https://github.com/ubports/ubports-installer/issues/416#issuecomment-417250720) helps :)

**Comment by fabrei** [comment] 2018-09-04 08:05
i am not an expert in this, but i see that the device is not found and the installer uses port `5038` to try to connect with it. i changed the port to `5037` (i got that trick a few months ago, but i cant remember how i found it out xD ) like i described it in the link i posted in the comment before. that worked for me and for some other people as well. did you try it?

**Comment by Xyphius** [comment] 2018-09-05 13:10
I'm experiencing the same issue. I had tried changing the port to 5037 and I'm still getting the same problem.

**Comment by fabrei** [comment] 2018-09-06 07:04
could be a problem with adb. did you try to list your adb devices? maybe you find something useful in the [docs](https://developer.android.com/studio/command-line/adb#devicestatus).

**Comment by TLysens** [comment] 2018-09-18 21:54
I have the same problem. I installed latest version of the installer for on windows. Installed the latest adb drivers. But it seems that doesn't fix it so far.

**Comment by NeoTheThird** [comment] 2019-03-13 16:30
Duplicate of #699.

**Closed by NeoTheThird** 2019-03-13 16:30 UTC
