### ISSUE TITLE
Error: systemimage: Error: Can't find latest version: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Michealhao1991** [ubports/ubports-installer#1330] opened 2020-09-02 03:50 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/MHbYXhFsKK/

**Comment by Olliyze** [comment] 2020-09-07 00:58
I'm getting this as well. I noticed that the issue has been opened in the past and closed just for it being 'network errors'. I also have a oneplus3.

**Comment by NeoTheThird** [comment] 2020-09-23 08:35
Duplicate of #1340

**Closed by NeoTheThird** 2020-09-23 08:35 UTC
