### ISSUE TITLE
Uncaught TypeError: devices.sort is not a function (MainRenderer:423)

### ISSUE THREAD

**Issue by BlueKenny** [ubports/ubports-installer#129] opened 2018-03-12 15:27 UTC
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Fedora 27
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/tsnXzsCRv7/ 

Same as #128

**Comment by BlueKenny** [comment] 2018-03-12 15:37
On version 0.1.7 it works

**Comment by NeoTheThird** [comment] 2018-03-14 10:05
Thanks for reporting, duplicate of #87

**Closed by NeoTheThird** 2018-03-14 10:05 UTC
