### ISSUE TITLE
Installer bug

### ISSUE THREAD

**Issue by tomacaster** [ubports/ubports-installer#1832] opened 2021-03-07 01:00 UTC
**UBports Installer `0.8.6-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.17763 win32 10.0.17763 x64 17763 0.0 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6044259a725a1c00074b5827
Log: *N/A*

the installer thought hammerhead was not supported. I had to select the device manually

**Comment by NeoTheThird** [comment] 2021-03-07 09:26
Duplicate of #1485

**Closed by NeoTheThird** 2021-03-07 09:26 UTC
