### ISSUE TITLE
reboots to recovery

### ISSUE THREAD

**Issue by stutteringp0et** [ubports/ubports-installer#1919] opened 2021-04-19 06:50 UTC
**UBports Installer `0.8.7-beta` (deb)**
Environment: `Ubuntu 20.04.2 LTS Focal Fossa linux 5.4.0-71-generic x64 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/607d282f7399730007f8ef93
Log: *N/A*

nexus 6p ubports deb on ubuntu

**Comment by UniversalSuperBox** [comment] 2021-04-20 20:25
Hi @stutteringp0et, could you please explain the issue you are experiencing in more detail?

**Comment by Flohack74** [comment] 2021-04-20 20:38
Also, what OS was flashed on this device before, and did you reset it to stock Android 7.1 as asked by the installer?

**Comment by NeoTheThird** [comment] 2022-03-19 19:12
this is seems to be a a duplicate of #1537. Please try [these steps](https://github.com/ubports/ubports-installer/issues/1537#issuecomment-792346472) to get it to work. sorry for the inconvenience :)

**Closed by NeoTheThird** 2022-03-19 19:12 UTC
