### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/275/app/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: Invalid argument"}

### ISSUE THREAD

**Issue by DrRoot85** [ubports/ubports-installer#1227] opened 2020-05-18 21:35 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":true,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/VsCjzm8JRf/

**Comment by NeoTheThird** [comment] 2020-09-23 08:44
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:44 UTC
