### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/275/app/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/home/pedro/snap/ubports-installer/275/.cache/ubports/flo/firmware/boot.img\""},"stdout":"","stderr":"Sending 'boot' (11320 KB)                          OKAY [  1.379s]\nWriting 'boot'                                     FAILED (remote: '(InvalidSize)')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by machadopedroh** [ubports/ubports-installer#1188] opened 2020-04-27 21:41 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":false}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/qMkFVwTmvj/

**Comment by NeoTheThird** [comment] 2020-09-23 09:07
Duplicate of #1078

**Closed by NeoTheThird** 2020-09-23 09:07 UTC
