### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >downloading 'boot.img'...OKAY [  0.767s]booting...FAILED (remote: unknown command)finished. total time: 0.781s

### ISSUE THREAD

**Issue by zikaras** [ubports/ubports-installer#328] opened 2018-06-25 20:11 UTC
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/VVZ7jQP34N/

**Comment by NeoTheThird** [comment] 2018-07-01 10:46
What OS is your device running right now?

**Comment by NeoTheThird** [comment] 2018-07-01 19:08
Duplicate of #329.

**Closed by NeoTheThird** 2018-07-01 19:08 UTC
