### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by DealerJohn** [ubports/ubports-installer#1110] opened 2020-01-26 12:57 UTC
Oneplus One hangs after installation

*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: dmg
Operating System: macOS 10.14.618G2022 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/JCH4vqNk3d/

**Comment by NeoTheThird** [comment] 2020-03-09 17:59
Duplicate of #1112

**Closed by NeoTheThird** 2020-03-09 17:59 UTC
