### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blacklist' of undefined (MainRenderer:360)

### ISSUE THREAD

**Issue by Donieck** [ubports/ubports-installer#173] opened 2018-03-27 16:21 UTC
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Package: Snap 
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/XKTmgmhrqr/

**Comment by gsilvapt** [comment] 2018-03-28 22:58
Due to the instability of cables, often devices are not recognized. I am not experienced with these logs but judging the number of errors of not being able to find the device, I'd advice starting again.

Moreover, this is a duplicate of #170 . Not sure if this was another try or not but everything is pretty much the same.

**Comment by NeoTheThird** [comment] 2018-03-30 11:13
This is a duplicate of #160 and should be fixed in the next release. Since you're using the snap, you can try this with `snap refresh ubports-installer --beta`.

**Closed by NeoTheThird** 2018-03-30 11:13 UTC
