### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blacklist' of undefined (MainRenderer:360)

### ISSUE THREAD

**Issue by Donieck** [ubports/ubports-installer#170] opened 2018-03-27 13:34 UTC
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Package: Snap 
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/WfN28KCn7M/

**Comment by gsilvapt** [comment] 2018-03-28 23:02
Potentially a duplicate of #157 as everything is very similar.

**Comment by NeoTheThird** [comment] 2018-03-30 20:27
Fixed in the upcoming release by #161.

**Closed by NeoTheThird** 2018-03-30 20:27 UTC
