### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined (MainRenderer:349)

### ISSUE THREAD

**Issue by Charley94** [ubports/ubports-installer#370] opened 2018-07-14 17:17 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Not detected
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/f3YkY542t3/

**Comment by NeoTheThird** [comment] 2018-07-17 08:49
duplicate of #368.

**Closed by NeoTheThird** 2018-07-17 08:49 UTC
