### ISSUE TITLE
After installation on Nexus 6P the system boots only into the Ubports Recovery mode

### ISSUE THREAD

**Issue by maneum1** [ubports/ubports-installer#1792] opened 2021-02-09 13:15 UTC
**UBports Installer `0.8.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.10.11-arch1-1 x64 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6022894fafa951000786e8d1
Log: *N/A*

Installation on Nexus 6P using snap image on Archlinux which runs on a VirtualBox which runs on a Windows 10 machine.
Trying to install from Windows directly did not work at all, the process always failed when getting to the point where the installation image needs to be selected. Meaning the selection page did not become available.
Using the VirtualBox the installer I over came that and the installer on the VBox Arch snap announced a successful install, but as said that install does not boot into linux touch. Only into Ubports recovery.

**Comment by NeoTheThird** [comment] 2021-03-06 17:32
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:32 UTC
