### ISSUE TITLE
unprecise downloading and selection of AOSP img file

### ISSUE THREAD

**Issue by kebeabap** [ubports/ubports-installer#1512] opened 2020-11-08 19:43 UTC
**UBports Installer `0.6.0-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.7.19-2-MANJARO x64 NodeJS v12.16.3`
Device: suzu
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa84a0f9702a600079db7fc
Log: *N/A*

start the ubports installer (snap) with an xperiax f5121 - it will open a browser tab and ask you to download the AOSP loire img (https://developer.sony.com/file/download/software-binaries-for-aosp-nougat-android-7-1-kernel-4-4-loire/). Though the installer instructions doesn't ask you to unzip the downloaded file. Also it would be helpful to have a file selector button, instead of using thunar (file explorer) to find the correct path.

**Comment by NeoTheThird** [comment] 2020-11-08 22:56
The snap package currently requires you to enter the path, because electron does not support XDG desktop portals yet, so it's impossible to open a file-picker dialog. Other packages do not have that issue, since they are unconfined. XDG support is in the works and will land in the installer as soon as possible. At that time, the text-box input in the snap will be replaced with the file-picker you see in the other packages.

The config should in fact be updated to take in the zipped file for later unpacking, thanks for reporting.

**Comment by NeoTheThird** [comment] 2020-11-15 11:43
Duplicate of #1544

**Closed by NeoTheThird** 2020-11-15 11:43 UTC
Labels: device config
