### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.577s]booting...FAILED (remote failure)finished. total time: 0.577s

### ISSUE THREAD

**Issue by nextstitch** [ubports/ubports-installer#524] opened 2018-10-28 08:41 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Meizu PRO 5
Package: snap
Operating System: Ubuntu Linux 18.10 cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/bqF4bjxh7r/

**Comment by NeoTheThird** [comment] 2019-03-13 15:57
What OS is the device running now? Possible duplicate of #221.

**Comment by NeoTheThird** [comment] 2019-03-17 16:47
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.

**Closed by NeoTheThird** 2019-03-17 16:47 UTC
Labels: question
