### ISSUE TITLE
[kagura] device keeps on restarting when prepairing image

### ISSUE THREAD

**Issue by ressanoid** [ubports/ubports-installer#1621] opened 2020-12-12 13:11 UTC
**UBports Installer `0.8.1-beta` (dmg)**
Environment: `macOS 11.0.1 macOS darwin 20.1.0 x64 20B29 NodeJS v12.16.3`
Device: kagura
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fd4c17642e3b000074bf21b
Log: https://paste.ubuntu.com/p/FK4SCJF2vf/

... use xperia XZ it seems that sony has problems with the installer

**Comment by NeoTheThird** [comment] 2021-03-06 17:16
Sorry about that, duplicate of #1402

**Closed by NeoTheThird** 2021-03-06 17:16 UTC
Labels: question
