### ISSUE TITLE
Error: Resolve device alias: Error: connect ETIMEDOUT 31.13.66.23:443

### ISSUE THREAD

**Issue by cuteinfo** [ubports/ubports-installer#1005] opened 2019-11-06 13:55 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.6-beta 
Device: Not detected
Channel: Not yet set
Package: exe
Operating System: Microsoft Windows [�汾 6.1.7601] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/X5Hp3fvvJ8/

**Comment by NeoTheThird** [comment] 2019-11-06 14:00
Hmm, we need error handling for that one, but you can just restart the installer and it should work

**Comment by NeoTheThird** [comment] 2019-11-06 14:00
Should be handled by showing the connection-lost modal

**Comment by NeoTheThird** [comment] 2019-11-21 13:58
Duplicate of #1034

**Closed by NeoTheThird** 2019-11-21 13:58 UTC
Labels: bug
