### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 134217728 bytessending 'recovery' (9708 KB)...OKAY [  0.341s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.344s

### ISSUE THREAD

**Issue by kencer** [ubports/ubports-installer#569] opened 2018-12-05 11:21 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: 
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/9CgWFXhvh2/

**Comment by NeoTheThird** [comment] 2019-03-13 14:49
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.

**Closed by NeoTheThird** 2019-03-13 14:49 UTC
