### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by emale999** [ubports/ubports-installer#877] opened 2019-09-08 17:51 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.6-beta 
Device: Not detected
Channel: Not yet set
Package: dmg
Operating System: macOS 10.13.617G65 x64 
NodeJS version: v8.2.1 

This is the screen the application looks like. Where do I have to click to start the installation process? Resizing the window doesn't show any more buttons
![Bildschirmfoto 2019-09-08 um 19 47 50](https://user-images.githubusercontent.com/12543734/64492168-91c11b80-d271-11e9-8344-893a73eea5fb.png)

Tried manual install method which works a little bit more.
Mobile phone enters fastboot mode and its display says that recovery was installed. But after that nothing more happens. And the UBPorts Installer application says "flashing recovery and system" for hours...

Error log: /p/THtnfzz2jg/

**Comment by NeoTheThird** [comment] 2019-09-09 08:14
Sorry about that. Duplicate of #806.

**Closed by NeoTheThird** 2019-09-09 08:14 UTC
