### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by SvenM74** [ubports/ubports-installer#1491] opened 2020-11-02 20:51 UTC
**UBports Installer `0.5.6-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19041 win32 10.0.19041 x64 19041 0.0` with Node.js `v12.16.3`
Device: flo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa071419702a600079da864
Log: *N/A*

**Error:**
```
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space
```

**Comment by NeoTheThird** [comment] 2020-11-03 12:03
Duplicate of #1087

**Closed by NeoTheThird** 2020-11-03 12:03 UTC
