### ISSUE TITLE
Fastboot: Unknown error:  target didn't report max-download-sizesending 'recovery' (10044 KB)...OKAY [  1.192s]writing 'recovery'...OKAY [  1.426s]finished. total time: 2.618starget didn't report max-download-sizesending 'boot' (11320 KB)...OKAY [  1.342s]writing 'boot'...FAILED (remote: (InvalidSize))finished. total time: 1.926s

### ISSUE THREAD

**Issue by montikal** [ubports/ubports-installer#853] opened 2019-08-10 04:47 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.3-beta 
Device: flo
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/XwtwSD9cpQ/

**Comment by NeoTheThird** [comment] 2019-08-27 08:39
Are you sure your device is the **Nexus 7 2013 WiFi (flo)**?

**Comment by NeoTheThird** [comment] 2019-08-28 06:42
Duplicate of #615.

**Closed by NeoTheThird** 2019-08-28 06:42 UTC
Labels: needs confirmation

**Comment by montikal** [comment] 2019-08-28 13:42
> Are you sure your device is the **Nexus 7 2013 WiFi (flo)**?

Yes. I am sure it is.
