### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by nabeel910** [ubports/ubports-installer#1157] opened 2020-04-01 15:59 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.17-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":false}
Package: source
Operating System: Arch Linux undefined undefined x64 
NodeJS version: v12.4.0 

Error log: https://paste.ubuntu.com//p/rM49WbsFm6/

**Comment by NeoTheThird** [comment] 2020-04-01 18:58
What OS was the device running?

**Comment by nabeel910** [comment] 2020-04-01 19:07
I solved the problem by going for an old jellybean factory image first then reinstalling and the installed said that the computer part is successful but the phone has been sitting in ubports recovery for a while. Sorry for the inconvenience. I know this is not a help forum but recovery logs shows nothing. 
https://imgur.com/undefined
https://imgur.com/0w4mWwM

**Comment by nabeel910** [comment] 2020-04-02 05:30
I managed to finish the installation and boot into ubuntu but I had to change the size of the cache partition to give it more space. I reduced the system partition size to 1341MB and increased the cache partition size to 599MB. Here's a link to the guide I used 
https://forum.xda-developers.com/nexus-4/general/guide-increase-nexus-4s-partition-space-t3800264

**Comment by agurenko** [comment] 2020-04-22 13:55
I believe this is a regression, since version 0.4.6 still manages to flash the device without this error. For me same happening right now with my Nexus 5, flashing from Fedora 32.

**Comment by NeoTheThird** [comment] 2020-09-23 09:56
Duplicate of #1089

**Closed by NeoTheThird** 2020-09-23 09:56 UTC
Labels: question
