### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by pleabargain** [ubports/ubports-installer#1025] opened 2019-11-14 07:36 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.8-beta 
Device: hammerhead
OS to install: Not yet set
Settings: {}
Package: deb
Operating System: Ubuntu Linux  19.10  eoan x64 
NodeJS version: v8.2.1 

Nearly an hour of fussing and got nowhere.

Here's video part iii of the failed installed :
https://youtu.be/jU3M_o8P1kQ

over 1 hour of effort and still no joy :(

The error messages stack on each other so I can't address/act on one or the other. :(

Error log: https://paste.ubuntu.com//p/rF8PK9WwNf/

**Comment by NeoTheThird** [comment] 2019-11-14 07:38
Duplicate of #1021

**Comment by NeoTheThird** [comment] 2019-11-14 07:41
Okay, after looking at your video (your log is not from the same run!), you're faced with #1018. Try again with [this version](https://github.com/ubports/ubports-installer/releases/tag/0.4.9-beta), which has that bug fixed.

**Closed** 2019-11-21 13:31 UTC
Labels: question
