### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal [...] \" non � riconosciuto come comando interno o esterno,\r\n un programma eseguibile o un file batch."}

### ISSUE THREAD

**Issue by giovortu** [ubports/ubports-installer#1449] opened 2020-10-16 12:12 UTC
**UBports Installer `0.5.4-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19041 win32 10.0.19041 x64 19041 0.0` with Node.js `v12.16.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: https://paste.ubuntu.com//p/4CCWByr4Hb/

**Error:**
```
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\giovortu\\AppData\\Local\\Temp\\1igEaIs1613hun5Q5NjwwC0zksr\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell mount -a || true"},"stdout":"","stderr":"mount: mounting /dev/block/platform/soc.0/f9824900.sdhci/by-name/vendor on /vendor failed: No such file or directory\r\nmount: mounting /dev/block/platform/soc.0/f9824900.sdhci/by-name/persist on /persist failed: No such file or directory\r\nmount: mounting /dev/block/platform/soc.0/f9824900.sdhci/by-name/modem on /firmware failed: No such file or directory\r\n\"true\" non � riconosciuto come comando interno o esterno,\r\n un programma eseguibile o un file batch."}
```

**Comment by NeoTheThird** [comment] 2020-10-28 10:55
Duplicate of #1474

**Closed by NeoTheThird** 2020-10-28 10:55 UTC
Labels: question
