### ISSUE TITLE
install did not finish upload to device

### ISSUE THREAD

**Issue by maneum1** [ubports/ubports-installer#1813] opened 2021-02-27 00:33 UTC
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6039936f16ef7600077b1b5a
Log: *N/A*

Nexus 6P install following the instructions of UBports installer

**Comment by NeoTheThird** [comment] 2021-03-06 17:32
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:32 UTC
