### ISSUE TITLE
Native tool called even though fallback tools are needed

### ISSUE THREAD

**Issue by evilvoice** [ubports/ubports-installer#786] opened 2019-05-15 15:33 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.17134.706] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/rRfdZbm2kj/

**Comment by NeoTheThird** [comment] 2019-08-27 12:07
The parts responsible for this need soooo much simplification, absolutely impossible to debug!

**Comment by NeoTheThird** [comment] 2019-08-27 12:52
Duplicate of #762.

**Closed by NeoTheThird** 2019-08-27 12:52 UTC
Labels: bug
