### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by pepper-conrad** [ubports/ubports-installer#1102] opened 2020-01-19 04:08 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: dmg
Operating System: macOS 10.13.617G10021 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/dB5dCwhvfc/

**Comment by NeoTheThird** [comment] 2020-01-22 15:33
Duplicate of #1089

**Closed by NeoTheThird** 2020-01-22 15:33 UTC
