### ISSUE TITLE
nexus 5 error

### ISSUE THREAD

**Issue by darshan-mr** [ubports/ubports-installer#1632] opened 2020-12-14 13:23 UTC
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 10 Home Single Language 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fd7672a42e3b000074bf8d3
Log: *N/A*

rror: systemimage:install: Error: {"error":{"code":1},"stdout":"adb: error: failed to copy 'C:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\pool\\ubports-9931a66ffaa043182df96ea44950d640f0427b0d98b50e6dae90e9281ae1ae7b.tar.xz' to '/cache/recovery/ubports-9931a66ffaa043182df96ea44950d640f0427b0d98b50e6dae90e9281ae1ae7b.tar.xz': remote No space left on device\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\pool\\ubports-9931a66ffaa043182df96ea44950d640f0427b0d98b50e6dae90e9281ae1ae7b.tar.xz: 1 file pushed, 0 skipped. 7.7 MB/s (392098116 bytes in 48.328s)\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\pool\\ubports-9931a66ffaa043182df96ea44950d640f0427b0d98b50e6dae90e9281ae1ae7b.tar.xz.asc: 1 file pushed, 0 skipped. 0.0 MB/s (473 bytes in 0.010s)\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\pool\\device-49aa71ad8b38e62de471640bba1a552de5846f5c0f2ff4abc0f1143d3decd0bf.tar.xz: 1 file pushed, 0 skipped. 8.2 MB/s (59668992 bytes in 6.924s)\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\pool\\device-49aa71ad8b38e62de471640bba1a552de5846f5c0f2ff4abc0f1143d3decd0bf.tar.xz.asc: 1 file pushed, 0 skipped. 0.1 MB/s (473 bytes in 0.007s)\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\pool\\keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz: 1 file pushed, 0 skipped. 5.0 MB/s (1504 bytes in 0.000s)\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\pool\\keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc: 1 file pushed, 0 skipped. 0.1 MB/s (473 bytes in 0.008s)\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\pool\\version-12.tar.xz: 1 file pushed, 0 skipped. 1.3 MB/s (460 bytes in 0.000s)\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\pool\\version-12.tar.xz.asc: 1 file pushed, 0 skipped. 0.1 MB/s (473 bytes in 0.007s)\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-signing.tar.xz: 1 file pushed, 0 skipped. 0.0 MB/s (900 bytes in 0.018s)\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 0.0 MB/s (473 bytes in 0.010s)\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-master.tar.xz: 1 file pushed, 0 skipped. 0.1 MB/s (864 bytes in 0.009s)\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-master.tar.xz.asc: 1 file pushed, 0 skipped. 0.1 MB/s (473 bytes in 0.008s)\r\nC:\\Users\\GRJ\\AppData\\Roaming\\ubports\\system-image\\ubuntu_command: 1 file pushed, 0 skipped. 0.1 MB/s (716 bytes in 0.006s)\r\n13 files pushed, 0 skipped. 7.7 MB/s (451774390 bytes in 56.281s)"}
can you give some solution to overcome this problem

**Comment by NeoTheThird** [comment] 2021-01-08 08:37
Sorry about that. Duplicate of #1052.

**Closed by NeoTheThird** 2021-01-08 08:37 UTC
