### ISSUE TITLE
Fastboot: Unknown error:  ERROR: could not clear input pipe

### ISSUE THREAD

**Issue by popesz** [ubports/ubports-installer#104] opened 2018-02-28 09:23 UTC
Automatically generated error report %0AVersion: 0.1.11-beta %0AHost OS: darwin %0AHost Dist: undefined undefined%0AHost Arch: x64 %0ANode: v8.2.1 %0A%0AError log: http://paste.ubuntu.com/p/TDxDs9xmZf/ %0A

**Comment by NeoTheThird** [comment] 2018-02-28 09:59
Duplicate of #92.

**Closed by NeoTheThird** 2018-02-28 09:59 UTC
Labels: duplicate
