### ISSUE TITLE
[kagura] device keeps on restarting and stuck on bootloader screen

### ISSUE THREAD

**Issue by ressanoid** [ubports/ubports-installer#1606] opened 2020-12-05 07:23 UTC
**UBports Installer `0.7.4-beta` (dmg)**
Environment: `macOS 11.0.1 macOS darwin 20.1.0 x64 20B29 NodeJS v12.16.3`
Device: kagura
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fcb355142e3b000074bdd94
Log: https://paste.ubuntu.com/p/mzfH8YfgbS/

run normal installer on xperia phone and it will cause this issue

**Comment by NeoTheThird** [comment] 2021-03-06 17:15
Sorry about that, duplicate of #1402.

**Closed by NeoTheThird** 2021-03-06 17:15 UTC
Labels: question
