### ISSUE TITLE
Sony Z4 - Download error

### ISSUE THREAD

**Issue by zeroxd0d0e0a0d0b0e0e0f** [ubports/ubports-installer#1680] opened 2020-12-28 10:49 UTC
Hi there, unable to set this up on Sony Z4 due to download error.

```
info: UBports Installer restarting...
info: device detected: karin
info: Installing Ubuntu Touch on your Sony Xperia Z4 Tablet4 (SGP771) (karin)
info: configuring...
info: settings: {"channel":"16.04/arm64/edge","wipe":false,"bootstrap":true}
error: download error: Error: Error: Download Error: Error: Request failed with status code 404
error: Error: core:download: Error: core:download Error: Error: Download Error: Error: Request failed with status code 404
stack trace: Error: core:download Error: Error: Download Error: Error: Request failed with status code 404
    at /tmp/.mount_ubportwvBXBi/resources/app.asar/src/core/plugins/core/plugin.js:146:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Any hints?

**Comment by NeoTheThird** [comment] 2020-12-28 14:20
Sorry about that, duplicate of #1613. Will have to confirm the url.

**Closed by NeoTheThird** 2020-12-28 14:20 UTC
