### ISSUE TITLE
Hangs at Google logo during initial boot

### ISSUE THREAD

**Issue by 4dflatlander** [ubports/ubports-installer#1667] opened 2020-12-22 19:14 UTC
**UBports Installer `0.8.2-beta` (deb)**
Environment: `LinuxMint 19.3 Tricia linux 5.4.0-58-generic x64 NodeJS v12.16.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fe2452c42e3b000074c12b0
Log: *N/A*

Suspect the vendor.img may be incorrect as phone was previously updated to angler-opm7.181105.004

**Comment by 4dflatlander** [comment] 2020-12-22 20:34
I was unable to install Ubuntu Touch stable on my Nexus 6P (angler) after re-flashing the base files from the factory image 7.1.2 using the factory image 7.1.2 (N2G48C, Aug 2017) from this location https://dl.google.com/dl/android/aosp/angler-n2g48c-factory-6a21e528.zip

**Comment by 4dflatlander** [comment] 2020-12-23 00:25
Also wiped device and tried loading latest factory image 8.1.0 (OPM7.181205.001, Dec 2018) from https://dl.google.com/dl/android/aosp/angler-opm7.181205.001-factory-b75ce068.zip, after verifying I had a running factory android system attempted to use ubports installer under Linux Mint 19.3 without any errors. This time the system will only reboot to the Ubport recovery menu. Bummer, I really like Lomiri on pinephone. If there are any suggestions I can try please let me know.

**Comment by NeoTheThird** [comment] 2021-03-06 17:30
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:30 UTC
