### ISSUE TITLE
The update was slow, and after reload the phone worked for 2-3 min, then the screen went black and unresponsive.

### ISSUE THREAD

**Issue by 065mpm** [ubports/ubports-installer#1729] opened 2021-01-14 19:30 UTC
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/600098a6203a7f0007646bfe
Log: *N/A*

Phone is Nexus 6P

I was playing around with settings, adding Norwegian keyboard and adjusting screen light level. Was exiting settings when screen went black, and did not respond to any buttons or movement on the screen. If I hold the power button, it restarts, but after a few seconds of Ubuntu loading screen, it turns black again.

Phone had no issues before I did the upgrade.

If I leave it for 1-2 min, the screen lights up for just a second or 2, it now shows the lock screen with the circle, and I just manages to swipe right to unlock, then it goes black again.

I managed to boot in bootloader, and the screen is not turning off now.
Se data on the bootloader below.

![Nexus 6P Ubuntu touch](https://user-images.githubusercontent.com/36519862/104638821-5299aa80-56af-11eb-8719-dba7517e3aad.jpg)

**Comment by 065mpm** [comment] 2021-01-14 19:56
After restarting it a couple of times, I must have pressed some setting in bootloader that reset the phone.
And after this, it works as normal.

One thing I notice, is that the LED next to the camera is now vaguely illuminated now, compared to earlier when it was off while the screen was not responding.

**Comment by NeoTheThird** [comment] 2021-03-06 17:30
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:30 UTC
