### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for hdj: < waiting for device >downloading 'boot.img'...OKAY [  0.358s]booting...FAILED (remote: dtb not found)finished. total time: 0.395s

### ISSUE THREAD

**Issue by hedingjie** [ubports/ubports-installer#690] opened 2019-03-09 06:04 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: OnePlus One
Package: unknown
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/H369fV7wbN/

**Comment by NeoTheThird** [comment] 2019-03-13 16:29
Duplicate of #699.

**Closed by NeoTheThird** 2019-03-13 16:29 UTC
