### ISSUE TITLE
Device just reboots to Ubports recovery

### ISSUE THREAD

**Issue by borzwazie** [ubports/ubports-installer#2061] opened 2021-08-04 04:11 UTC
**UBports Installer `0.8.8-beta` (AppImage)**
Environment: `Devuan GNU/Linux 4 chimaera linux 5.10.0-7-amd64 x64 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Clean Nexus 6P factory restored to Android 7.1.2. Installed TWRP successfully. Booted into TWRP recovery. Ran the Appimage installer, which apparently completed successfully. Upon reboot, the system went into recovery and would not boot system. Repeated the process twice, both unsuccessful.

**Comment by NeoTheThird** [comment] 2022-03-19 19:12
this is seems to be a a duplicate of #1537. Please try [these steps](https://github.com/ubports/ubports-installer/issues/1537#issuecomment-792346472) to get it to work. sorry for the inconvenience :)

**Closed by NeoTheThird** 2022-03-19 19:12 UTC
