### ISSUE TITLE
error at sending files, no more space left on device

### ISSUE THREAD

**Issue by inoktav** [ubports/ubports-installer#1710] opened 2021-01-08 03:43 UTC
**UBports Installer `0.8.4-beta` (snap)**
Environment: `Deepin 20 apricot linux 5.4.70-amd64-desktop x64 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5ff7d4ca203a7f0007645738
Log: *N/A*

error at sending files, no more space left on device

**Comment by NeoTheThird** [comment] 2021-01-08 08:32
Sorry about that. Duplicate of #1052.

**Closed by NeoTheThird** 2021-01-08 08:32 UTC
