### ISSUE TITLE
Overall good, but this  iteration of  the installer appeared to throw up spurious USB errors  

### ISSUE THREAD

**Issue by rdrowe** [ubports/ubports-installer#1561] opened 2020-11-20 13:48 UTC
**UBports Installer `0.7.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.16.3`
Device: vegetahd
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fb7c2b49702a600079dd76f
Log: https://paste.ubuntu.com/p/cFKRfqvvsJ/

See if it takes numerous attempts to connect to phone post fastboot section

**Comment by NeoTheThird** [comment] 2020-11-20 14:17
Thanks for reporting. Duplicate of #1511

**Closed by NeoTheThird** 2020-11-20 14:17 UTC

**Comment by rdrowe** [comment] 2020-11-20 15:21
Thanks Jan, I had missed #1511...
