### ISSUE TITLE
[angler] booting to recovery after installation

### ISSUE THREAD

**Issue by mafischer** [ubports/ubports-installer#2498] opened 2022-03-12 18:34 UTC
**UBports Installer `0.8.8-beta` (dmg)**
Environment: `macOS 12.2.1 macOS darwin 21.3.0 x64 21D62 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Follow instructions to the letter for initial installation. Installed factory image 7.1.2, then installed twrp, then wiped all partitions, then boot into fastboot, then click install.

**Comment by mafischer** [comment] 2022-03-12 18:44
I ran the installer again, this time via the ubports recovery instead of fastboot. Here is the log file which was generated in /tmp/recovery.log

```
[    0.001167] __bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
[    0.001319] Starting recovery (pid 350) on Fri Jan 30 19:46:39 1970
[    0.002347] recovery filesystem table
[    0.002398] =========================
[    0.002410]   0 /system ext4 /dev/block/platform/soc.0/f9824900.sdhci/by-name/system 0
[    0.002419]   1 /vendor ext4 /dev/block/platform/soc.0/f9824900.sdhci/by-name/vendor 0
[    0.002428]   2 /data ext4 /dev/block/platform/soc.0/f9824900.sdhci/by-name/userdata 0
[    0.002437]   3 /persist ext4 /dev/block/platform/soc.0/f9824900.sdhci/by-name/persist 0
[    0.002446]   4 /firmware vfat /dev/block/platform/soc.0/f9824900.sdhci/by-name/modem 0
[    0.002455]   5 /boot emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/boot 0
[    0.002463]   6 /recovery emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/recovery 0
[    0.002472]   7 /misc emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/misc 0
[    0.002481]   8 /modem emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/modem 0
[    0.002490]   9 /sbl1 emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/sbl1 0
[    0.002498]   10 /pmic emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/pmic 0
[    0.002507]   11 /hyp emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/hyp 0
[    0.002515]   12 /tz emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/tz 0
[    0.002524]   13 /rpm emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/rpm 0
[    0.002533]   14 /sdi emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/sdi 0
[    0.002541]   15 /aboot emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/aboot 0
[    0.002550]   16 /persistent emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/frp 0
[    0.002559]   17 /keymaster emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/keymaster 0
[    0.002568]   18 /cmnlib emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/cmnlib 0
[    0.002576]   19 auto auto /devices/*/xhci-hcd.0.auto/usb* 0
[    0.002585]   20 none swap /dev/block/zram0 0
[    0.002594]   21 /tmp ramdisk ramdisk 0
[    0.002602]
[    0.015945] E:unknown volume for path [/cache/recovery/ubuntu_command]
[    0.015991] E:Can't mount /cache/recovery/ubuntu_command
[    0.017604] locale is [en_US]
[    0.017672] stage is []
[    0.017687] reason is [(null)]
[    0.017703] I:VoldClient thread starting
[    0.017713] I:Connecting to Vold...
[    1.018726] I:Connecting to Vold...
[    2.018399] I:VoldClient initialized, storage is emulated
[    2.021811] cannot find/open a drm device: No such file or directory
[    2.024441] fb0 reports (possibly inaccurate):
[    2.024504]   vi.bits_per_pixel = 32
[    2.024516]   vi.red.offset   =   0   .length =   8
[    2.024526]   vi.green.offset =   8   .length =   8
[    2.024535]   vi.blue.offset  =  16   .length =   8
[    2.072705] framebuffer: 0 (1440 x 2560)
[    2.169702]           erasing_text: en_US (178 x 76 @ 2310)
[    2.186117]        no_command_text: en_US (330 x 76 @ 2310)
[    2.200169]             error_text: en_US (127 x 76 @ 2310)
[    2.356962]        installing_text: en_US (602 x 76 @ 2310)
[    2.423356] mount: mounting /dev/block/platform/soc.0/f9824900.sdhci/by-name/vendor on /vendor failed: No such file or directory
[    2.427531] mount: mounting /dev/block/platform/soc.0/f9824900.sdhci/by-name/userdata on /data failed: Invalid argument
[    2.430673] mount: mounting /dev/block/platform/soc.0/f9824900.sdhci/by-name/persist on /persist failed: No such file or directory
[    2.432326] mount: mounting /dev/block/platform/soc.0/f9824900.sdhci/by-name/modem on /firmware failed: No such file or directory
[    2.432868] Command: "/sbin/recovery"
[    2.432924]
[    2.433249] ro.dalvik.vm.native.bridge=0
[    2.433310] dalvik.vm.isa.arm.variant=cortex-a53.a57
[    2.433366] dalvik.vm.isa.arm.features=default
[    2.433420] dalvik.vm.isa.arm64.variant=cortex-a53
[    2.433473] dalvik.vm.isa.arm64.features=default
[    2.433527] dalvik.vm.usejit=true
[    2.433580] dalvik.vm.heapsize=512m
[    2.433632] dalvik.vm.lockprof.threshold=500
[    2.433685] dalvik.vm.dex2oat-Xms=64m
[    2.433748] dalvik.vm.dex2oat-Xmx=512m
[    2.433803] dalvik.vm.heapmaxfree=8m
[    2.433855] dalvik.vm.heapminfree=512k
[    2.433907] dalvik.vm.heapstartsize=8m
[    2.433959] dalvik.vm.appimageformat=lz4
[    2.434012] dalvik.vm.usejitprofiles=true
[    2.434064] dalvik.vm.dex2oat-threads=4
[    2.434117] dalvik.vm.heapgrowthlimit=192m
[    2.434174] dalvik.vm.stack-trace-file=/data/anr/traces.txt
[    2.434227] dalvik.vm.image-dex2oat-Xms=64m
[    2.434280] dalvik.vm.image-dex2oat-Xmx=64m
[    2.434376] dalvik.vm.boot-dex2oat-threads=4
[    2.434433] dalvik.vm.image-dex2oat-filter=verify-at-runtime
[    2.434488] dalvik.vm.heaptargetutilization=0.75
[    2.434544] dalvik.vm.image-dex2oat-threads=4
[    2.434641] ro.config.ringtone=Orion.ogg
[    2.434698] ro.config.alarm_alert=Hassium.ogg
[    2.434751] ro.config.notification_sound=Argon.ogg
[    2.434874] ro.build.fingerprint=google/angler/angler:7.1.2/N2G48C/4104010:user/release-keys
[    2.434967] vold.has_adoptable=0
[    2.435031] af.fast_track_multiplier=1
[    2.435091] cm.service.adb.root=1
[    2.435145] pm.dexopt.boot=verify-at-runtime
[    2.435199] pm.dexopt.ab-ota=speed-profile
[    2.435252] pm.dexopt.install=interpret-only
[    2.435306] pm.dexopt.core-app=speed
[    2.435359] pm.dexopt.bg-dexopt=speed-profile
[    2.435412] pm.dexopt.first-boot=verify-at-runtime
[    2.435465] pm.dexopt.shared-apk=speed
[    2.435518] pm.dexopt.nsys-library=speed
[    2.435572] pm.dexopt.forced-dexopt=speed
[    2.435626] ro.cm.build.version=14.1
[    2.435680] ro.cm.build.version.plat.rev=0
[    2.435733] ro.cm.build.version.plat.sdk=7
[    2.435785] ro.cm.device=angler
[    2.435840] ro.cm.display.version=14.1-20201228-UNOFFICIAL-angler
[    2.435894] ro.cm.version=14.1-20201228-UNOFFICIAL-angler
[    2.435947] ro.cm.releasetype=UNOFFICIAL
[    2.436000] ro.qc.sdk.audio.fluencetype=fluence
[    2.436053] ro.sf.lcd_density=560
[    2.436106] ro.com.google.clientidbase=android-google
[    2.436160] ro.frp.pst=/dev/block/platform/soc.0/f9824900.sdhci/by-name/frp
[    2.436213] ro.sys.sdcardfs=true
[    2.436266] ro.t-o.quirk.forcesink=sink.primary_output
[    2.436319] ro.t-o.quirk.forcesource=source.fast_input
[    2.436373] ro.boot.mode=normal
[    2.436426] ro.boot.flash.locked=0
[    2.436480] ro.boot.radio=angler-03.81
[    2.436533] ro.boot.console=ttyHSL0
[    2.436586] ro.boot.baseband=msm
[    2.436638] ro.boot.hardware=angler
[    2.436692] ro.boot.hardware.ddr=3072MB,HYNIX,LPDDR4
[    2.436745] ro.boot.hardware.sku=H1511
[    2.436799] ro.boot.hardware.emmc=128GB,Toshiba
[    2.436851] ro.boot.hardware.revision=ANGLER-VN2
[    2.436905] ro.boot.serialno=5VT7N16324000104
[    2.436958] ro.boot.wifi_cal=
[    2.437010] ro.boot.btmacaddr=80:13:82:14:D1:8E
[    2.437063] ro.boot.bootdevice=f9824900.sdhci
[    2.437116] ro.boot.bootloader=angler-03.68
[    2.437168] ro.boot.bootreason=recovery
[    2.437221] ro.boot.veritymode=enforcing
[    2.437273] ro.boot.wifimacaddr=80:13:82:14:CF:9E
[    2.437326] ro.boot.secure_hardware=1
[    2.437379] ro.boot.verifiedbootstate=orange
[    2.437435] ro.hwui.path_cache_size=32
[    2.437488] ro.hwui.layer_cache_size=48
[    2.437541] ro.hwui.texture_cache_size=72
[    2.437594] ro.hwui.gradient_cache_size=1
[    2.437731] ro.hwui.r_buffer_cache_size=8
[    2.437796] ro.hwui.drop_shadow_cache_size=6
[    2.437851] ro.hwui.text_large_cache_width=2048
[    2.437906] ro.hwui.text_small_cache_width=1024
[    2.437959] ro.hwui.text_large_cache_height=1024
[    2.438011] ro.hwui.text_small_cache_height=1024
[    2.438063] ro.hwui.texture_cache_flushrate=0.4
[    2.438115] ro.wifi.channels=
[    2.438168] ro.allow.mock.location=1
[    2.438222] ro.audio.monitorRotation=true
[    2.438274] ro.audio.flinger_standbytime_ms=300
[    2.438326] ro.board.platform=msm8994
[    2.438379] ro.build.id=NOF27B
[    2.438433] ro.build.date=Tue Dec 29 00:58:42 CET 2020
[    2.438486] ro.build.date.utc=1609199922
[    2.438539] ro.build.host=build3.ubports.com
[    2.438592] ro.build.tags=test-keys
[    2.438644] ro.build.type=eng
[    2.438706] ro.build.user=jenkins_worker
[    2.438760] ro.build.flavor=lineage_angler-eng
[    2.438813] ro.build.display.id=lineage_angler-eng 7.1.1 NOF27B d8ca07f99d test-keys
[    2.438865] ro.build.product=angler
[    2.438918] ro.build.selinux=1
[    2.438972] ro.build.version.sdk=25
[    2.439025] ro.build.version.base_os=
[    2.439078] ro.build.version.release=7.1.1
[    2.439130] ro.build.version.codename=REL
[    2.439182] ro.build.version.incremental=d8ca07f99d
[    2.439235] ro.build.version.preview_sdk=0
[    2.439287] ro.build.version.all_codenames=REL
[    2.439339] ro.build.version.security_patch=2017-03-05
[    2.439392] ro.build.description=angler-user 7.1.2 N2G48C 4104010 release-keys
[    2.439444] ro.build.characteristics=nosdcard
[    2.439497] ro.device.cache_dir=/cache
[    2.439550] ro.kernel.android.checkjni=1
[    2.439602] ro.secure=0
[    2.439656] ro.vendor.extension_library=libqti-perfd-client.so
[    2.439708] ro.zygote=zygote64_32
[    2.439761] ro.carrier=unknown
[    2.439814] ro.cmlegal.url=https://lineageos.org/legal
[    2.439867] ro.product.cpu.abi=arm64-v8a
[    2.439920] ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi
[    2.439973] ro.product.cpu.abilist32=armeabi-v7a,armeabi
[    2.440025] ro.product.cpu.abilist64=arm64-v8a
[    2.440078] ro.product.name=angler
[    2.440130] ro.product.board=angler
[    2.440182] ro.product.brand=google
[    2.440236] ro.product.model=Nexus 6P
[    2.440288] ro.product.device=angler
[    2.440340] ro.product.locale=en-US
[    2.440392] ro.product.manufacturer=Huawei
[    2.440444] ro.product.first_api_level=23
[    2.440496] ro.baseband=msm
[    2.440549] ro.bootmode=normal
[    2.440602] ro.facelock.det_timeout=2500
[    2.440655] ro.facelock.rec_timeout=3500
[    2.440707] ro.facelock.est_max_time=600
[    2.440759] ro.facelock.black_timeout=700
[    2.440811] ro.hardware=angler
[    2.440864] ro.opengles.version=196610
[    2.440916] ro.revision=0
[    2.441004] ro.serialno=5VT7N16324000104
[    2.441065] ro.bootimage.build.date=Tue Dec 29 00:58:42 CET 2020
[    2.441122] ro.bootimage.build.date.utc=1609199922
[    2.441175] ro.telephony.call_ring.multiple=0
[    2.441229] ro.telephony.default_network=10
[    2.441281] ro.telephony.default_cdma_sub=0
[    2.441332] ro.telephony.get_imsi_from_sim=true
[    2.441385] ro.bootloader=angler-03.68
[    2.441437] ro.debuggable=1
[    2.441491] ro.min_freq_0=384000
[    2.441543] ro.min_freq_4=384000
[    2.441596] ro.modversion=14.1-20201228-UNOFFICIAL-angler
[    2.441649] ro.recovery_id=0x1e7464391944c8b2e372cf826c686d2fc1ad1cd8000000000000000000000000
[    2.441703] ro.storage_manager.enabled=true
[    2.441755] ro.oem_unlock_supported=1
[    2.441808] drm.service.enabled=true
[    2.441863] init.svc.adbd=running
[    2.441915] init.svc.vold=running
[    2.441967] init.svc.healthd=running
[    2.442019] init.svc.ueventd=running
[    2.442071] init.svc.recovery=running
[    2.442124] init.svc.setup_adbd=stopped
[    2.442176] rild.libpath=/vendor/lib64/libril-qc-qmi-1.so
[    2.442230] vidc.enc.dcvs.extra-buff-count=2
[    2.442283] vidc.debug.perf.mode=2
[    2.442335] media.sf.omx-plugin=libffmpeg_omx.so
[    2.442389] media.sf.extractor-plugin=libffmpeg_extractor.so
[    2.442441] media.aac_51_output_enabled=true
[    2.442494] persist.hwc.mdpcomp.enable=true
[    2.442545] persist.data.mode=concurrent
[    2.442597] persist.data.iwlan.enable=true
[    2.442650] persist.camera.cpp.duplication=false
[    2.442703] persist.camera.eis.enable=1
[    2.442755] persist.camera.is_type=4
[    2.442808] keyguard.no_require_sim=true
[    2.442860] audio_hal.period_size=192
[    2.442913] telephony.lteOnCdmaDevice=1
[    2.442965] ro_debuggable=1
[    2.443274] persist.audio.fluence.speaker=true
[    2.443331] persist.audio.fluence.voicecall=true
[    2.443384] persist.audio.fluence.voicecomm=true
[    2.443437] persist.audio.product.identify=angler
[    2.443526] service.adb.root=1
[    2.443762] debug.atrace.tags.enableflags=0
[    2.443941] sys.usb.ffs.ready=1
[    2.444062] net.bt.name=Android
[    2.444126] net.change=net.bt.name
[    2.444180] net.tethering.noprovisioning=true
[    2.444234] sys.io.scheduler=bfq
[    2.444288] persist.sys.dun.override=0
[    2.444387] persist.sys.ssr.restart_level=ALL_ENABLE
[    2.444442] persist.sys.ssr.enable_ramdumps=1
[    2.444496] persist.sys.usb.config=adb
[    2.444548] persist.sys.dalvik.vm.lib.2=libart.so
[    2.444642] ro.ril.force_eri_from_xml=true
[    2.444698] persist.radio.custom_ecc=1
[    2.444751] persist.radio.data_con_rprt=true
[    2.444803] persist.radio.data_no_toggle=1
[    2.444856] persist.radio.mode_pref_nv10=1
[    2.444908] persist.radio.snapshot_timer=2
[    2.444961] persist.radio.redir_party_num=0
[    2.445013] persist.radio.always_send_plmn=true
[    2.445065] persist.radio.apm_sim_not_pwdn=1
[    2.445117] persist.radio.snapshot_enabled=1
[    2.445231]
[   41.027118] No /cache partition found.
```

**Comment by NeoTheThird** [comment] 2022-03-18 14:27
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer?

**Comment by mafischer** [comment] 2022-03-19 17:03
@NeoTheThird, I have tried again with the release version you mentioned. See the new reovery.log
```
[    0.001939] __bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
[    0.002092] Starting recovery (pid 352) on Fri Feb  6 18:05:38 1970
[    0.002105] recovery filesystem table
[    0.002115] =========================
[    0.002124]   0 /system ext4 /dev/block/platform/soc.0/f9824900.sdhci/by-name/system 0
[    0.002133]   1 /vendor ext4 /dev/block/platform/soc.0/f9824900.sdhci/by-name/vendor 0
[    0.002142]   2 /data ext4 /dev/block/platform/soc.0/f9824900.sdhci/by-name/userdata 0
[    0.002151]   3 /persist ext4 /dev/block/platform/soc.0/f9824900.sdhci/by-name/persist 0
[    0.002159]   4 /firmware vfat /dev/block/platform/soc.0/f9824900.sdhci/by-name/modem 0
[    0.002169]   5 /boot emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/boot 0
[    0.002183]   6 /recovery emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/recovery 0
[    0.002194]   7 /misc emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/misc 0
[    0.002202]   8 /modem emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/modem 0
[    0.002211]   9 /sbl1 emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/sbl1 0
[    0.002220]   10 /pmic emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/pmic 0
[    0.002229]   11 /hyp emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/hyp 0
[    0.002238]   12 /tz emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/tz 0
[    0.002247]   13 /rpm emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/rpm 0
[    0.002256]   14 /sdi emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/sdi 0
[    0.002265]   15 /aboot emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/aboot 0
[    0.002273]   16 /persistent emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/frp 0
[    0.002282]   17 /keymaster emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/keymaster 0
[    0.002291]   18 /cmnlib emmc /dev/block/platform/soc.0/f9824900.sdhci/by-name/cmnlib 0
[    0.002300]   19 auto auto /devices/*/xhci-hcd.0.auto/usb* 0
[    0.002309]   20 none swap /dev/block/zram0 0
[    0.002317]   21 /tmp ramdisk ramdisk 0
[    0.002326]
[    0.014510] E:unknown volume for path [/cache/recovery/ubuntu_command]
[    0.014555] E:Can't mount /cache/recovery/ubuntu_command
[    0.015915] locale is [en_US]
[    0.015943] stage is []
[    0.015954] reason is [(null)]
[    0.015967] I:VoldClient thread starting
[    0.015976] I:Connecting to Vold...
[    1.016394] I:Connecting to Vold...
[    2.016718] I:VoldClient initialized, storage is emulated
[    2.019994] cannot find/open a drm device: No such file or directory
[    2.020358] fb0 reports (possibly inaccurate):
[    2.020379]   vi.bits_per_pixel = 32
[    2.020390]   vi.red.offset   =   0   .length =   8
[    2.020399]   vi.green.offset =   8   .length =   8
[    2.020408]   vi.blue.offset  =  16   .length =   8
[    2.070285] framebuffer: 0 (1440 x 2560)
[    2.158153]           erasing_text: en_US (178 x 76 @ 2310)
[    2.174595]        no_command_text: en_US (330 x 76 @ 2310)
[    2.188626]             error_text: en_US (127 x 76 @ 2310)
[    2.343665]        installing_text: en_US (602 x 76 @ 2310)
[    2.411857] mount: mounting /dev/block/platform/soc.0/f9824900.sdhci/by-name/vendor on /vendor failed: No such file or directory
[    2.416220] mount: mounting /dev/block/platform/soc.0/f9824900.sdhci/by-name/userdata on /data failed: Invalid argument
[    2.419390] mount: mounting /dev/block/platform/soc.0/f9824900.sdhci/by-name/persist on /persist failed: No such file or directory
[    2.421086] mount: mounting /dev/block/platform/soc.0/f9824900.sdhci/by-name/modem on /firmware failed: No such file or directory
[    2.421619] Command: "/sbin/recovery"
[    2.421675]
[    2.421999] ro.dalvik.vm.native.bridge=0
[    2.422060] dalvik.vm.isa.arm.variant=cortex-a53.a57
[    2.422116] dalvik.vm.isa.arm.features=default
[    2.422172] dalvik.vm.isa.arm64.variant=cortex-a53
[    2.422226] dalvik.vm.isa.arm64.features=default
[    2.422281] dalvik.vm.usejit=true
[    2.422335] dalvik.vm.heapsize=512m
[    2.422389] dalvik.vm.lockprof.threshold=500
[    2.422443] dalvik.vm.dex2oat-Xms=64m
[    2.422505] dalvik.vm.dex2oat-Xmx=512m
[    2.422562] dalvik.vm.heapmaxfree=8m
[    2.422615] dalvik.vm.heapminfree=512k
[    2.422668] dalvik.vm.heapstartsize=8m
[    2.422777] dalvik.vm.appimageformat=lz4
[    2.422834] dalvik.vm.usejitprofiles=true
[    2.422887] dalvik.vm.dex2oat-threads=4
[    2.422941] dalvik.vm.heapgrowthlimit=192m
[    2.422999] dalvik.vm.stack-trace-file=/data/anr/traces.txt
[    2.423053] dalvik.vm.image-dex2oat-Xms=64m
[    2.423106] dalvik.vm.image-dex2oat-Xmx=64m
[    2.423159] dalvik.vm.boot-dex2oat-threads=4
[    2.423214] dalvik.vm.image-dex2oat-filter=verify-at-runtime
[    2.423266] dalvik.vm.heaptargetutilization=0.75
[    2.423320] dalvik.vm.image-dex2oat-threads=4
[    2.423415] ro.config.ringtone=Orion.ogg
[    2.423471] ro.config.alarm_alert=Hassium.ogg
[    2.423524] ro.config.notification_sound=Argon.ogg
[    2.423646] ro.build.fingerprint=google/angler/angler:7.1.2/N2G48C/4104010:user/release-keys
[    2.423738] vold.has_adoptable=0
[    2.423801] af.fast_track_multiplier=1
[    2.423860] cm.service.adb.root=1
[    2.423914] pm.dexopt.boot=verify-at-runtime
[    2.423968] pm.dexopt.ab-ota=speed-profile
[    2.424021] pm.dexopt.install=interpret-only
[    2.424075] pm.dexopt.core-app=speed
[    2.424129] pm.dexopt.bg-dexopt=speed-profile
[    2.424181] pm.dexopt.first-boot=verify-at-runtime
[    2.424234] pm.dexopt.shared-apk=speed
[    2.424288] pm.dexopt.nsys-library=speed
[    2.424342] pm.dexopt.forced-dexopt=speed
[    2.424396] ro.cm.build.version=14.1
[    2.424450] ro.cm.build.version.plat.rev=0
[    2.424503] ro.cm.build.version.plat.sdk=7
[    2.424555] ro.cm.device=angler
[    2.424610] ro.cm.display.version=14.1-20201228-UNOFFICIAL-angler
[    2.424664] ro.cm.version=14.1-20201228-UNOFFICIAL-angler
[    2.424717] ro.cm.releasetype=UNOFFICIAL
[    2.424771] ro.qc.sdk.audio.fluencetype=fluence
[    2.424824] ro.sf.lcd_density=560
[    2.424877] ro.com.google.clientidbase=android-google
[    2.424932] ro.frp.pst=/dev/block/platform/soc.0/f9824900.sdhci/by-name/frp
[    2.424985] ro.sys.sdcardfs=true
[    2.425038] ro.t-o.quirk.forcesink=sink.primary_output
[    2.425090] ro.t-o.quirk.forcesource=source.fast_input
[    2.425144] ro.boot.mode=normal
[    2.425198] ro.boot.flash.locked=0
[    2.425251] ro.boot.radio=angler-03.81
[    2.425305] ro.boot.console=ttyHSL0
[    2.425358] ro.boot.baseband=msm
[    2.425410] ro.boot.hardware=angler
[    2.425464] ro.boot.hardware.ddr=3072MB,HYNIX,LPDDR4
[    2.425517] ro.boot.hardware.sku=H1511
[    2.425571] ro.boot.hardware.emmc=128GB,Toshiba
[    2.425623] ro.boot.hardware.revision=ANGLER-VN2
[    2.425676] ro.boot.serialno=
[    2.425730] ro.boot.wifi_cal=
[    2.425782] ro.boot.btmacaddr=80:13:82:14:D1:8E
[    2.425835] ro.boot.bootdevice=f9824900.sdhci
[    2.425889] ro.boot.bootloader=angler-03.68
[    2.425941] ro.boot.bootreason=recovery
[    2.425994] ro.boot.veritymode=enforcing
[    2.426102] ro.boot.wifimacaddr=80:13:82:14:CF:9E
[    2.426160] ro.boot.secure_hardware=1
[    2.426215] ro.boot.verifiedbootstate=orange
[    2.426271] ro.hwui.path_cache_size=32
[    2.426327] ro.hwui.layer_cache_size=48
[    2.426380] ro.hwui.texture_cache_size=72
[    2.426433] ro.hwui.gradient_cache_size=1
[    2.426486] ro.hwui.r_buffer_cache_size=8
[    2.426539] ro.hwui.drop_shadow_cache_size=6
[    2.426593] ro.hwui.text_large_cache_width=2048
[    2.426646] ro.hwui.text_small_cache_width=1024
[    2.426698] ro.hwui.text_large_cache_height=1024
[    2.426751] ro.hwui.text_small_cache_height=1024
[    2.426803] ro.hwui.texture_cache_flushrate=0.4
[    2.426858] ro.wifi.channels=
[    2.426911] ro.allow.mock.location=1
[    2.426965] ro.audio.monitorRotation=true
[    2.427017] ro.audio.flinger_standbytime_ms=300
[    2.427071] ro.board.platform=msm8994
[    2.427123] ro.build.id=NOF27B
[    2.427177] ro.build.date=Tue Dec 29 00:58:42 CET 2020
[    2.427230] ro.build.date.utc=1609199922
[    2.427284] ro.build.host=build3.ubports.com
[    2.427337] ro.build.tags=test-keys
[    2.427389] ro.build.type=eng
[    2.427450] ro.build.user=jenkins_worker
[    2.427505] ro.build.flavor=lineage_angler-eng
[    2.427559] ro.build.display.id=lineage_angler-eng 7.1.1 NOF27B d8ca07f99d test-keys
[    2.427611] ro.build.product=angler
[    2.427663] ro.build.selinux=1
[    2.427717] ro.build.version.sdk=25
[    2.427770] ro.build.version.base_os=
[    2.427823] ro.build.version.release=7.1.1
[    2.427876] ro.build.version.codename=REL
[    2.427929] ro.build.version.incremental=d8ca07f99d
[    2.427982] ro.build.version.preview_sdk=0
[    2.428035] ro.build.version.all_codenames=REL
[    2.428088] ro.build.version.security_patch=2017-03-05
[    2.428140] ro.build.description=angler-user 7.1.2 N2G48C 4104010 release-keys
[    2.428193] ro.build.characteristics=nosdcard
[    2.428246] ro.device.cache_dir=/cache
[    2.428299] ro.kernel.android.checkjni=1
[    2.428352] ro.secure=0
[    2.428405] ro.vendor.extension_library=libqti-perfd-client.so
[    2.428457] ro.zygote=zygote64_32
[    2.428510] ro.carrier=unknown
[    2.428563] ro.cmlegal.url=https://lineageos.org/legal
[    2.428616] ro.product.cpu.abi=arm64-v8a
[    2.429412] ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi
[    2.429430] ro.product.cpu.abilist32=armeabi-v7a,armeabi
[    2.429439] ro.product.cpu.abilist64=arm64-v8a
[    2.429446] ro.product.name=angler
[    2.429454] ro.product.board=angler
[    2.429460] ro.product.brand=google
[    2.429467] ro.product.model=Nexus 6P
[    2.429473] ro.product.device=angler
[    2.429479] ro.product.locale=en-US
[    2.429486] ro.product.manufacturer=Huawei
[    2.429492] ro.product.first_api_level=23
[    2.429498] ro.baseband=msm
[    2.429504] ro.bootmode=normal
[    2.429510] ro.facelock.det_timeout=2500
[    2.429517] ro.facelock.rec_timeout=3500
[    2.429523] ro.facelock.est_max_time=600
[    2.429528] ro.facelock.black_timeout=700
[    2.429535] ro.hardware=angler
[    2.429541] ro.opengles.version=196610
[    2.429547] ro.revision=0
[    2.429553] ro.serialno=
[    2.429559] ro.bootimage.build.date=Tue Dec 29 00:58:42 CET 2020
[    2.429565] ro.bootimage.build.date.utc=1609199922
[    2.429571] ro.telephony.call_ring.multiple=0
[    2.429577] ro.telephony.default_network=10
[    2.429583] ro.telephony.default_cdma_sub=0
[    2.429589] ro.telephony.get_imsi_from_sim=true
[    2.429595] ro.bootloader=angler-03.68
[    2.429601] ro.debuggable=1
[    2.429607] ro.min_freq_0=384000
[    2.429613] ro.min_freq_4=384000
[    2.429619] ro.modversion=14.1-20201228-UNOFFICIAL-angler
[    2.429625] ro.recovery_id=0x1e7464391944c8b2e372cf826c686d2fc1ad1cd8000000000000000000000000
[    2.429631] ro.storage_manager.enabled=true
[    2.429637] ro.oem_unlock_supported=1
[    2.429643] drm.service.enabled=true
[    2.429649] init.svc.adbd=running
[    2.429654] init.svc.vold=running
[    2.429660] init.svc.healthd=running
[    2.429666] init.svc.ueventd=running
[    2.429672] init.svc.recovery=running
[    2.429678] init.svc.setup_adbd=stopped
[    2.429684] rild.libpath=/vendor/lib64/libril-qc-qmi-1.so
[    2.429690] vidc.enc.dcvs.extra-buff-count=2
[    2.429696] vidc.debug.perf.mode=2
[    2.429702] media.sf.omx-plugin=libffmpeg_omx.so
[    2.429707] media.sf.extractor-plugin=libffmpeg_extractor.so
[    2.429713] media.aac_51_output_enabled=true
[    2.429719] persist.hwc.mdpcomp.enable=true
[    2.429725] persist.data.mode=concurrent
[    2.429731] persist.data.iwlan.enable=true
[    2.429737] persist.camera.cpp.duplication=false
[    2.429743] persist.camera.eis.enable=1
[    2.429749] persist.camera.is_type=4
[    2.429755] keyguard.no_require_sim=true
[    2.429761] audio_hal.period_size=192
[    2.429766] telephony.lteOnCdmaDevice=1
[    2.429772] ro_debuggable=1
[    2.429778] persist.audio.fluence.speaker=true
[    2.429784] persist.audio.fluence.voicecall=true
[    2.429791] persist.audio.fluence.voicecomm=true
[    2.429797] persist.audio.product.identify=angler
[    2.429803] service.adb.root=1
[    2.429812] debug.atrace.tags.enableflags=0
[    2.429819] sys.usb.ffs.ready=1
[    2.429825] net.bt.name=Android
[    2.429852] net.change=net.bt.name
[    2.429861] net.tethering.noprovisioning=true
[    2.429868] sys.io.scheduler=bfq
[    2.429874] persist.sys.dun.override=0
[    2.429880] persist.sys.ssr.restart_level=ALL_ENABLE
[    2.429887] persist.sys.ssr.enable_ramdumps=1
[    2.429893] persist.sys.usb.config=adb
[    2.429898] persist.sys.dalvik.vm.lib.2=libart.so
[    2.429904] ro.ril.force_eri_from_xml=true
[    2.429910] persist.radio.custom_ecc=1
[    2.429916] persist.radio.data_con_rprt=true
[    2.429922] persist.radio.data_no_toggle=1
[    2.429928] persist.radio.mode_pref_nv10=1
[    2.429934] persist.radio.snapshot_timer=2
[    2.429940] persist.radio.redir_party_num=0
[    2.429946] persist.radio.always_send_plmn=true
[    2.429952] persist.radio.apm_sim_not_pwdn=1
[    2.429958] persist.radio.snapshot_enabled=1
[    2.429963]
```

**Comment by mafischer** [comment] 2022-03-19 17:07
It seems like the installer [config](https://github.com/ubports/installer-configs/blob/master/v2/devices/angler.yml) for angler only contains a recovery file.

**Comment by mafischer** [comment] 2022-03-19 17:09
It seems like the installer [config](https://cdimage.ubports.com/devices/angler/halium-unlocked-recovery_angler.img) for angler only contains a recovery file. The firmware for the device is missing from the config.

**Comment by NeoTheThird** [comment] 2022-03-19 19:10
yeah, so what it _should_ be doing is flash the recovery via fastboot, boot into it and then push ubuntu touch files and an `/cache/recovery/ubuntu_command` file, which then gets executed on the device for the actual installation. something there is not working due to partitions:

```
[    0.014510] E:unknown volume for path [/cache/recovery/ubuntu_command]
[    0.014555] E:Can't mount /cache/recovery/ubuntu_command
```

this is seems to be a a duplicate of #1537. Please try [these steps](https://github.com/ubports/ubports-installer/issues/1537#issuecomment-792346472) to get it to work. sorry for the inconvenience :)

**Closed by NeoTheThird** 2022-03-19 19:10 UTC
Labels: needs confirmation
