### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.361s]booting...FAILED (remote: dtb not found)finished. total time: 0.398s

### ISSUE THREAD

**Issue by nareshkadali9** [ubports/ubports-installer#463] opened 2018-09-22 22:59 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ M10 FHD
Package: unknown
Operating System: Ubuntu Linux    18.04    bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/P46FT3r3yW/

**Comment by blaubaer01** [comment] 2018-10-05 18:33
On Fairphone 2 the Version 0.1.12 works, maybe it will run with BQ M10 FHD too

**Comment by NeoTheThird** [comment] 2019-03-13 16:33
Duplicate of #699.

**Closed by NeoTheThird** 2019-03-13 16:33 UTC
