### ISSUE TITLE
Flashing unsuccessful due to missing USB drivers

### ISSUE THREAD

**Issue by 0ddb0d** [ubports/ubports-installer#1959] opened 2021-05-23 14:09 UTC
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60aa5e1438e26d0007915a45
Log: *N/A*

Basically a duplicate of issue #1937

Flashing was successful after installing [Google's USB drivers](https://developer.android.com/studio/run/win-usb) and running the installer again.

**Comment by UniversalSuperBox** [comment] 2021-06-17 21:58
Thank you for your report.

Since this is a duplicate of https://github.com/ubports/ubports-installer/issues/1922, I will close this report in favor of that one.

**Closed by UniversalSuperBox** 2021-06-17 21:58 UTC
