### ISSUE TITLE
Fastboot: Unknown error:  [sudo] heslo pro rfa: downloading 'boot.img'...OKAY [  0.376s]booting...FAILED (remote: dtb not found)finished. total time: 0.397s

### ISSUE THREAD

**Issue by fakenberg** [ubports/ubports-installer#734] opened 2019-03-25 19:30 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Ubuntu Linux  undefined  undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/6k8bpbkxSg/

**Comment by NeoTheThird** [comment] 2019-03-26 09:41
Sorry about that, seems to be a duplicate of #699. Could you install CyanogenMod 12 or Android 6 on the device and try again? If you want, you can also [use our current prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.2.2-beta) for the second installation run. Thanks for reporting and sorry for the inconvenience :]

**Closed by NeoTheThird** 2019-03-26 09:41 UTC
