### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by chunkynutella** [ubports/ubports-installer#2191] opened 2021-10-12 04:07 UTC
**UBports Installer `0.9.1-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v16.5.0`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/616509d9b26de20008d3f561

doesn't boot to os

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment] 2022-03-19 19:13
this is seems to be a a duplicate of #1537. Please try [these steps](https://github.com/ubports/ubports-installer/issues/1537#issuecomment-792346472) to get it to work. sorry for the inconvenience :)

**Closed by NeoTheThird** 2022-03-19 19:13 UTC
