### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/home/steffen/.cache/ubports/suzu/firmware/halium-unlocked-recovery_suzu.img\""},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'."}

### ISSUE THREAD

**Issue by OhneZ007** [ubports/ubports-installer#1391] opened 2020-09-28 20:50 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/grpNSHyyTr/

**Comment by NeoTheThird** [comment] 2020-09-28 21:19
Duplicate of #1305

**Closed by NeoTheThird** 2020-09-28 21:19 UTC
