### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.359s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.360s

### ISSUE THREAD

**Issue by alexlawrence** [ubports/ubports-installer#184] opened 2018-04-02 10:36 UTC
Automatically generated error report %0D%0AVersion: 0.1.12-beta %0D%0AHost OS: darwin %0D%0AHost Dist: undefined undefined%0D%0AHost Arch: x64 %0D%0ANode: v8.2.1 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/NFCYbMTwdJ/ %0D%0A

**Comment by gsilvapt** [comment] 2018-04-06 15:59
This might be related with the oem state. Can you paste here the output of this command? `fastboot oem device-info`? I'm assuming you have the fastboot tools installed.

**Comment by jonnius** [comment] 2018-05-06 17:51
I have the same issue:

Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Package: Snap 
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/CGRmxqbd5C/ 

```
$ fastboot oem device-info
...
(bootloader) 	Device tampered: false
(bootloader) 	Device unlocked: false
(bootloader) 	Charger screen enabled: true
(bootloader) 	Display panel: 
OKAY [  0.004s]
finished. total time: 0.004s
```
I had to manually select Fairphone 2. In the past the installer would recognize the phone itself. 

I have UT 15.04 installed right now. So obviously the information fastboot provides seems wrong. My phone is unlocked.

**Comment by Flohack74** [comment] 2018-05-10 09:00
No this has nothing to do with the OEM state. I used my notebook with the previous version to flash 4 or 5 times without any issues, also on the FP2, which is now affected by this bug. To me it seems that the download might be suddently corrupted or idk. Cleaning the cache may help, I will try this now.

**Comment by jonnius** [comment] 2018-05-12 16:35
A Telegramm user reporter that he could avoid this by using installer Version 0.1.9.

**Comment by Flohack74** [comment] 2018-05-12 18:46
I think this is a regression, yes. Please try 0.1.12 before downgrading too much...

**Comment by dark-eye** [comment] 2018-05-12 22:07
Same issue with a meizu PRO 5 device.
(on v0.1.13-beta of the installer)

**Comment by NeoTheThird** [comment] 2018-05-13 10:14
Seems to be a problem with the system-image-module then. I'll investigate. Downgrading to 0.1.12-beta should work, as flo said.

![this is my life now](https://media.giphy.com/media/11ZSwQNWba4YF2/giphy.gif)

**Comment by jonnius** [comment] 2018-05-13 17:29
How can I install a older version of a snap package? I found the `--revision` option, but dont know what to specify.

**Comment by gsilvapt** [comment] 2018-05-13 17:48
Instead, you could download the source code in the state of that revision (check the releases tab) and just use `npm install` and `npm run` to use the installer at a previous version.

**Comment by NeoTheThird** [comment] 2018-05-13 17:53
Rev 68 should work

**Comment by jonnius** [comment] 2018-05-21 16:56
I can confirm that using version 0.1.12 of the installer works. This is interesting, as this issue has been reported for 0.1.12 originally.

**Comment by NeoTheThird** [comment] 2018-05-25 10:57
What changed between 12 and 13 is the implementation of the new system-image node-module. Interestingly though, the code that hales the download is exactly the same, the only thing that's different is the way it's called. We seem to have introduced a weird race condition somewhere... fml

**Comment by NeoTheThird** [comment] 2018-05-25 10:58
> I can confirm that using version 0.1.12 of the installer works. This is interesting, as this issue has been reported for 0.1.12 originally.

Huh, this is interesting. It can't be the image on the server, though, since both versions are downloading exactly the same file!

**Comment by gronkern** [comment] 2018-06-26 08:53
Hello I analyzed the issue. The problem are asynchronous processes that are launched and hindering each other. I have prepared a patch that fixed the issue for me. At least I was able to install the latest version on my FP2. 
[asnyc.patch.gz](https://github.com/ubports/ubports-installer/files/2136327/asnyc.patch.gz)

I also added support for the environment variable SUDO_ASKPASS for an alternative to the current dialog.

**Comment by Flohack74** [comment] 2018-06-26 09:35
Hmm great! Are you able to file this as PR on Github, which we would prefer. Then also you are credited by mentions with this fix :)

**Comment by NeoTheThird** [comment] 2018-07-04 22:31
Could you guys try with [the latest release](https://github.com/ubports/ubports-installer/releases/latest)? Thanks

**Comment by jonnius** [comment] 2018-07-07 16:37
Just tried 0.1.18, still having the same issue.

**Comment by NeoTheThird** [comment] 2018-07-08 14:11
Since we don't *need* to flash the boot-image, i disabled that for now. Could you try again? :)

**Comment by jonnius** [comment] 2018-07-08 19:29
Still the same issue on 0.1.20. :(

**Comment by helguson** [comment] 2018-07-11 19:04
I had the same issue when I tried to install Ubuntu Touch on a new fairphone 2.

Device: fairphone 2
Host Dist: Ubuntu Linux 16.04

Version: 0.1.18-beta
Package: Snap

Version: 0.1.18-beta
Package: deb

Version: 0.1.19-beta
Package: Snap

Version: 0.1.20-beta
Package: Snap

Version 0.1.12-beta as Flohack74 suggested was able to complete the installation.

**Comment by NeoTheThird** [comment] 2018-07-12 12:11
This issue is incredibly weird.

**Comment by Ingo-FP-Angel** [comment] 2018-07-23 17:02
To add to the weirdness: I haven't seen this bug during my last two installs (FP2, opensuse leap 43.2, appimage installer). That was with 0.1.21 and 0.1.20. UT was already installed on the phone as I specifically tested the new installer versions.

And I'm *quite* sure I haven't seen it in earlier tries with even lower versions (linux appimage and windows exe), but I don't remember the exact details. I *think* for me the error was gone after the fix of gronkern was applied.

**Comment by gronkern** [comment] 2018-07-24 08:17
Hello I have developed a workaround for the issue that can easyly applied. It basically calls fastboot flash commands synchronous. This should prevent the error.

**Comment by jonnius** [comment] 2018-07-24 19:10
@gronkern is it the patch you sent before and have been asked to file a pull request?

**Comment by gronkern** [comment] 2018-10-04 20:13
Mabe you want to try my branch:
https://github.com/gronkern/ubports-installer
If it works for you I can try to merge.

**Comment by elelel** [comment] 2018-12-09 01:57
@NeoTheThird's PR #517 fixes the fastboot problem for me (checked it with the appimage included). Unfortunately the bug is not specific to fastboot, but to async calls in general. For this reason analogous fallback to sync is needed for ADB. I tried to insert a similar if condition for adb as in #517, but I could not get the code built or run neither for master, nor for PR branch at the last commit when the appimage was created (I'm not familiar with JS tooling). But I managed to successfully install 16.04 stable on Meizu Pro 5 (turbo) by fooling the async calls with delays. Here is the whole procedure in case anyone needs to install UTouch under the current state of things.

1. Download ubuntu-installer AppImage from PR #517, chmod +x it
2. Hide the real adb:
```
sudo mv /usr/bin/adb /usr/bin/adb.real
```
3. Create a wrapper script around adb which prevents reboots and insert delays /usr/bin/adb
```
#!/bin/bash
sleep 1
if [ $3 != 'reboot' ]
then
    /usr/bin/adb.real "$@"
fi
sleep 2
```
chmod +x it

4. Launch downloaded appimage from terminal
5. Put the phone in bootloader mode and choose "select manually" in the installer
6. When prompted, put the phone in recovery mode
7. The copying process will be slow because of the delays. Wait until
```
debug: reboot to recovery [DONE] err:null
```
message is displayed in the terminal and no more output is emitted for at least a couple of minutes.
8. In another terminal window issue the command:
```
sudo adb.real -P 5038 reboot recovery

```

As a side note, it would be nice to have some simple installer (maybe shell script or command line utility) that doesn't come with all that UI/async burden.

**Comment by elelel** [comment] 2018-12-31 09:37
@frthjf sorry, the symptom is too unspecific for a concrete advice. It happened to me several times, and the reason each time was different. Once I fixed it by wiping the partitions manually from TRWP, putting an old Ubuntu Touch image over them, and then flashing from the installer again.

**Comment by frthjf** [comment] 2019-01-01 13:39
Ok thanks, I'll try and fiddle around with it then!

**Comment by frthjf** [comment] 2019-01-12 11:36
Turns out the solution was simpler than I thought. I've used a live image of Ubuntu 16.04 (I'm on 18.04 at the minute) and used installer version 0.1.12. The installation went without problem. My suspicion is that the upgrade to 18.04 messed with the installer. Anyway, works now.

**Comment by NeoTheThird** [comment] 2019-03-25 11:26
Just got word that it works with [our latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.2.2-beta)! The issue was introduced in #166, causing the installer to execute `fastboot boot` even if the command was not understood. Closing until reported otherwise. Sorry it took so long, everybody!

**Closed by NeoTheThird** 2019-03-25 11:26 UTC
Labels: bug

**Comment by jonnius** [comment] 2019-03-26 06:33
This is great news. Thanks, @NeoTheThird!
