### ISSUE TITLE
Error: systemimage: Error: Can't find latest version: Error: Request failed with status code 404

### ISSUE THREAD

**Issue by joopzuur** [ubports/ubports-installer#1314] opened 2020-08-19 15:06 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.1016] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/Gh7m89SBfc/

**Comment by NeoTheThird** [comment] 2020-09-28 21:33
Probably caused by the empty channels, closing for now.

**Closed by NeoTheThird** 2020-09-28 21:33 UTC
Labels: needs confirmation
