### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.375s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.376s

### ISSUE THREAD

**Issue by ubuntushop** [ubports/ubports-installer#404] opened 2018-08-10 17:11 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Fairphone 2
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/d2VZ9YB4v8/

**Comment by ic3d** [comment] 2018-08-25 13:37
Duplicate of #387

**Comment by jonnius** [comment] 2018-10-27 07:30
Actually duplicate of #184

**Closed** 2019-03-10 08:47 UTC
