### ISSUE TITLE
Fastboot: Unknown error:  sending 'recovery' (12592 KB)...OKAY [  0.400s]writing 'recovery'...FAILED (remote: image is not a boot image)finished. total time: 0.403s

### ISSUE THREAD

**Issue by jbaruffa** [ubports/ubports-installer#477] opened 2018-09-28 05:00 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 7 2013 (LTE)
Package: source
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/qr249WxNhh/

**Comment by NeoTheThird** [comment] 2019-03-10 16:33
Duplicate of #639.

**Closed by NeoTheThird** 2019-03-10 16:33 UTC
