### ISSUE TITLE
Uncaught TypeError: devices.sort is not a function (MainRenderer:423)

### ISSUE THREAD

**Issue by uaqben** [ubports/ubports-installer#131] opened 2018-03-14 09:54 UTC
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/RpBgmvvs83/

**Comment by NeoTheThird** [comment] 2018-03-14 10:05
Thanks for reporting, duplicate of #87

**Closed by NeoTheThird** 2018-03-14 10:05 UTC
