### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by watchdogs007** [ubports/ubports-installer#1256] opened 2020-06-16 18:25 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/devel","wipe":false,"bootstrap":true,"format":false}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/rVyyThd6Dy/

**Comment by NeoTheThird** [comment] 2020-09-23 09:59
Duplicate of #1052

**Closed by NeoTheThird** 2020-09-23 09:59 UTC
