### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\diand\\AppData\\Local\\Temp\\1hyI1QEHTskiEoiim0WRgAvnirz\\resources\\app.asar.unpacked\\platform-tools\\win\\fastboot flash boot \"C:\\Users\\diand\\AppData\\Roaming\\ubports\\bacon\\firmware\\boot-bacon.img\""},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'."}

### ISSUE THREAD

**Issue by huanghester** [ubports/ubports-installer#1383] opened 2020-09-27 14:30 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: exe
Operating System: Microsoft Windows [�汾 10.0.18363.1082] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/DV4XtfyBCZ/

**Comment by NeoTheThird** [comment] 2020-09-28 21:25
duplicate of #1032

**Closed by NeoTheThird** 2020-09-28 21:25 UTC
