### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by zikaras** [ubports/ubports-installer#808] opened 2019-05-30 19:07 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: arale
Channel: ubports-touch/16.04/rc
Package: exe
Operating System: Microsoft Windows [Version 10.0.17763.503] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/r4DNGh2NyT/

**Comment by NeoTheThird** [comment] 2019-08-27 09:56
Sorry about that. Duplicate of #786.

**Closed by NeoTheThird** 2019-08-27 09:56 UTC
