### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by vovchykbratyk** [ubports/ubports-installer#1980] opened 2021-06-13 01:14 UTC
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60c55bc62acf3900071ea05e
Log: *N/A*

Install on Nexus6P (angler)

**Comment by NeoTheThird** [comment] 2022-03-19 19:12
this is seems to be a a duplicate of #1537. Please try [these steps](https://github.com/ubports/ubports-installer/issues/1537#issuecomment-792346472) to get it to work. sorry for the inconvenience :)

**Closed by NeoTheThird** 2022-03-19 19:12 UTC
