### ISSUE TITLE
Ubuntu Installation on Fairphone 2 does not continue. 

### ISSUE THREAD

**Issue by JorkvomOrk** [ubports/ubports-installer#387] opened 2018-07-25 19:03 UTC
After I have allowed OEM Debugging on the FP2 the installation program does not continue while the circle around the orange Android (?) symbol continues circling. 
My Mac is getting hotter, and the FP2 is stuck in the re-boot process, showing "Fairphone - Powered by android". 
I have tried the installation several times using different versions of the ubport installer, from version 0.1.12 up to 0.1.21-beta.dmg. 
Please help. I am frustrated. 
Thanks, Jörg

**Comment by dayrover** [comment] 2018-07-26 18:56
Seeing the same Problem with snap version 0.1.20-beta.

Fairphone 2 is in fastboot mode with the Fairphone logo showing. The connection to the phone work as autodiscovery worked and the install was able to reboot the phone in fastboot.

Last line of the install log is:

{"level":"debug","message":"fastboot: flash; [{\"url\":\"http://cdimage.ubports.com/devices/recovery-FP2.img\",\"checksum\":\"534cc2da2add4a2bd8136b01069ed7dbe432076659fd4780910b6910b916f77b\",\"type\":\"recovery\",\"path\":\"/home/michael/snap/ubports-installer/170/.cache/ubports/images/FP2\"},{\"type\":\"splash\",\"url\":\"http://cdimage.ubports.com/devices/splash-FP2.img\",\"checksum\":\"2bf76ec909af34d9896a954cd6c4ed5ad114d6053e59b7a856325b4fcfca43cd\",\"path\":\"/home/michael/snap/ubports-installer/170/.cache/ubports/images/FP2\"}]","timestamp":"2018-07-26T18:49:12.565Z"}

This hangs indefiniately while the circle spins round the Ubports logo. Disconnect the USB cable does not cause any further log or breakoff the hung flashing process.

**Comment by dayrover** [comment] 2018-07-31 19:55
Tried again from the devel channel and this fail with checksum mismatch.

{"level":"error","message":"Devices: Error: Fastboot: Unknown error:  downloading 'boot.img'...\nOKAY [  0.360s]\nbooting...\nFAILED (remote: bootimage: incomplete or not signed)\nfinished. total time: 0.362s\n","timestamp":"2018-07-31T19:17:06.854Z"}

To debug i've used the installed adb and fastboot from the snap and the cached images. With this the images sucessfully flashed. 

fastboot flash recovery /home/michael/snap/ubports-installer/170/.cache/ubports/images/FP2/recovery-FP2.img 
fastboot flash splash /home/michael/snap/ubports-installer/170/.cache/ubports/images/FP2/splash-FP2.img

Does anyone know how the Ubport-installer continue and install the 16.04/devel image?

**Comment by dayrover** [comment] 2018-08-03 15:01
Looks like after the recovery and splash images are successfully flashed the installer is attempting to
download 'boot.img' fro  'http://cdimage.ubports.com/devices/' but here there the file is named 'boot-FP2.img'

Looking at the manifest information in 'https://devices.ubports.com/api/installer/FP2' the boot image is not mentioned.
Anyone know why the installer is getting the name wrong?


Title: Fastboot: Unknown error:  downloading 'boot.img'...
OKAY [  0.363s]
booting...
FAILED (remote: bootimage: incomplete or not signed)
finished. total time: 0.364s


error 2018-07-31T18:56:41.765Z Devices: Error: Fastboot: Unknown error:  downloading 'boot.img'...
OKAY [  0.363s]
booting...
FAILED (remote: bootimage: incomplete or not signed)
finished. total time: 0.364s

info 2018-07-31T18:56:41.334Z Booting into recovery image...

**Comment by ic3d** [comment] 2018-08-15 09:46
Same error here: trying to install Ubuntu 16.04rc on Fairphone 2 using a PC with Ubuntu 18.04. After the failure I have to remove the battery to turn off the phone. The system on the phone is Ubuntu 15.04 stable. Error log below.

Fastboot: Unknown error:  < waiting for any device >downloading 'boot.img'...OKAY [  0.490s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.491s
Installing 

Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/7kswjdB5WY/

**Comment by dayrover** [comment] 2018-08-20 17:36
Error can simply reproduced by downloading 
http://cdimage.ubports.com/devices/recovey-FP2.img
and then running:
fastboot boot recover-FP2.img

It seems that the images on the cdrimage download are not signed. Anyone know how to sign them or better still upload a signed image to the site???

**Comment by dayrover** [comment] 2018-08-20 19:00
Instructions on how to sign an image can be found in 
https://forum.fairphone.com/t/fastboot-boot-is-broken/23235
and a working keystore in
https://z3ntu.github.io/2017/06/16/Signing-boot-images.html

**Comment by jonnius** [comment] 2018-10-27 07:30
This seems to be a duplicate of #184

**Closed** 2019-03-10 08:47 UTC
Labels: duplicate
