### ISSUE TITLE
Error: adb:format: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell echo ."},"stdout":"","stderr":"error: insufficient permissions for device: user in plugdev group

### ISSUE THREAD

**Issue by Chris5784** [ubports/ubports-installer#1220] opened 2020-05-16 11:42 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: arale
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/hwW7xPtz2Y/

**Comment by NeoTheThird** [comment] 2020-09-23 11:05
Duplicate of #225

**Closed by NeoTheThird** 2020-09-23 11:05 UTC
