### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/tmp/.mount_ubportW9D8yU/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: No such process"}

### ISSUE THREAD

**Issue by blackICE19240** [ubports/ubports-installer#1168] opened 2020-04-10 02:12 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":false,"bootstrap":true}
Package: AppImage
Operating System: Fedora 30 Thirty x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/cNxHHhFQc4/

**Comment by trin94** [comment] 2020-04-16 16:24
I got the same error for the same device using the 0.4.18 beta from the AUR.

**Comment by NeoTheThird** [comment] 2020-09-23 08:45
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:45 UTC
