### ISSUE TITLE
Error: adb:format: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/262/app/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell echo ."},"stdout":"","stderr":"error: device unauthorized.\nThis adb server's $ADB_VENDOR_KEYS is not set\nTry 'adb kill-server' if that seems wrong.\nOtherwise check for a confirmation dialog on your device."}

### ISSUE THREAD

**Issue by txaumevw** [ubports/ubports-installer#1086] opened 2019-12-29 17:42 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/devel","wipe":false,"bootstrap":true,"format":false}
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/5fVfnydYC2/

**Comment by ChrisPHL** [comment] 2020-01-02 12:42
Hello folks,

I just want to confirm this bug and explain my thoughts about it.
I tried to install UBports on my FP2 using the same version of the installer. It get's stuck on waiting for the device ("Connection to device lost") running the freshly installed recovery (Which btw looks pretty nice!). I'm pretty sure the cable is not the culprit since I flashed my Fairphone2 recently without encountering any issues. Furthermore I can state that I enabled developer mode on the device while running Android. What I didn't do though is to connect with adb once to set/allow the ADB_VENDOR_KEYS. :-/
So I think this should made clear at prominent stage, to point the user do so before erasing the device. Maybe the UBports recovery could even just show the confirm dialog to make sure keys are accepted?

**Comment by NeoTheThird** [comment] 2020-01-22 15:45
That's peculiar, we had that fixed at some point. Need to look into that again.

**Comment by ancas99** [comment] 2020-01-25 12:36
Hello , i have the same Problem on a Nexus 4 and a Nexus 5 Hammerhead.

**Comment by NeoTheThird** [comment] 2020-09-23 09:12
Duplicate of #983

**Closed by NeoTheThird** 2020-09-23 09:12 UTC
Labels: needs confirmation
