### ISSUE TITLE
Uncaught Error: user-open error: Object does not implement the interface (MainRenderer:39)

### ISSUE THREAD

**Issue by delijati** [ubports/ubports-installer#145] opened 2018-03-18 13:04 UTC
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/qYqdZJCg5F/

**Comment by NeoTheThird** [comment] 2018-03-19 09:47
Possible duplicate of #43, will have to investigate...

**Comment by NeoTheThird** [comment] 2018-04-30 20:42
Should be fixed in #160.

**Closed by NeoTheThird** 2018-04-30 20:42 UTC
Labels: needs confirmation
