### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.362s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.364s

### ISSUE THREAD

**Issue by epierre3** [ubports/ubports-installer#282] opened 2018-05-28 14:17 UTC
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/5nPSvmtY4t/

**Comment by NeoTheThird** [comment] 2018-06-06 09:04
Duplicate of #184.

**Closed by NeoTheThird** 2018-06-06 09:04 UTC
