### ISSUE TITLE
Nexus 5 stuck on all-white-on-black Google logo with an unlocked lock at the bottom

### ISSUE THREAD

**Issue by snickell** [ubports/ubports-installer#1702] opened 2021-01-06 12:17 UTC
**UBports Installer `0.8.2-beta` (dmg)**
Environment: `Mac OS X 10.15.7 macOS Catalina darwin 19.6.0 x64 19H15 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

install on nexus 5?

**Comment by NeoTheThird** [comment] 2021-01-08 08:33
Sorry about that. Duplicate of #1052.

**Closed by NeoTheThird** 2021-01-08 08:33 UTC
