### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by decorazonubuntu** [ubports/ubports-installer#1163] opened 2020-04-04 18:47 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.17-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":true}
Package: deb
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/Xdtd5MDYB6/

**Comment by NeoTheThird** [comment] 2020-04-05 08:11
Duplicate of #1160

**Closed by NeoTheThird** 2020-04-05 08:11 UTC
