### ISSUE TITLE
hellp

### ISSUE THREAD

**Issue by watchdogs007** [ubports/ubports-installer#1654] opened 2020-12-18 02:19 UTC
**UBports Installer `0.8.2-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-58-generic x64 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fdc117042e3b000074c0427
Log: *N/A*

Error: systemimage:install: Error: {"error":{"code":1},"stdout":"adb: error: failed to copy '/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz' to '/cache/recovery/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz': remote No space left on device\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz: 1 file pushed, 0 skipped. 9.5 MB/s (392330372 bytes in 39.301s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz.asc: 1 file pushed, 0 skipped. 4.7 MB/s (473 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/device-acd68776bf09c82adc321743a0b12171ea09a9ced25c26c854eaa8bdd520860e.tar.xz: 1 file pushed, 0 skipped. 9.5 MB/s (59671712 bytes in 5.977s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/device-acd68776bf09c82adc321743a0b12171ea09a9ced25c26c854eaa8bdd520860e.tar.xz.asc: 1 file pushed, 0 skipped. 7.7 MB/s (473 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz: 1 file pushed, 0 skipped. 24.0 MB/s (1504 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc: 1 file pushed, 0 skipped. 9.6 MB/s (473 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/version-13.tar.xz: 1 file pushed, 0 skipped. 12.9 MB/s (464 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/version-13.tar.xz.asc: 1 file pushed, 0 skipped. 12.6 MB/s (473 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/gpg/image-signing.tar.xz: 1 file pushed, 0 skipped. 22.0 MB/s (900 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/gpg/image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 11.4 MB/s (473 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/gpg/image-master.tar.xz: 1 file pushed, 0 skipped. 17.3 MB/s (864 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/gpg/image-master.tar.xz.asc: 1 file pushed, 0 skipped. 12.0 MB/s (473 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/ubuntu_command: 1 file pushed, 0 skipped. 17.2 MB/s (728 bytes in 0.000s)\n13 files pushed, 0 skipped. 9.3 MB/s (452009382 bytes in 46.396s)"}

Error: systemimage:install: Error: {"error":{"code":1},"stdout":"adb: error: failed to copy '/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz' to '/cache/recovery/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz': remote No space left on device\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz: 1 file pushed, 0 skipped. 9.5 MB/s (392330372 bytes in 39.301s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz.asc: 1 file pushed, 0 skipped. 4.7 MB/s (473 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/device-acd68776bf09c82adc321743a0b12171ea09a9ced25c26c854eaa8bdd520860e.tar.xz: 1 file pushed, 0 skipped. 9.5 MB/s (59671712 bytes in 5.977s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/device-acd68776bf09c82adc321743a0b12171ea09a9ced25c26c854eaa8bdd520860e.tar.xz.asc: 1 file pushed, 0 skipped. 7.7 MB/s (473 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz: 1 file pushed, 0 skipped. 24.0 MB/s (1504 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc: 1 file pushed, 0 skipped. 9.6 MB/s (473 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/version-13.tar.xz: 1 file pushed, 0 skipped. 12.9 MB/s (464 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/pool/version-13.tar.xz.asc: 1 file pushed, 0 skipped. 12.6 MB/s (473 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/gpg/image-signing.tar.xz: 1 file pushed, 0 skipped. 22.0 MB/s (900 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/gpg/image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 11.4 MB/s (473 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/gpg/image-master.tar.xz: 1 file pushed, 0 skipped. 17.3 MB/s (864 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/gpg/image-master.tar.xz.asc: 1 file pushed, 0 skipped. 12.0 MB/s (473 bytes in 0.000s)\n/home/khedri/snap/ubports-installer/330/.cache/ubports/system-image/ubuntu_command: 1 file pushed, 0 skipped. 17.2 MB/s (728 bytes in 0.000s)\n13 files pushed, 0 skipped. 9.3 MB/s (452009382 bytes in 46.396s)"}

**Comment by NeoTheThird** [comment] 2021-01-08 08:38
Sorry about that. Duplicate of #1052.

**Closed by NeoTheThird** 2021-01-08 08:38 UTC
