### ISSUE TITLE
Nexus 5 stuck on boot after install

### ISSUE THREAD

**Issue by ddveras** [ubports/ubports-installer#1653] opened 2020-12-18 00:53 UTC
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fdbfd5a42e3b000074c03f5
Log: Error: systemimage:install: Error: {"error":{"code":1},"stdout":"adb: error: failed to copy 'C:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\pool\\ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz' to '/cache/recovery/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz': remote No space left on device\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\pool\\ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz: 1 file pushed, 0 skipped. 6.3 MB/s (392330372 bytes in 59.607s)\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\pool\\ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz.asc: 1 file pushed, 0 skipped. 0.5 MB/s (473 bytes in 0.001s)\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\pool\\device-acd68776bf09c82adc321743a0b12171ea09a9ced25c26c854eaa8bdd520860e.tar.xz: 1 file pushed, 0 skipped. 6.4 MB/s (59671712 bytes in 8.882s)\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\pool\\device-acd68776bf09c82adc321743a0b12171ea09a9ced25c26c854eaa8bdd520860e.tar.xz.asc: 1 file pushed, 0 skipped. 0.5 MB/s (473 bytes in 0.001s)\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\pool\\keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz: 1 file pushed, 0 skipped. 8.4 MB/s (1504 bytes in 0.000s)\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\pool\\keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc: 1 file pushed, 0 skipped. 0.8 MB/s (473 bytes in 0.001s)\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\pool\\version-13.tar.xz: 1 file pushed, 0 skipped. 2.9 MB/s (464 bytes in 0.000s)\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\pool\\version-13.tar.xz.asc: 1 file pushed, 0 skipped. 0.7 MB/s (473 bytes in 0.001s)\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-signing.tar.xz: 1 file pushed, 0 skipped. 1.4 MB/s (900 bytes in 0.001s)\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 0.8 MB/s (473 bytes in 0.001s)\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-master.tar.xz: 1 file pushed, 0 skipped. 1.3 MB/s (864 bytes in 0.001s)\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-master.tar.xz.asc: 1 file pushed, 0 skipped. 0.5 MB/s (473 bytes in 0.001s)\r\nC:\\Users\\thunderCATUPIRY\\AppData\\Roaming\\ubports\\system-image\\ubuntu_command: 1 file pushed, 0 skipped. 1.0 MB/s (728 bytes in 0.001s)\r\n13 files pushed, 0 skipped. 6.2 MB/s (452009382 bytes in 69.556s)"}

After using UBports Installer (0.8.2-beta) to flash ubuntu in hammerhead everything runs smoothly until last second where error pops out, if I ignore ubuntu will finish installing on nexus but gets stuck on boot image.

**Comment by NeoTheThird** [comment] 2021-01-08 08:38
Sorry about that. Duplicate of #1052.

**Closed by NeoTheThird** 2021-01-08 08:38 UTC
