### ISSUE TITLE
Error: adb:format: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/cache on /cache failed: Invalid argument

### ISSUE THREAD

**Issue by dakling** [ubports/ubports-installer#1311] opened 2020-08-13 15:57 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":false,"format":false}
Package: source
Operating System: Manjaro Linux 20.0.3 lysia x64 
NodeJS version: v12.4.0 

Error log: https://paste.ubuntu.com//p/yZbgjcPsqR/

**Comment by NeoTheThird** [comment] 2020-09-23 08:42
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:42 UTC
