### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.329s]booting...FAILED (remote: dtb not found)finished. total time: 0.351s

### ISSUE THREAD

**Issue by coolcourd** [ubports/ubports-installer#559] opened 2018-11-27 07:22 UTC
*Automatically generated error report* 
UB

I get this error trying to install from my windows machine or linux

**Comment by NeoTheThird** [comment] 2019-03-13 16:12
What device is this?

**Comment by NeoTheThird** [comment] 2019-03-13 16:30
Duplicate of #699.

**Closed by NeoTheThird** 2019-03-13 16:30 UTC
