### ISSUE TITLE
I got flasing is not allowed in lock state

### ISSUE THREAD

**Issue by gshaibi** [ubports/ubports-installer#2347] opened 2021-12-14 08:15 UTC
**UBports Installer `0.8.9-beta` (dmg)**
Environment: `macOS 11.3.1 macOS Big Sur darwin 20.4.0 x64 20E241 NodeJS v12.18.3`
Device: lavender
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Install on Redmi note 7 and select wipe all data

**Comment by NeoTheThird** [comment] 2022-03-15 16:05
Duplicate of #2171. please try again with [the latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) and open a new issue if the problem persists.

**Closed by NeoTheThird** 2022-03-15 16:05 UTC
