### ISSUE TITLE
Ubuntu Touch fails to install on Nexus 7 2013 wifi flo

### ISSUE THREAD

**Issue by robert97520** [ubports/ubports-installer#855] opened 2019-08-20 19:06 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.3-beta 
Device: flo
Channel: Not yet set
Package: deb
Operating System: Ubuntu Linux   16.04   xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/gHhD27KR4W/ 

Nexus 7 freezes with error message "This device needs restoring from a PC or service center"

**Comment by NeoTheThird** [comment] 2019-08-27 10:10
Could you try again with the latest version?

**Comment by NeoTheThird** [comment] 2019-08-27 13:30
Pinging @UniversalSuperBox. Any ideas what's going on here?

**Comment by NeoTheThird** [comment] 2019-08-27 13:34
duplicate of #615

**Closed by NeoTheThird** 2019-08-27 13:34 UTC
Labels: bug
