### ISSUE TITLE
Installer detects the BQ M10 FHD but the Installer windows stays white

### ISSUE THREAD

**Issue by achimboers** [ubports/ubports-installer#824] opened 2019-06-11 17:39 UTC
![Screen Shot 2019-06-11 at 19 39 17](https://user-images.githubusercontent.com/24492395/59293958-a0069800-8c80-11e9-854f-924749259fb4.png)
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: frieza
Channel: Not yet set
Package: dmg
Operating System: macOS 10.11.615G22010 x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/9VZsqyx6nX/

**Comment by NeoTheThird** [comment] 2019-08-27 09:42
Sorry about that. Duplicate of #806

**Closed by NeoTheThird** 2019-08-27 09:42 UTC
