### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.359s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.360s

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubports-installer#271] opened 2018-05-21 11:43 UTC
Automatically generated error report 
Version: 0.1.13-beta **appimage**
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/zk2BgbJ6nB/

**Comment by pixelr0** [comment] 2018-05-21 12:06
fp2 (with 15.04) + dev mode. phone detected by both ubuntu and installer, options 16.04 dev + wipe and then this error ^^

**Comment by jonnius** [comment] 2018-05-21 16:53
May be a duplicate of #184

**Closed** 2018-05-25 10:59 UTC
Labels: duplicate
