### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.607s]booting...FAILED (remote failure)finished. total time: 0.607s

### ISSUE THREAD

**Issue by jdhoek** [ubports/ubports-installer#355] opened 2018-07-06 09:00 UTC
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/qS8qQs9KzK/

**Comment by jdhoek** [comment] 2018-07-06 09:02
I'm trying to migrate from the Canonical image to UBPorts. I have powered up the phone with `vol-` + `power` (it says Fastboot mode (unlocked, unrooted)).

```
# sudo fastboot devices
04f44d5f2148	fastboot
```

I don't think the installer sees the phone.

**Comment by jdhoek** [comment] 2018-07-06 09:16
This is what the installer is repeating when I start it after the phone is in fastboot mode:

> Error: Command failed: adb -P 5038 shell echo 1

**Comment by NeoTheThird** [comment] 2018-07-08 10:00
Hey there, this might be a case of #225. Please try [this](https://github.com/ubports/ubports-installer#device-not-detected-linux)

**Comment by jdhoek** [comment] 2018-07-11 08:22
I have added those Udev-rules, and `lsusb` shows a *Google Inc* device.

When I run the installer it recognises my phone, and I can start the process, but it won't progress past the next phase until I shutdown the phone and boot it up with `vol -` and `power` held. After that, the installer fails with this output:

```
Pug interceptor registered successfully
debug: Using native platform tools!
debug: 
debug: 
debug: adb shell: echo 1
debug: Successfully downloaded devices list
debug: 
debug: adb shell: getprop ro.product.device
debug: 
debug: getprop: turbo
debug: adb shell: cat /etc/system-image/channel.ini
debug: 
debug: adb shell: echo 1
debug: 
debug: reboot to bootloader
debug: 
debug: reboot to bootloader [DONE] err:null
debug: checking password
debug: correct password
debug: fastboot: wait for device
info: Download startCheck
info: checked: recovery-turbo.img
info: /home/freaknl/.cache/ubportsimages/turbo/recovery-turbo.img already exists with the expected checksum, so download will be skipped
info: Download complete
info: done downloading(once listener)
debug: fastboot: flash; [{"type":"recovery","url":"http://cdimage.ubports.com/devices/recovery-turbo.img","checksum":"632dae343d026d755867c43ba8634c42edcc5d2b81856e790ebc8d71eaf18c03","path":"/home/freaknl/.cache/ubportsimages/turbo"}]
info: Booting into recovery image...
error: Devices: Error: Fastboot: Unknown error:  downloading 'boot.img'...
OKAY [  0.641s]
booting...
FAILED (remote failure)
finished. total time: 0.641s
```

**Comment by NeoTheThird** [comment] 2019-03-17 16:46
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.

**Closed by NeoTheThird** 2019-03-17 16:46 UTC
Labels: question
