### ISSUE TITLE
Error: adb:wait: Error: {"error":{"code":1,"cmd":"C:\\Users\\trist\\AppData\\Local\\Temp\\1pQNDpI5Kn6teIMMfkwxEiCc0hT\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 wait-for-any-any"},"stderr":"error: more than one device/emulator"}

### ISSUE THREAD

**Issue by sw0leymammoth** [ubports/ubports-installer#1839] opened 2021-03-10 02:34 UTC
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6048303252bd840007f91e4c
Log: *N/A*

Try to install

**Error:**
```
Error: adb:wait: Error: {"error":{"code":1,"cmd":"C:\\Users\\trist\\AppData\\Local\\Temp\\1pQNDpI5Kn6teIMMfkwxEiCc0hT\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 wait-for-any-any"},"stderr":"error: more than one device/emulator"}
```

**Comment by NeoTheThird** [comment] 2021-03-10 08:35
Duplicate of #653

**Comment by NeoTheThird** [comment] 2021-03-10 08:36
To work around this, you'll have to make sure you only have one ADB device connected to your PC. Unplug all other phones, except the one you want to install.

**Closed by NeoTheThird** 2021-03-10 08:35 UTC

**Comment by sw0leymammoth** [comment] 2021-03-10 19:10
Hi Jan!

No other phones were plugged in while trying to install. I'm not sure what
else could be causing that to go off.

Cheers,

Tristen Nelson

**Comment by NeoTheThird** [comment] 2021-03-10 20:39
Did you by any chance have an android emulator (like for android app development) running on the computer? To be sure, you could run the `adb devices` command and check the output.

**Comment by sw0leymammoth** [comment] 2021-03-10 23:25
Nope, there's nothing else attached or running it seems😓
[image: image.png]

-Tristen Nelson

**Comment by sw0leymammoth** [comment] 2021-03-10 23:28
I just gave it another shot and got the same error:

Error: adb:wait: Error:
{"error":{"code":1,"cmd":"C:\\Users\\trist\\AppData\\Local\\Temp\\1pQNDpI5Kn6teIMMfkwxEiCc0hT\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe
-P 5037 wait-for-any-any"},"stderr":"error: more than one
device/emulator"}


-Tristen Nelson
