### ISSUE TITLE
Fastboot: Unknown error:  [sudo] Passwort für franziska: downloading 'boot.img'...OKAY [  0.493s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.494s

### ISSUE THREAD

**Issue by Mondschein93** [ubports/ubports-installer#457] opened 2018-09-16 08:47 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/crfG7qSvZG/

**Comment by jonnius** [comment] 2018-10-27 07:31
duplicate of #184

**Comment by NeoTheThird** [comment] 2019-03-10 08:49
Duplicate of #184. Try again with UBports Installer 0.1.12-beta.

**Closed by NeoTheThird** 2019-03-10 08:49 UTC
