### ISSUE TITLE
Uncaught Error: user-open error: Object does not implement the interface (MainRenderer:39)

### ISSUE THREAD

**Issue by Markm52** [ubports/ubports-installer#179] opened 2018-03-29 22:28 UTC
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux undefined
Package: Snap 
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/fxBytBs9Y7/

**Comment by gsilvapt** [comment] 2018-03-30 01:05
@Markm52 Thanks for reporting. Judging by the log, it seems adb was not able to find the device. Do you think you could try installing again? If this was not a first-time error, can you run `adb devices` and confirm if adb finds your device?

**Comment by gsilvapt** [comment] 2018-03-30 01:09
Potential duplicate of #145, although this one did **not** return the reboot parts. @Markm52 if you follow the bugs, there are some suggestions from Neo to workaround this issue.

**Closed** 2018-07-04 22:13 UTC
Labels: question
