### ISSUE TITLE
Installer hangs at "Flashing firmware partitions using fastboot"

### ISSUE THREAD

**Issue by ok-what** [ubports/ubports-installer#1167] opened 2020-04-08 16:46 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/devel","wipe":true,"bootstrap":true}
Package: AppImage
Operating System: Linux Mint 19.2 tina x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/WtKvGmz5v6/ 

I've tried both the .deb and appimage versions. In the appimage when asked whether I want to set the udev rules I let the installer do it automatically. I've tried the stable and development branches. Both times I had "wipe" and "fastboot" enabled. I unlocked the device myself earlier. The device screen shows that it's in fastboot mode and `sudo fastboot devices` lists the device. When I stop the installation and do `sudo fastboot reboot` it normally boots into Android like nothing changed.

I did a backup with TWRP without letting it modify my phone, so flashing that image worked just fine. Copying the backup to my pc also worked without any issues so I don't think there's anything wrong with the cable.

On this third attempt I've let it do its thing for about 80 minutes now.

Btw, the automatic error log seems to be in a weird order. Here's the rest of the log saved in ~/.config/ubports after it downloaded everything: https://pastebin.com/B9zxrA1F

Edit: Apparently I _do_ still have TWRP as my recovery image. Maybe that could be causing the issue?
Edit 2: I set the recovery image back to the default one. I've tried it with and without 'wipe' enabled, didn't seem to make a difference. Not sure what disabling the 'fastboot' option does so I haven't tried disabling it.
The "waiting for devices" at the end of the pastebin log seems suspicious.

**Comment by ok-what** [comment] 2020-04-08 16:49
Similar issues:
https://forums.ubports.com/topic/3412/oneplus-one-installation-stuck-on-flashing-in-fastboot
somewhat similar: https://github.com/ubports/ubports-installer/issues/1029

**Comment by ok-what** [comment] 2020-07-13 13:01
Other similar ones:
- https://forums.ubports.com/topic/4337/oneplus-one-installer-hangs-on-flashing-firmware
- https://forums.ubports.com/topic/4384/oneplus-one-install-failed-cannot-flash-ubports-recovery
- https://forums.ubports.com/topic/4362/oneplus-one-failed/30?_=1594644009485 and

I've gone through all of those posts, and have tried everything except clearing the device cache and using an old version of the installer ( someone recommended this https://github.com/ubports/ubports-installer/releases/tag/0.2.6-beta ). I'll try those things later.
It seems that the thing in common is that all of them use Linux Mint. Is that a coincidence or could that be part of the issue?

A tip I found which I'll try later:
https://forums.ubports.com/topic/3826/ubuntu-touch-won-t-install-on-oneplus-one-apparently-successful-install-won-t-boot-up/12?_=1594644087864
I'll try clearing the cache.

**Comment by NeoTheThird** [comment] 2020-09-23 10:40
> Linux Mint

That's an interesting hypothesis! I would not put it past the mint devs to do something weird there intended to make peoples lives easier but actually breaking stuff. Needs investigation.

**Comment by NeoTheThird** [comment] 2020-10-03 19:46
Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.5.2-beta) and let me know how it goes? We fixed some waiting conditions here, so this might just do the trick.

**Comment by ok-what** [comment] 2020-10-25 16:18
Hi, I'm really sorry it took so long to reply.
I tried the latest release (0.5.5) and the one you linked (0.5.2) and both of them had the same issue as last time. I've tried it with and without wipe selected and I let it do its thing for a lot longer than 20 minutes both times.

**Comment by NeoTheThird** [comment] 2020-10-26 15:55
Okay, i know what's going on. Duplicate of #1367

**Closed by NeoTheThird** 2020-10-26 15:55 UTC
Labels: needs confirmation

**Comment by ok-what** [comment] 2020-12-06 14:02
Thanks a lot! :)
It worked correctly now with some minor issues that I reported.
