### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by JeanVert** [ubports/ubports-installer#1205] opened 2020-05-06 20:19 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: dora
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/anpok/devel","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/qyH93scBss/

**Comment by NeoTheThird** [comment] 2020-09-23 11:14
duplicate of #1071

**Closed by NeoTheThird** 2020-09-23 11:14 UTC
