### ISSUE TITLE
Flashing seemed to work fine, but ended up in UBports recovery, without being able to start Ubuntu touch

### ISSUE THREAD

**Issue by severin-lemaignan** [ubports/ubports-installer#1881] opened 2021-03-27 10:49 UTC
**UBports Installer `0.8.7-beta` (deb)**
Environment: `Ubuntu 20.04.2 LTS Focal Fossa linux 5.4.0-70-generic x64 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/605f0dae90d83900079eb869
Log: *N/A*

Started the process from a freshly re-installed stock Android 7.1.2. Install twrp-3.5.1 (via fastboot) and wiped all partitions. Started the installation from ubport-installer. ubports-installer completed without issues, but the phone reboot to ubports recovery, without any way to actually start ubuntu touch.

**Comment by NeoTheThird** [comment] 2022-03-19 19:12
this is seems to be a a duplicate of #1537. Please try [these steps](https://github.com/ubports/ubports-installer/issues/1537#issuecomment-792346472) to get it to work. sorry for the inconvenience :)

**Closed by NeoTheThird** 2022-03-19 19:12 UTC
