### ISSUE TITLE
No standard way to quit app on macos

### ISSUE THREAD

**Issue by azzid** [ubports/ubports-installer#1434] opened 2020-10-07 18:59 UTC
UBports Installer: `0.5.2-beta` 
Device: `frieza` 
OS to install: Ubuntu Touch 
Settings: undefined 
Package: `dmg` 
Operating System: Mac OS X 10.15.6 macOS Catalina darwin 19.6.0 x64 19G2021 
NodeJS version: `v12.0.0` 
Error log: https://paste.ubuntu.com// 
``` 
⌘-Q does not quit the application.
There is no 'quit'-option in the menu.

There should probably be a more MacOS native 'quit'-function in the MacOS version of the application.
```

**Comment by NeoTheThird** [comment] 2020-10-10 07:48
Duplicate of #1047

**Closed by NeoTheThird** 2020-10-10 07:48 UTC
