### ISSUE TITLE
Checksum failure on the file SW_binaries_for_Xperia_AOSP_N_MR1_5.7_r1_v08_loire.zip  had to restart the installer. Second try it worked.

### ISSUE THREAD

**Issue by nanu-c** [ubports/ubports-installer#1798] opened 2021-02-13 13:45 UTC
**UBports Installer `0.8.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-41-generic x64 NodeJS v12.18.3`
Device: suzu
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6027d7e8afa951000786f450
Log: https://paste.ubuntu.com/p/dPttbwKkF7/

Try to install normally and then enter the path, then it fails

**Comment by ix5** [comment] 2021-02-21 21:33
Duplicate of https://github.com/ubports/ubports-installer/issues/1798

**Comment by ix5** [comment] 2021-03-01 16:46
@nanu-c please see whether https://github.com/ubports/ubports-installer/pull/1786 fixes your issue

**Comment by NeoTheThird** [comment] 2021-03-06 17:04
not reproducible for me any more with @ix5's fix

**Closed by NeoTheThird** 2021-03-06 17:04 UTC
