### ISSUE TITLE
UBports installer says 'connectiion to device lost' instead of 'device not found' when no device is connected

### ISSUE THREAD

**Issue by eightdot** [ubports/ubports-installer#1455] opened 2020-10-21 13:30 UTC
**UBports Installer `0.5.4-beta` (deb)**
Environment: `Debian GNU/Linux unknown linux 5.8.0-1-amd64 x64` with Node.js `v12.16.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f903667fd51f200075a4a68
Log: https://paste.ubuntu.com//p/NWNHRmBxPf/

* do not connect a device
* open UBports Installer
* Select device manually
* Select Oneplus One (bacon)
* click install and next
* on 'Reboot to Bootloader' click Continue
now an error pops up that says: "Connection to device lost" and suggests trying another usb cable

i think it should have said that it cannot find the device

**Comment by NeoTheThird** [comment] 2020-10-21 14:18
Duplicate of #1056

**Closed by NeoTheThird** 2020-10-21 14:18 UTC
