### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.361s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.362s

### ISSUE THREAD

**Issue by siragi** [ubports/ubports-installer#545] opened 2018-11-20 09:19 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Fairphone 2
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/cYcBkHqYwJ/

**Comment by Ingo-FP-Angel** [comment] 2018-11-23 07:50
Could you try this version: https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fubports-installer/detail/PR-517/6/artifacts

It should fix that "incomplete or not signed" error (but might have other problems).

**Comment by jonnius** [comment] 2018-12-13 17:44
duplicate of #184

**Closed** 2019-03-10 08:56 UTC
