### ISSUE TITLE
Installer hangs with Aquaris 4.5 in Fastboot...

### ISSUE THREAD

**Issue by skvamme** [ubports/ubports-installer#111] opened 2018-03-01 12:35 UTC
Device: BQ Aquaris 4.5 Ubuntu with Canonical images. Developer Mode is On.
Installer: MAC version

Steps to reproduce
Start Installer. Connect Phone. Installer identifies Phone correctly. Type Password. Phone goes to Fastboot. Installer hangs indefinitely. Phone stays in Fastboot until manually rebooted.

I tried to manually put the phone in fastboot mode, same result.

**Comment by NeoTheThird** [comment] 2018-03-01 12:42
Probably a duplicate of #92. Closing for now. Thanks for reporting, though :)

**Closed by NeoTheThird** 2018-03-01 12:42 UTC
