### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":fa [...]                          FAILED (File is too large to download)\r\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by aleksandersciubisz** [ubports/ubports-installer#1489] opened 2020-11-02 18:25 UTC
**UBports Installer `0.5.6-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.18362 win32 10.0.18362 x64 18362 0.0` with Node.js `v12.16.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa04eb09702a600079da808
Log: https://paste.ubuntu.com//

**Error:**
```
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\Users\\marle\\AppData\\Local\\Temp\\1jMdTdVOhwHx82J6jvAT35OzJyY\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\fastboot.exe\" flash boot \"C:\\Users\\marle\\AppData\\Roaming\\ubports\\santoni\\firmware\\halium-boot_santoni.img\""},"stdout":"","stderr":"< waiting for any device >\r\nSending 'boot' (0 KB)                              FAILED (File is too large to download)\r\nfastboot: error: Command failed"}
```

**Comment by NeoTheThird** [comment] 2020-11-03 11:59
Duplicate of #1488

**Closed by NeoTheThird** 2020-11-03 11:59 UTC
