### ISSUE TITLE
Error: adb:format: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/275/app/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell echo ."},"stdout":"","stderr":"error: device unauthorized.\nThis adb server's $ADB_VENDOR_KEYS is not set\nTry 'adb kill-server' if that seems wrong.\nOtherwise check for a confirmation dialog on your device."}

### ISSUE THREAD

**Issue by SAdamchick** [ubports/ubports-installer#1202] opened 2020-05-05 21:15 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":false}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/RYQsf8nMRK/

**Comment by NeoTheThird** [comment] 2020-09-23 09:12
Duplicate of #983

**Closed by NeoTheThird** 2020-09-23 09:12 UTC
