### ISSUE TITLE
Adb push error: cannot stat ''C:\Users\accountname\AppData\Roaming\ubports\pool/ubports-3a54a53a92abad43f475de97cc2851031987120be96fda76c30f863e3fb2fb91.tar.xz'': No such file or directory

### ISSUE THREAD

**Issue by candiedhax0r** [ubports/ubports-installer#220] opened 2018-04-29 20:43 UTC
A

**Comment by NeoTheThird** [comment] 2018-04-30 03:29
Duplicate of #110.

**Closed by NeoTheThird** 2018-04-30 03:29 UTC
