### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by jeanstanis** [ubports/ubports-installer#1401] opened 2020-09-30 13:01 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":false}
Package: deb
Operating System: Ubuntu  20.04  focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/sxg4Vdsgw3/

**Comment by NeoTheThird** [comment] 2020-09-30 14:04
Duplicate of #1087

**Closed by NeoTheThird** 2020-09-30 14:04 UTC

**Comment by jeanstanis** [comment] 2020-09-30 14:20
Hello,
I've been trying for several months now, in vain, to install ubuntu touch. Always the same error that appears in the log.
My tablet has worked with ubuntu touch for several years (until 2019) with UT 15.04. I was hoping to succeed with the new version of ubports-installer 0.4.20 beta.
If you have a solution, I'm interested in...
Thank you for your interest.

**Comment by NeoTheThird** [comment] 2020-09-30 14:27
Hi, we're working on a solution. Be sure to watch issue #1087 (you can subscribe to it, so you'll get notifications if there*s anything new).

**Comment by jeanstanis** [comment] 2020-09-30 14:32
Thank you very much

**Comment by jeanstanis** [comment] 2020-09-30 14:45
I have just reinstalled lineageOS 17.1 unofficially while waiting for the expected solution for UT.
I would like to point out that I regularly use the adb and fastboot commands; however, there seems to be a problem with adb in the installation of UT. Moreover, the userdata partition seems insufficient.
Sorry for the syntax errors, I'm French.

**Comment by NeoTheThird** [comment] 2020-09-30 14:52
> Thank you very much

you're very welcome, thanks for putting up with us 🙃

> there seems to be a problem with adb in the installation of UT

what do you mean? the adb server (the executable that's bundled in the installer), or the adb client (the adb implementation that's receiving the commands in the device)?

**Comment by NeoTheThird** [comment] 2020-09-30 16:03
you'll see the same when you start adb in your terminal :) so everything is working as expected there.

**Comment by jeanstanis** [comment] 2020-09-30 16:22
Ok, so the installation problem is elsewhere.
For the record, I tried, some time ago, a manual installation:
"sudo ubuntu-device-flash --server=http://system-image.ubports.com touch \
--device=flo --channel=ubports-touch/16.04/stable --bootstrap --wipe"
Without more result, even with 15.04.
I wonder if the nexus 7 flo is not obsolete with the sophistication of ubuntu touch?
Thanks again for all the time spent solving all these problems.

**Comment by NeoTheThird** [comment] 2020-09-30 16:35
>  I wonder if the nexus 7 flo is not obsolete with the sophistication of ubuntu touch?

It is not, we still want to support it. I don't have one myself, but i'm positive we'll get to the bottom of this.

**Comment by jeanstanis** [comment] 2020-09-30 16:47
I am willing to wait as long as it takes.
Yours sincerely.
