### ISSUE TITLE
Fastboot: Unknown error:  sending 'recovery' (12592 KB)...OKAY [  1.551s]writing 'recovery'...FAILED (remote: image is not a boot image)finished. total time: 1.555s

### ISSUE THREAD

**Issue by ardalon** [ubports/ubports-installer#654] opened 2019-02-12 17:42 UTC
Hi I was trying to flash Nexus 7 with Ubuntu Touch.  Please let me know how I can install the image manually as both the latest stable and edge versions of ubports-installer crash as below ? 

*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 7 2013 (LTE)
Package: snap
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/ThkW6zZmXW/

**Comment by gregb49** [comment] 2019-02-13 17:54
Similar problem to ardalon. 
I'm trying to flash a new BQ M10 HD Android and am going around in circles. (Linux 4.15.0-45-generic)
I’ve tried the following

- 1. 2 different USB cables.
- 2. Latest version of ubports-installer, with the BQ M10 in Bootloader mode.
- 3. Smart Phone Flash Tool, latest version, using cooler-image MT8163_Android_scatter.txt and being very careful to select firmware upgrade. I click the download button and get 0 B/s 0 Bytes, with the BQ M10 connected. Eventually this times out. Tried with the BQ M10 turned off and also in bootloader mode.

Previously I put UBPorts on a Nexus 5 which has been working well for probably about a year. 

> *Automatically generated error report* 
> UBports Installer Version: 0.1.21-beta 
> Device: BQ M10 HD
> Package: unknown
> Operating System: elementary OS undefined undefined x64 
> NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/NNFFGHFWs6/

**Comment by NeoTheThird** [comment] 2019-03-13 15:22
Duplicate of #639

**Closed by NeoTheThird** 2019-03-13 15:22 UTC
