### ISSUE TITLE
Ubuntu recovery keeps rebooting. Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: stdout: adb: error: failed to copy '/home/jr/.cache/ubports/pool/ubports-cda5dea4fff1c2552edcb7ef2e7a1c3d9504b5f8d695ff6087df67958c4ea02c.tar.xz' to '/cache/recovery/ubports-cda5dea4fff1c2552edcb7ef2e7a1c3d9504b5f8d695ff6087df67958c4ea02c.tar.xz': remote write failed: Read-only file system/home/jr/.cache/ubports/pool/ubports-cda5dea4fff1c2552edcb7ef2e7a1c3d9504b5f8d695ff6087df67958c4ea02c.tar.xz: 0 files pushed, 0 skipped. 15.9 MB/s (214997368 bytes in 12.904s)

### ISSUE THREAD

**Issue by vasyugan** [ubports/ubports-installer#1204] opened 2020-05-06 15:10 UTC
The ubports installer gets as far as installing the ubuntu recovery, after which the device is rebooted into recovery mode. However, the recovery itself keeps rebooting every 30 seconds or so, therefore before the ubports installer gets anything finished, connection is lost. The last messages in /tmp/recovery.log are

```
[    3.045878] ril.subscription.types=NV,RUIM
[    3.045880] persist.radio.lw_enabled=true
[    3.045883] persist.radio.oem_socket=false
[    3.045886] persist.radio.add_power_save=1
[    3.045889] persist.radio.redir_party_num=0
[    3.045891] persist.radio.VT_CAM_INTERFACE=1
[    3.045894] persist.radio.apm_sim_not_pwdn=1
[    3.045897] persist.radio.block_allow_data=1
[    3.045900] sys.usb.config=adb
[    3.045903]


```

*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/fredldotme/devel","wipe":false,"bootstrap":true}
Package: AppImage
Operating System: Debian   10   buster x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/tBmrKF4R7c/

**Comment by vasyugan** [comment] 2020-05-06 16:01
OK, found the solution: To first flash the OEM binaries for AOSP, [as explained at XDA developers](https://forum.xda-developers.com/xperia-x/how-to/sonyx-f5121-downgrade-8-0-0-to-7-1-1-to-t3754986)

It would be great if such information could be added to the device page.

**Comment by NeoTheThird** [comment] 2020-09-23 09:37
Duplicate of #1072

**Closed by NeoTheThird** 2020-09-23 09:37 UTC
