### ISSUE TITLE
Error: Failed to start adb server: Error: {error:{killed:false,code:4294967295,signal:null,cmd:C:\\Users\\zhang\\AppData\\Local\\Temp\\1a29HDbUDo9dPX2PzfzmdVGwUHN\\resources\\app.asar.unpacked\\platform-tools\\win\\adb

### ISSUE THREAD

**Issue by jasonber** [ubports/ubports-installer#1247] opened 2020-06-06 12:47 UTC
the ubports installer can`t conect to the ubports server

**Comment by NeoTheThird** [comment] 2020-09-23 09:33
Duplicate of #1207

**Closed by NeoTheThird** 2020-09-23 09:33 UTC
