### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.759s]booting...FAILED (remote: dtb not found)finished. total time: 0.810s

### ISSUE THREAD

**Issue by nareshkadali9** [ubports/ubports-installer#464] opened 2018-09-22 23:20 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Meizu PRO 5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/Ws7rRxXrc7/

**Comment by blaubaer01** [comment] 2018-10-05 18:32
On Fairphone 2 the Version 0.1.12 works, maybe it will run with Meizu Pro 5 too

**Comment by NeoTheThird** [comment] 2019-03-13 16:32
Duplicate of #699.

**Closed by NeoTheThird** 2019-03-13 16:32 UTC
