### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.960s]booting...FAILED (remote failure)finished. total time: 0.961s

### ISSUE THREAD

**Issue by Billdemoncho** [ubports/ubports-installer#431] opened 2018-08-29 21:13 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Meizu PRO 5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/b6gRwJnx4d/

**Comment by NeoTheThird** [comment] 2019-03-17 16:46
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.

**Closed by NeoTheThird** 2019-03-17 16:46 UTC
