### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/275/app/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/system on /system failed: Invalid argument"}

### ISSUE THREAD

**Issue by GemCom2020** [ubports/ubports-installer#1192] opened 2020-05-01 11:35 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":false,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/rtvbg5RF2M/

**Comment by Bubbelb** [comment] 2020-05-15 13:00
Same here

**Comment by NeoTheThird** [comment] 2020-09-23 08:44
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:44 UTC
