### ISSUE TITLE
kongo

### ISSUE THREAD

**Issue by koba29** [ubports/ubports-installer#1841] opened 2021-03-10 08:59 UTC
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60488a3e52bd840007f91f45
Log: https://paste.ubuntu.com/p/6k88B6htVG/

kongo

**Comment by NeoTheThird** [comment] 2021-03-10 10:02
Duplicate of #1831, sorry about that.

**Closed by NeoTheThird** 2021-03-10 10:02 UTC
