### ISSUE TITLE
Error: systemimage: Error: Can't find latest version: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by kkk-code** [ubports/ubports-installer#1350] opened 2020-09-15 15:21 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/stable","wipe":true,"bootstrap":false}
Package: snap
Operating System: Ubuntu 16.04 xenial x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/mpwzvSs68d/

**Comment by NeoTheThird** [comment] 2020-09-23 08:34
Duplicate of #1340

**Closed by NeoTheThird** 2020-09-23 08:34 UTC
