### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by dedero1985** [ubports/ubports-installer#1201] opened 2020-05-05 18:01 UTC
Hi, I would like to report this bug for Mako, I've installed it from a complete fresh 5.1.1 android factory image installation with usb debug activated and no luck, would you please check?

Thanks!

*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/zc3JF8WvwM/

**Comment by NeoTheThird** [comment] 2020-09-23 09:56
Duplicate of #1089

**Closed by NeoTheThird** 2020-09-23 09:56 UTC
