### ISSUE TITLE
Fastboot: Unknown error:  [sudo] Passwort für eric: downloading 'boot.img'...OKAY [  0.371s]booting...FAILED (remote: unknown command)finished. total time: 0.373s

### ISSUE THREAD

**Issue by LinuxfarmerHH** [ubports/ubports-installer#606] opened 2019-01-07 17:12 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ Aquaris E4.5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/zqrFzpn2ZZ/

**Comment by NeoTheThird** [comment] 2019-03-13 14:53
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.

**Closed by NeoTheThird** 2019-03-13 14:53 UTC
