### ISSUE TITLE
Device doesn't reboot to bootloader

### ISSUE THREAD

**Issue by jonnycraeen** [ubports/ubports-installer#410] opened 2018-08-18 21:52 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: OnePlus One
Package: exe
Operating

**Comment by phihuynh** [comment] 2018-08-19 05:39
Tp link 601a

**Comment by NeoTheThird** [comment] 2019-03-10 10:04
Duplicate of #116.

**Closed by NeoTheThird** 2019-03-10 10:04 UTC
