### ISSUE TITLE
does not detect when device is in bootloader mode, provides no interface to manually proceed

### ISSUE THREAD

**Issue by ManOfScience** [ubports/ubports-installer#443] opened 2018-09-02 16:29 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: OnePlus One
Package: exe
Operating

**Comment by NeoTheThird** [comment] 2019-03-10 10:05
Duplicate of #116.

**Closed by NeoTheThird** 2019-03-10 10:05 UTC
