### ISSUE TITLE
[sargo] more loop boots

### ISSUE THREAD

**Issue by hahapewpew** [ubports/ubports-installer#1564] opened 2020-11-21 00:53 UTC
**UBports Installer `0.7.4-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.16.3`
Device: sargo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fb8650b9702a600079dd8c0
Log: *N/A*

didn't identify that device was connected when first plugged in on fastboot, ran as admin, tried the release candidate, still bootloop

**Comment by NeoTheThird** [comment] 2020-12-01 10:23
Duplicate of #1563

**Closed by NeoTheThird** 2020-12-01 10:23 UTC
Labels: question
