### ISSUE TITLE
Nexus 6P install fail

### ISSUE THREAD

**Issue by 7evin** [ubports/ubports-installer#1515] opened 2020-11-09 18:39 UTC
**UBports Installer `0.7.0-beta` (exe)**
Environment: `Microsoft Windows 10 Home N 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.16.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa98cd79702a600079dbaac
Log: https://paste.ubuntu.com/p/fxy72Mp9td/

Ran installer with phone in bootloader and UBPorts Recovery, both fail while installer says "Falshing firmware...." Only when running installer from recovery does this error come up

**Comment by NeoTheThird** [comment] 2020-11-12 10:39
Duplicate of #1530

**Closed by NeoTheThird** 2020-11-12 10:39 UTC
