### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blacklist' of undefined (MainRenderer:360)

### ISSUE THREAD

**Issue by Viradj** [ubports/ubports-installer#218] opened 2018-04-28 22:22 UTC
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/NNKtZyWxy9/

**Comment by NeoTheThird** [comment] 2018-04-30 03:32
Duplicate of #124.

**Closed by NeoTheThird** 2018-04-30 03:32 UTC
