### ISSUE TITLE
The program doesn't seem to recognize the nexus 4 bootloader

### ISSUE THREAD

**Issue by Skievar** [ubports/ubports-installer#486] opened 2018-10-08 17:44 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 4
Package: exe
Operating Syst

**Comment by NeoTheThird** [comment] 2019-03-10 10:06
Duplicate of #116.

**Closed by NeoTheThird** 2019-03-10 10:06 UTC
