### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, chmod 'C:\Users\natsu\AppData\Local\Temp\tmp-18764pvNmIR45kFoM\adb.exe' (MainRenderer:250)

### ISSUE THREAD

**Issue by Natsuten** [ubports/ubports-installer#730] opened 2019-03-23 11:33 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.1-beta 
Device: Not detected
Channel: Not yet set
Package: exe
Operating System: Microsoft Windows [�汾 10.0.17763.379] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/JrXH8V36vp/

**Comment by NeoTheThird** [comment] 2019-03-24 06:56
Duplicate of #728

**Closed by NeoTheThird** 2019-03-24 06:56 UTC
