### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for p: downloading 'boot.img'...OKAY [  0.369s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.370s

### ISSUE THREAD

**Issue by pnm4sfix** [ubports/ubports-installer#539] opened 2018-11-17 01:11 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux   18.04   bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/xSTZ9zgVNQ/

**Comment by jonnius** [comment] 2018-12-13 17:44
duplicate of #184

**Closed** 2019-03-10 08:56 UTC
Labels: duplicate
