### ISSUE TITLE
Adb push error: cannot stat ''C:\Users\dselling\AppData\Roaming\ubports\pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz'': No such file or directory

### ISSUE THREAD

**Issue by dselling** [ubports/ubports-installer#264] opened 2018-05-18 13:11 UTC
Auto

**Comment by NeoTheThird** [comment] 2018-05-25 11:07
Duplicate of #110. Please try agian with [this version](https://github.com/ubports/ubports-installer/releases/download/0.1.9-beta/ubports-installer.0.1.9-beta.exe).

**Closed by NeoTheThird** 2018-05-25 11:07 UTC
