### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for ***: target reported max download size of 134217728 bytessending 'recovery' (11450 KB)...OKAY [  0.501s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.505s

### ISSUE THREAD

**Issue by lfortanet** [ubports/ubports-installer#616] opened 2019-01-14 08:00 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ M10 FHD
Package: unknown
Operating System: Debian 9.6 stretch x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/2MbDpQD8zg/

**Comment by NeoTheThird** [comment] 2019-03-13 14:48
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.

**Closed by NeoTheThird** 2019-03-13 14:48 UTC
