### ISSUE TITLE
google pixel 3a not possible to install ubuntu touch just shows google logo after change to recovery mode

### ISSUE THREAD

**Issue by something-wrong** [ubports/ubports-installer#1861] opened 2021-03-17 22:46 UTC
**UBports Installer `0.8.7-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-44-generic x64 NodeJS v12.18.3`
Device: sargo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/605285f9af4b210007b255c1
Log: https://paste.ubuntu.com/p/8MzHtJvpgp/

after step change to recovery mode with the button just shows google logo

**Comment by UniversalSuperBox** [comment] 2021-04-20 21:33
Duplicate of https://github.com/ubports/ubports-installer/issues/1811

**Closed by UniversalSuperBox** 2021-04-20 21:33 UTC
