### ISSUE TITLE
Installer in Windows 8.1 doesn't detect Fairphone 2

### ISSUE THREAD

**Issue by jh-frank** [ubports/ubports-installer#361] opened 2018-07-07 19:06 UTC
I am using Windows 8.1 and want to install Ubuntu touch to a Fairphone 2, that I bought two weeks ago. I started ubports-installer.0.1.19-beta.exe. It does not detect my FP2. As recommended I installed Android Studio, chose "Select device manually". In "Custom tools" I filled in the path for adb and fastboot. I started the FP2 bootloader, waited for almost an hour, but nothing happens. What can I do?

**Comment by NeoTheThird** [comment] 2018-07-07 20:06
Hmm, very weird. This seems to be an issue on Windows 10 and Windows 8 only. I don't know how technical you are, but if you're comfortable with that, you could try [running the program from source](https://github.com/ubports/ubports-installer#how-to-run-the-program-from-source). That usually works. For some reason, we can not see the device on Windows 10 when running as an exe...

**Comment by jh-frank** [comment] 2018-07-08 06:53
I realized one more thing: Before installing the adb driver, there was an entry in the windows device manager called "FP", followed by a question mark. After installing it just says "Android Device/Android Composite ADB Interface". So the entry's name changed. For what kind of names is the ubports installer looking for?

**Comment by NeoTheThird** [comment] 2018-07-08 09:45
To be honest, i have no idea. The entries might well be arbitrary. As long as adb.exe detects the device in system and recovery and fastboot.exe detects the device in bootloader mode, you know that the driver is correct. But the problem is, that fastboot and adb for some weird reason do not see the devices when running from inside the exe, only when running from source.

**Comment by NeoTheThird** [comment] 2019-03-10 10:02
Duplicate of #116.

**Closed by NeoTheThird** 2019-03-10 10:02 UTC
