### ISSUE TITLE
It worked as expected but after installing update it freezes on 'sony'

### ISSUE THREAD

**Issue by Skyliner-369** [ubports/ubports-installer#1503] opened 2020-11-06 23:48 UTC
**UBports Installer `0.6.0-beta` (deb)**
Environment: `Ubuntu 20.04.1 LTS Focal Fossa linux 5.4.0-52-generic x64 NodeJS v12.16.3`
Device: dora
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa5e0d49702a600079db2cf
Log: *N/A*

I just installed but somehow it doesn't work.

**Comment by NeoTheThird** [comment] 2020-11-08 10:23
Thank you for reporting. Duplicate of #1420

**Closed by NeoTheThird** 2020-11-08 10:23 UTC
