### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by princesafee** [ubports/ubports-installer#1139] opened 2020-03-10 04:07 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:false,bootstrap:true,format:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18363.693] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/vtQHC6rmyz/

**Comment by NeoTheThird** [comment] 2020-09-23 10:00
Duplicate of #1052

**Closed by NeoTheThird** 2020-09-23 10:00 UTC
