### ISSUE TITLE
Error: adb:format: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/cache on /cache failed: Device or resource busy

### ISSUE THREAD

**Issue by sharpINU** [ubports/ubports-installer#1334] opened 2020-09-04 15:01 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:false,bootstrap:true,format:false}
Package: exe
Operating System: Microsoft Windows [Version 10.0.19041.450] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/mT5z2wvjyP/

**Comment by NeoTheThird** [comment] 2020-09-23 08:42
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:42 UTC
