### ISSUE TITLE
screen locked in adb

### ISSUE THREAD

**Issue by jesus6505** [ubports/ubports-installer#1582] opened 2020-11-26 09:54 UTC
**UBports Installer `0.7.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-51-generic x64 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fbf7b289702a600079de66d
Log: *N/A*

in previous versions when the adb screen wan reached the phone was restarted in recovery in his version must be done manually

**Comment by NeoTheThird** [comment] 2020-11-30 13:59
Duplicate of #1575

**Closed by NeoTheThird** 2020-11-30 13:59 UTC
