### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.370s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.372s

### ISSUE THREAD

**Issue by epierre3** [ubports/ubports-installer#733] opened 2019-03-25 07:51 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: snap
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/jwzsj4cY7s/

**Comment by NeoTheThird** [comment] 2019-03-25 08:44
Sorry about that. Duplicate of #184.

**Closed by NeoTheThird** 2019-03-25 08:44 UTC

**Comment by NeoTheThird** [comment] 2019-03-25 08:50
Maybe you could try that with the current prerelease? You can download it [here](https://github.com/ubports/ubports-installer/releases/tag/0.2.2-beta), or install it using `snap refresh ubports-installer --candidate` and `snap connect ubports-installer:adb-support`. Please let me know if that works!
