### ISSUE TITLE
Empty screen after connecting the device

### ISSUE THREAD

**Issue by mardy** [ubports/ubports-installer#884] opened 2019-09-17 20:19 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.7-beta 
Device: krillin
Channel: Not yet set
Package: AppImage
Operating System: Ubuntu Linux  16.04  xenial x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/YKyFy4zFKf/ 

After connecting the device, I get a mostly empty screen.
![Screenshot from 2019-09-17 22-19-20](https://user-images.githubusercontent.com/59287/65076410-3ab9f580-d999-11e9-9a2d-12fb4dc3866c.png)

**Comment by mardy** [comment] 2019-09-17 20:22
Forgot to mention: the installer thinks that this is a legacy android device, even though I just followed the [instructions](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices) to flash the old Ubuntu image.

**Comment by NeoTheThird** [comment] 2019-09-17 21:17
Duplicate of #806. Just close the installer and try again. Will be fixed properly soon.

**Comment by mardy** [comment] 2019-09-18 06:35
I tried many times, I suspect that the issue is another one. Could it be that my device is oem locked (I just installed the old Ubuntu image on it)? When I run

    sudo fastboot eom unlock

I just get three dots on the screen, and the program hangs. I will try running the installer more times and I will close this bug if indeed I get to see the install button, anyway.

**Comment by NeoTheThird** [comment] 2019-09-18 09:36
No, the installer does the oem unlocking for you.

**Comment by mardy** [comment] 2019-09-18 19:28
> No, the installer does the oem unlocking for you.

Could it be that it's failing, and that is the cause for this bug? I've now tried to run it more than ten times, and I always got to this blank screen.

**Comment by NeoTheThird** [comment] 2019-09-19 07:25
Might be, i have to experiment with that, thanks for the hint. So you can't get it to unlock manually?

**Closed** 2019-10-05 13:59 UTC
