### ISSUE TITLE
Nexus 7 2013 WiFi ubports installation fails 

### ISSUE THREAD

**Issue by andytough** [ubports/ubports-installer#890] opened 2019-09-23 21:11 UTC
Thank you for the work you have put in to ubports.

*Automatically generated error report* 
Fastboot: Unknown error:  Password:Sending 'recovery' (10044 KB)                      OKAY [  1.244s]Writing 'recovery'                                 OKAY [  0.745s]Finished. Total time: 2.054sSending 'boot' (11320 KB)                          OKAY [  1.399s]Writing 'boot'                                     FAILED (remote: '(InvalidSize)')fastboot: error: Command failed

UBports Installer Version: 0.2.7-beta 
Device: flo
Channel: ubports-touch/16.04/stable
Package: dmg
Operating System: macOS 10.14.618G84 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/GMSt7BzFc6/ 

I get the same error if I run the installation manually:
```
fastboot flash boot boot.img
Sending 'boot' (11320 KB)                          OKAY [  1.452s]
Writing 'boot'                                     FAILED (remote: '(InvalidSize)')
```

**Comment by NeoTheThird** [comment] 2019-09-27 02:39
Duplicate of #615. Sorry about that.

**Closed by NeoTheThird** 2019-09-27 02:39 UTC
