### ISSUE TITLE
[krillin] IMEI disappears after installing ubports

### ISSUE THREAD

**Issue by HaleyACS** [ubports/ubports-installer#562] opened 2018-11-30 09:25 UTC
Device: Aquaris E4.5 Ubuntu Edition
UBports release: RC 2018-W48
Tested: Installation wizard to clean system

IMEI partition seems to be gone after going from official Android version to UBPorts, resulting in no more IMEI data in the system.
There is a possibility to re-install official android and add the IMEI back in, but non found under UBPorts yet. Going back from official android to ubports deletes again the IMEI.

**Comment by HaleyACS** [comment] 2018-11-30 15:06
Note - I fixed my IMEI issue by downloading imei.exe (Dark Net, it is not available) command line utility.

Executed: wine imei.exe <imei1> <imei2>
which dumped me a new file: MP0B_001_NEW

Replaced /android/data/nvram/md/NVRAM/NVD_IMEI/MP0B_001 with that file in my ubuntu phone.
Rebooted, and I had my IMEI back.

Note - it took me 3 hours to identify what was needed to be done - as it really takes only a minute to fix.
Finding imei.exe was difficult, as all Google tools tell you it is malicious code and prevent you from downloading it. So dark-channels it was to get the file.

**Comment by NeoTheThird** [comment] 2020-10-28 10:16
This might have been caused by sp flash tool, not the installer. Our [docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices) are clear to select FIRMWARE UPGRADE, not doing so might result in issues like this. Due to the age of this issue, i'm going to close this for now.

**Closed by NeoTheThird** 2020-10-28 10:16 UTC
Labels: needs confirmation
