### ISSUE TITLE
Error: configure: Error: fetching system image channels failed: Error: Request failed with status code 522

### ISSUE THREAD

**Issue by bhonehtetaung** [ubports/ubports-installer#1439] opened 2020-10-09 16:32 UTC
UBports Installer: `0.5.2-beta` 
Device: `turbo` 
OS to install: Ubuntu Touch 
Settings: undefined 
Package: `exe` 
Operating System: Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 
NodeJS version: `v12.0.0` 
Error log: https://paste.ubuntu.com//p/pnCSM6VdYY/ 
``` 
Error: configure: Error: fetching system image channels failed: Error: Request failed with status code 522 
```

**Comment by NeoTheThird** [comment] 2020-10-09 17:22
Duplicate of #1346

**Closed by NeoTheThird** 2020-10-09 17:22 UTC
