### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 1073741824 bytessending 'recovery' (11844 KB)...OKAY [  0.507s]writing 'recovery'...FAILED (remote: not supported in locked device)finished. total time: 0.607s

### ISSUE THREAD

**Issue by lascapi** [ubports/ubports-installer#18] opened 2017-08-16 18:40 UTC
Automatically generated error report %0AVersion: 0.1.4-beta %0AHost OS: darwin %0AHost Dist: undefined undefined%0AHost Arch: x64 %0ANode: v7.4.0 %0A%0AError log: http://paste.ubuntu.com/25327300/ %0A

**Comment by NeoTheThird** [comment] 2017-08-16 22:35
Duplicate of #17.

**Closed by NeoTheThird** 2017-08-16 22:35 UTC
Labels: duplicate
