### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\WINDOWS\\TEMP\\1jZdYrkqnbzAZoGRTA5fqH0JXK9\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe\" -P 5037 shell 'mount -a || true'"},"stdout":"","stderr":"/sbin/sh: no closing quote\r\n\"true'\" �� ���� ����७��� ��� ���譥�\r\n��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���."}

### ISSUE THREAD

**Issue by JuicyFpyKT** [ubports/ubports-installer#1526] opened 2020-11-11 16:28 UTC
**UBports Installer `0.6.0-beta` (exe)**
Environment: `Microsoft Windows 10 Pro for Workstations 10.0.20251 win32 10.0.20251 x64 20251 0.0 NodeJS v12.16.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fac11139702a600079dbfd9
Log: *N/A*

Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\WINDOWS\\TEMP\\1jZdYrkqnbzAZoGRTA5fqH0JXK9\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe\" -P 5037 shell 'mount -a || true'"},"stdout":"","stderr":"/sbin/sh: no closing quote\r\n\"true'\" �� ���� ����७��� ��� ���譥�\r\n��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���."}

**Comment by NeoTheThird** [comment] 2020-11-12 08:32
Duplicate of #1474

**Closed by NeoTheThird** 2020-11-12 08:32 UTC
