### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >downloading 'boot.img'...OKAY [  0.767s]booting...FAILED (remote: unknown command)finished. total time: 0.781s

### ISSUE THREAD

**Issue by zikaras** [ubports/ubports-installer#329] opened 2018-06-25 20:12 UTC
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/GzDsjt2Gt2/

**Comment by NeoTheThird** [comment] 2018-07-01 19:08
What OS is your device running right now?

**Comment by zikaras** [comment] 2018-07-02 06:29
I installed Ubuntu on the Meizu MX4. I wanted to update but not successful.

2018-07-01, sk, 22:08 Jan Sprinz <notifications@github.com> rašė:

**Comment by NeoTheThird** [comment] 2018-07-02 09:31
So it is running Ubuntu Touch from Canonical or UBports? What OS did the device come with?

**Comment by NeoTheThird** [comment] 2018-07-04 22:34
Could you try again with [the latest version](https://github.com/ubports/ubports-installer/releases/latest)?

**Comment by NeoTheThird** [comment] 2019-03-13 15:00
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.

**Closed by NeoTheThird** 2019-03-13 15:00 UTC
Labels: needs confirmation
