### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.263s]booting...FAILED (remote: dtb not found)finished. total time: 0.422s

### ISSUE THREAD

**Issue by 306730204** [ubports/ubports-installer#770] opened 2019-04-29 03:06 UTC
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: bacon
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [�汾 10.0.16299.1004] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/3Thh5hhWPQ/

**Comment by NeoTheThird** [comment] 2019-08-27 08:32
Sorry about that. Duplicate of #699.

**Closed by NeoTheThird** 2019-08-27 08:32 UTC
