### ISSUE TITLE
install fails on windows for nexus 6p

### ISSUE THREAD

**Issue by ryan-morris** [ubports/ubports-installer#1513] opened 2020-11-08 21:22 UTC
**UBports Installer `0.6.0-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.16.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa857519702a600079db819
Log: https://paste.ubuntu.com/p/7yq9prJXff/

Just followed the instructions, phone would reboot to ubports recovery, but would never get to transferring files to system. just stuck on "preparing system-image"

I was able to get phone flashed on pop os using the latest ubports installer so seems like a windows issue only to me.

**Comment by NeoTheThird** [comment] 2020-11-08 22:52
Sorry about that, duplicate of #1474. Fixed in the next release.

**Closed by NeoTheThird** 2020-11-08 22:52 UTC
