### ISSUE TITLE
Remain in bootloader screen

### ISSUE THREAD

**Issue by mbzadegan** [ubports/ubports-installer#768] opened 2019-04-24 20:18 UTC
I installed adb driver and I can communicate with adb to my device without any problems but when I want to installing the ubports on my device (Nexus 5) it shows boot loader screen but ubports does not start installing on my device and remain on its screen that announce:
PLEASE REBOOT TO BOOTLOADER
and show the two keys pressing
How can I resolve my problem?
Thanks in advance.

*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.17134.706] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/bJqzy5t9PQ/

**Comment by NeoTheThird** [comment] 2019-08-27 12:12
Sorry about that, duplicate of #806.

**Closed by NeoTheThird** 2019-08-27 12:12 UTC
