### ISSUE TITLE
Error: oem unlock failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot oem unlock"},"stdout":"","stderr":"FAILED (remote: 'Incorrect format for unlock data. Should be on the form \"0x')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by ubuntusol** [ubports/ubports-installer#1232] opened 2020-05-22 14:20 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/fredldotme/devel","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/cSxm4bG7t9/

**Comment by NeoTheThird** [comment] 2020-09-23 10:31
Duplicate of #1071

**Closed by NeoTheThird** 2020-09-23 10:31 UTC
