### ISSUE TITLE
Fastboot: Unknown error:  [sudo] Mot de passe de fox : downloading 'boot.img'...OKAY [  0.862s]booting...FAILED (remote failure)finished. total time: 0.862s

### ISSUE THREAD

**Issue by lalannne** [ubports/ubports-installer#490] opened 2018-10-12 13:45 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Ubuntu Linux  16.04  xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/SXpf48xsvr/

**Comment by NeoTheThird** [comment] 2019-03-17 16:47
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.

**Closed by NeoTheThird** 2019-03-17 16:47 UTC
