### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.720s]booting...FAILED (remote: unknown command)finished. total time: 0.734s

### ISSUE THREAD

**Issue by zacardec** [ubports/ubports-installer#595] opened 2019-01-01 09:54 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu MX4
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/vRSy4Dc9HD/

**Comment by zacardec** [comment] 2019-01-01 09:58
Hello,
First, scuse for my poor english. I try to install on my MX4. Originaly, it was running on ubuntutouch, but cause of a persistant bug not solved with phone app, i had install flyme. Now I'll try again new version of ubports but i can't. Ubports installer still ask me to be upgrade .

**Comment by NeoTheThird** [comment] 2019-03-13 14:56
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.

**Closed by NeoTheThird** 2019-03-13 14:56 UTC
