### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.590s]booting...FAILED (remote failure)finished. total time: 0.590s

### ISSUE THREAD

**Issue by robertoduwe** [ubports/ubports-installer#563] opened 2018-12-01 21:53 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/p5RqYtPyyd/

**Comment by NeoTheThird** [comment] 2019-03-13 15:34
What OS is the device running right now?

**Comment by NeoTheThird** [comment] 2019-03-17 16:44
Duplicate of #716.

**Closed by NeoTheThird** 2019-03-17 16:44 UTC
Labels: question
