### ISSUE TITLE
Error: Failed to start adb server: Error: {"error":{"killed":false,"code":255,"signal":null,"cmd":"/snap/ubports-installer/275/app/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 start-server"},"stdout":"","stderr":"* daemon not running

### ISSUE THREAD

**Issue by fyfchaos** [ubports/ubports-installer#1261] opened 2020-06-21 14:14 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: snap
Operating System: Ubuntu Linux  undefined  undefined x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/zwhd3QHtPN/

**Comment by NeoTheThird** [comment] 2020-09-23 09:34
Duplicate of #1207

**Closed by NeoTheThird** 2020-09-23 09:34 UTC
