### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.768s]booting...FAILED (remote: unknown command)finished. total time: 0.782s

### ISSUE THREAD

**Issue by zikaras** [ubports/ubports-installer#315] opened 2018-06-23 07:10 UTC
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/H22TF4MbGD/

**Comment by NeoTheThird** [comment] 2018-07-01 10:57
Duplicate of #329. Please do not report the same issue more than once!

**Closed by NeoTheThird** 2018-07-01 10:57 UTC
