### ISSUE TITLE
Adb push error: failed to copy '/home/duwe/snap/ubports-installer/180/.cache/ubports/pool/device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz' to '/cache/recovery//device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz': No space left on device

### ISSUE THREAD

**Issue by robertoduwe** [ubports/ubports-installer#618] opened 2019-01-15 17:29 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: snap
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/ZmdXTkhzsG/

**Comment by siril233** [comment] 2019-01-30 04:20
yesterday I got the same error message while flashing with the installer, 
this is *possibly* not a bug:

flash the working TWRP, adb shell  into it,  then check your partition layout,
the meizu pro 5 android flavor come with 512MB cache and custom partition, while ubuntu flavor has at least 700MB custom and cache partition. 

details here:
https://askubuntu.com/questions/767323/how-to-install-ubuntu-on-meizu-pro-5-that-was-originally-with-android
I managed to follow the tricky repartition procedure, and got ubuntu touch running now.

what I did:
prepare an external micro sd card  with 1 vfat and 1 ext4 part,
copy the .tar.xz files into vfat part,  extract ubuntu xz file to the ext4 part.
instert micro sd into meizu pro 5,
boot TWRP,  adb shell into it,
DONT mount any partition now,
mount the extra sd card part to somewhere handy, 
   mount bind dev directory,  and chroot into extracted system,
   use fdisk ,  copy the text of (or screenshot) the current partition layout,
   delete the 4 partition: 41,42,43,44, 
   and recreate with 9GB system, 1GB custom, 1GB cache,  and smaller userdata,
   I created new 41 part (system) with exact same start location, probably necessary.
   mkfs.ext4 on them.  
   relabel them, for example:  " parted /dev/block/sda -s --name 41 system "  
   and reboot into TWRP to use the new partition table.
   Now mount the partitions, follow the manual install procedure.
   If anything cannot be mounted, something went wrong, you may start over and recheck it.

***  you should be famillar with linux commandline  to finish this. 
    Try on your own risk. and good luck  : )

**Comment by robertoduwe** [comment] 2019-02-11 23:56
Thank you very much

With this information I was able to change the partition table of the device and install it.

Problem solved.

**Comment by NeoTheThird** [comment] 2019-08-28 06:59
Duplicate of #841. Sorry about that.

**Closed by NeoTheThird** 2019-08-28 06:59 UTC
Labels: bug
