### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.361s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.363s

### ISSUE THREAD

**Issue by sommerhoff** [ubports/ubports-installer#638] opened 2019-01-29 12:13 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: snap
Operating System: Ubuntu Linux     18.04     bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/32kZD8Km5W/

**Comment by NeoTheThird** [comment] 2019-03-10 08:52
Duplicate of #184. Try again with UBports Installer 0.1.12-beta.

**Closed by NeoTheThird** 2019-03-10 08:52 UTC
Labels: duplicate
