### ISSUE TITLE
[bacon] Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by arkhub** [ubports/ubports-installer#1272] opened 2020-06-30 09:19 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:true,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.19041.329] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/WkBQ8SXfwd/

**Comment by NeoTheThird** [comment] 2020-10-26 18:33
duplicate of #1032

**Closed by NeoTheThird** 2020-10-26 18:33 UTC
Labels: bug
