### ISSUE TITLE
Error: Failed to start adb server: Error: {error:{killed:false,code:4294967295,signal:null,cmd:C:\\Users\\DELL\\AppData\\Local\\Temp\\1a29HDbUDo9dPX2PzfzmdVGwUHN\\resources\\app.asar.unpacked\\platform-tools\\win\\adb

### ISSUE THREAD

**Issue by dushaopeng** [ubports/ubports-installer#1325] opened 2020-09-01 08:39 UTC

**Comment by NeoTheThird** [comment] 2020-09-23 09:34
Duplicate of #1207

**Closed by NeoTheThird** 2020-09-23 09:34 UTC
