### ISSUE TITLE
Error: systemimage: Error: Can't find latest version: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by PeskeGit** [ubports/ubports-installer#1318] opened 2020-08-26 19:09 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/stable","wipe":true,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/6mBXMzd22r/

**Comment by NeoTheThird** [comment] 2020-09-23 08:35
Duplicate of #1340

**Closed by NeoTheThird** 2020-09-23 08:35 UTC
