### ISSUE TITLE
Nexus 5 wont load past initial Google screen

### ISSUE THREAD

**Issue by MaitreyaMelchizedek** [ubports/ubports-installer#1757] opened 2021-01-26 01:32 UTC
**UBports Installer `0.8.4-beta` (deb)**
Environment: `Ubuntu 20.04.1 LTS Focal Fossa linux 5.8.0-40-generic x64 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/600f710a203a7f0007648fbd
Log: *N/A*

Load UBports on Nexus 5 16GB D820 using UBports Installer on Linux

**Comment by NeoTheThird** [comment] 2021-03-06 17:36
sorry about that, duplicate of #1052

**Closed by NeoTheThird** 2021-03-06 17:36 UTC
