### ISSUE TITLE
Error: systemimage: Error: Can't find latest version: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by kozlovandrei** [ubports/ubports-installer#1319] opened 2020-08-27 16:07 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/stable","wipe":false,"bootstrap":false}
Package: deb
Operating System: Ubuntu Linux undefined undefined x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/ZfzVD5VhC3/

**Comment by NeoTheThird** [comment] 2020-09-23 08:35
Duplicate of #1340

**Closed by NeoTheThird** 2020-09-23 08:35 UTC
