### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/262/app/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: Invalid argument"}

### ISSUE THREAD

**Issue by unclepaulie79** [ubports/ubports-installer#1096] opened 2020-01-09 22:42 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":false,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux undefined undefined x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/QMZYKDyCyv/

**Comment by michael71** [comment] 2020-01-20 16:24
I have exactly the same problem (oneplus3t), OS Ubuntu Linux

**Comment by bblaha** [comment] 2020-01-21 10:18
Can confirm on Linux and Windows with OnePlus 3:

Has anyone solved this? I'd consider myself a rookie, so here's the full steps to what I did:
Flash TWRP
Wipe all partitions
Rebooted to Recovery
Started ubinstaller and let it do its thing

Error: systemimage: Error: Error: {error:{killed:false,code:1,signal:null,cmd:C:\\Users\\XXX\\AppData\\Local\\Temp\\1Uo4H80AYPnCivmpnC8M9LLWxLb\\resources\\app.asar.unpacked\\platform-tools\\win\\adb

**Comment by unclepaulie79** [comment] 2020-01-21 15:59
I have been able to bypass this error by downgrading to Oreo firmware but installer get stuck after "downloading ubuntu touch" on verifying. At least one step forward.

**Comment by NeoTheThird** [comment] 2020-01-22 15:36
Duplicate of #1046

**Closed by NeoTheThird** 2020-01-22 15:36 UTC
Labels: needs confirmation
