### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: No such process"}

### ISSUE THREAD

**Issue by trin94** [ubports/ubports-installer#1179] opened 2020-04-16 17:11 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":true,"bootstrap":true}
Package: source
Operating System: Arch Linux rolling undefined x64 
NodeJS version: v12.4.0 

Error log: https://paste.ubuntu.com//p/RfhcPTt5bx/ 

I wiped **every** partition in the TWRP and changed **every** possible parition to ext4.

**Comment by trin94** [comment] 2020-04-16 17:25
Well I fixed it.

Problem was that the cache partition in TWRP could not be mounted.
So I followed the steps from https://forum.xda-developers.com/showpost.php?p=55104262&postcount=3:

- Flash latest TWRP
- Reboot into Recovery.
- Go to "Wipe".
- Go to "Advanced Wipe".
- Choose "Cache".
- Go to "Repair or Change Filesystem".
- Press "Change Filesystem".
- Press "EXT4".
- Reboot system and wait until Android completely boot up.
- Reboot into recovery to check if problem still persists.

:+1: :smile:

**Comment by NeoTheThird** [comment] 2020-09-23 08:45
duplicate of #1304

**Closed by NeoTheThird** 2020-09-23 08:45 UTC
