### ISSUE TITLE
The phone will only boot into the recovery.

### ISSUE THREAD

**Issue by trebabcock** [ubports/ubports-installer#1773] opened 2021-02-02 02:09 UTC
**UBports Installer `0.8.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.10.9-169.current x64 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6018b431afa951000786d151
Log: *N/A*

Flash stock 7.1.2 and TWRP, then install Ubuntu Touch with the UBports Installer.

**Comment by NeoTheThird** [comment] 2021-03-06 17:31
Sorry about that, duplicate of #1537

**Closed by NeoTheThird** 2021-03-06 17:31 UTC
