### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by Soorsi** [ubports/ubports-installer#1249] opened 2020-06-06 18:44 UTC
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/rc,wipe:true,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18363.836] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/nx5f3B6Mg8/

**Comment by NeoTheThird** [comment] 2020-09-23 09:57
Duplicate of #1089

**Closed by NeoTheThird** 2020-09-23 09:57 UTC
