### ISSUE TITLE
Fastboot: Unknown error:  [sudo] Passwort für jason: downloading 'boot.img'...OKAY [  2.305s]booting...FAILED (remote failure)finished. total time: 2.308s (Meizu Pro5 Ubuntu Edition)

### ISSUE THREAD

**Issue by RenaldoJay** [ubports/ubports-installer#480] opened 2018-09-30 14:28 UTC
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/f88HjQBks3/

**Comment by blaubaer01** [comment] 2018-10-05 18:13
with the Version 0.1.12 on the Fairphone 2 the programm is running

**Comment by NeoTheThird** [comment] 2019-03-17 16:47
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.

**Closed by NeoTheThird** 2019-03-17 16:47 UTC
