### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal [...]  'adb kill-server' if that seems wrong.\nOtherwise check for a confirmation dialog on your device."}

### ISSUE THREAD

**Issue by 00p513-dev** [ubports/ubports-installer#1446] opened 2020-10-11 17:05 UTC
**UBports Installer `0.5.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-20-generic x64` with Node.js `v12.16.3`
Device: bacon
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f833af904d6b6000750b394
Log: https://paste.ubuntu.com//p/CxhcMyxsSt/

**Error:**
```
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/300/app/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/adb -P 5037 shell echo ."},"stdout":"","stderr":"adb: device unauthorized.\nThis adb server's $ADB_VENDOR_KEYS is not set\nTry 'adb kill-server' if that seems wrong.\nOtherwise check for a confirmation dialog on your device."}
```

Happens when trying to install latest devel on my bacon, happened with AppImage and snap...

**Comment by NeoTheThird** [comment] 2020-10-21 13:25
Sorry about that. Duplicate of #983.

**Closed by NeoTheThird** 2020-10-21 13:25 UTC
